"""Base types for strategy compilation and execution."""

from dataclasses import dataclass
from datetime import datetime
from enum import StrEnum
from typing import TypedDict


class SignalMetadata(TypedDict, total=False):
    """Optional signal metadata."""

    indicator_values: dict[str, float]
    reason: str
    strategy_version: int
    strategy_name: str
    strategy_type: str
    exit_reason: str
    pnl_pct: float


class SignalType(StrEnum):
    """Trading signal types."""

    BUY = "buy"
    SELL = "sell"
    CLOSE_LONG = "close_long"
    CLOSE_SHORT = "close_short"
    HOLD = "hold"


@dataclass
class Signal:
    """Trading signal generated by a strategy."""

    type: SignalType
    symbol: str
    price: float
    timestamp: datetime
    confidence: float = 1.0
    quantity_percent: float = 100.0
    stop_loss: float | None = None
    take_profit: float | None = None
    metadata: SignalMetadata | None = None


@dataclass
class Bar:
    """OHLCV bar data."""

    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: int

    def to_dict(self) -> dict:
        return {
            "timestamp": self.timestamp,
            "open": self.open,
            "high": self.high,
            "low": self.low,
            "close": self.close,
            "volume": self.volume,
        }
