"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins as builtins
import sys
import typing as typing
from collections import abc as abc

from google.protobuf import descriptor as descriptor
from google.protobuf import message as message
from google.protobuf.internal import containers as containers
from google.protobuf.internal import enum_type_wrapper as enum_type_wrapper

from llamatrade.v1 import common_pb2 as common_pb2

if sys.version_info >= (3, 10):
    pass
else:
    pass

DESCRIPTOR: descriptor.FileDescriptor

class _SubscriptionStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    type V = ValueType  # noqa: Y015

class _SubscriptionStatusEnumTypeWrapper(enum_type_wrapper._EnumTypeWrapper[_SubscriptionStatus.ValueType], builtins.type):
    DESCRIPTOR: descriptor.EnumDescriptor
    SUBSCRIPTION_STATUS_UNSPECIFIED: _SubscriptionStatus.ValueType  # 0
    SUBSCRIPTION_STATUS_ACTIVE: _SubscriptionStatus.ValueType  # 1
    SUBSCRIPTION_STATUS_PAST_DUE: _SubscriptionStatus.ValueType  # 2
    SUBSCRIPTION_STATUS_CANCELED: _SubscriptionStatus.ValueType  # 3
    SUBSCRIPTION_STATUS_TRIALING: _SubscriptionStatus.ValueType  # 4
    SUBSCRIPTION_STATUS_PAUSED: _SubscriptionStatus.ValueType  # 5

class SubscriptionStatus(_SubscriptionStatus, metaclass=_SubscriptionStatusEnumTypeWrapper):
    """=============================================================================
    ENUMS
    =============================================================================

    Subscription status
    """

SUBSCRIPTION_STATUS_UNSPECIFIED: SubscriptionStatus.ValueType  # 0
SUBSCRIPTION_STATUS_ACTIVE: SubscriptionStatus.ValueType  # 1
SUBSCRIPTION_STATUS_PAST_DUE: SubscriptionStatus.ValueType  # 2
SUBSCRIPTION_STATUS_CANCELED: SubscriptionStatus.ValueType  # 3
SUBSCRIPTION_STATUS_TRIALING: SubscriptionStatus.ValueType  # 4
SUBSCRIPTION_STATUS_PAUSED: SubscriptionStatus.ValueType  # 5

class _PlanTier:
    ValueType = typing.NewType("ValueType", builtins.int)
    type V = ValueType  # noqa: Y015

class _PlanTierEnumTypeWrapper(enum_type_wrapper._EnumTypeWrapper[_PlanTier.ValueType], builtins.type):
    DESCRIPTOR: descriptor.EnumDescriptor
    PLAN_TIER_UNSPECIFIED: _PlanTier.ValueType  # 0
    PLAN_TIER_FREE: _PlanTier.ValueType  # 1
    PLAN_TIER_STARTER: _PlanTier.ValueType  # 2
    PLAN_TIER_PROFESSIONAL: _PlanTier.ValueType  # 3
    PLAN_TIER_ENTERPRISE: _PlanTier.ValueType  # 4

class PlanTier(_PlanTier, metaclass=_PlanTierEnumTypeWrapper):
    """Plan tier"""

PLAN_TIER_UNSPECIFIED: PlanTier.ValueType  # 0
PLAN_TIER_FREE: PlanTier.ValueType  # 1
PLAN_TIER_STARTER: PlanTier.ValueType  # 2
PLAN_TIER_PROFESSIONAL: PlanTier.ValueType  # 3
PLAN_TIER_ENTERPRISE: PlanTier.ValueType  # 4

class _BillingInterval:
    ValueType = typing.NewType("ValueType", builtins.int)
    type V = ValueType  # noqa: Y015

class _BillingIntervalEnumTypeWrapper(enum_type_wrapper._EnumTypeWrapper[_BillingInterval.ValueType], builtins.type):
    DESCRIPTOR: descriptor.EnumDescriptor
    BILLING_INTERVAL_UNSPECIFIED: _BillingInterval.ValueType  # 0
    BILLING_INTERVAL_MONTHLY: _BillingInterval.ValueType  # 1
    BILLING_INTERVAL_YEARLY: _BillingInterval.ValueType  # 2

class BillingInterval(_BillingInterval, metaclass=_BillingIntervalEnumTypeWrapper):
    """Billing interval"""

BILLING_INTERVAL_UNSPECIFIED: BillingInterval.ValueType  # 0
BILLING_INTERVAL_MONTHLY: BillingInterval.ValueType  # 1
BILLING_INTERVAL_YEARLY: BillingInterval.ValueType  # 2

@typing.final
class Plan(message.Message):
    """=============================================================================
    MESSAGES
    =============================================================================

    Subscription plan
    """

    DESCRIPTOR: descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    TIER_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    MONTHLY_PRICE_FIELD_NUMBER: builtins.int
    YEARLY_PRICE_FIELD_NUMBER: builtins.int
    MAX_STRATEGIES_FIELD_NUMBER: builtins.int
    MAX_BACKTESTS_PER_MONTH_FIELD_NUMBER: builtins.int
    MAX_LIVE_SESSIONS_FIELD_NUMBER: builtins.int
    DATA_RETENTION_DAYS_FIELD_NUMBER: builtins.int
    FEATURES_FIELD_NUMBER: builtins.int
    API_ACCESS_FIELD_NUMBER: builtins.int
    PRIORITY_SUPPORT_FIELD_NUMBER: builtins.int
    id: builtins.str
    name: builtins.str
    tier: PlanTier.ValueType
    description: builtins.str
    max_strategies: builtins.int
    """Limits"""
    max_backtests_per_month: builtins.int
    max_live_sessions: builtins.int
    data_retention_days: builtins.int
    api_access: builtins.bool
    priority_support: builtins.bool
    @builtins.property
    def monthly_price(self) -> common_pb2.Money:
        """Pricing"""

    @builtins.property
    def yearly_price(self) -> common_pb2.Money: ...
    @builtins.property
    def features(self) -> containers.RepeatedScalarFieldContainer[builtins.str]:
        """Features"""

    def __init__(
        self,
        *,
        id: builtins.str = ...,
        name: builtins.str = ...,
        tier: PlanTier.ValueType = ...,
        description: builtins.str = ...,
        monthly_price: common_pb2.Money | None = ...,
        yearly_price: common_pb2.Money | None = ...,
        max_strategies: builtins.int = ...,
        max_backtests_per_month: builtins.int = ...,
        max_live_sessions: builtins.int = ...,
        data_retention_days: builtins.int = ...,
        features: abc.Iterable[builtins.str] | None = ...,
        api_access: builtins.bool = ...,
        priority_support: builtins.bool = ...,
    ) -> None: ...
    type _HasFieldArgType = typing.Literal["monthly_price", b"monthly_price", "yearly_price", b"yearly_price"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    type _ClearFieldArgType = typing.Literal["api_access", b"api_access", "data_retention_days", b"data_retention_days", "description", b"description", "features", b"features", "id", b"id", "max_backtests_per_month", b"max_backtests_per_month", "max_live_sessions", b"max_live_sessions", "max_strategies", b"max_strategies", "monthly_price", b"monthly_price", "name", b"name", "priority_support", b"priority_support", "tier", b"tier", "yearly_price", b"yearly_price"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class Subscription(message.Message):
    """Subscription"""

    DESCRIPTOR: descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    TENANT_ID_FIELD_NUMBER: builtins.int
    PLAN_ID_FIELD_NUMBER: builtins.int
    PLAN_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    INTERVAL_FIELD_NUMBER: builtins.int
    CURRENT_PRICE_FIELD_NUMBER: builtins.int
    CURRENT_PERIOD_START_FIELD_NUMBER: builtins.int
    CURRENT_PERIOD_END_FIELD_NUMBER: builtins.int
    IS_TRIAL_FIELD_NUMBER: builtins.int
    TRIAL_END_FIELD_NUMBER: builtins.int
    CANCEL_AT_PERIOD_END_FIELD_NUMBER: builtins.int
    CANCELED_AT_FIELD_NUMBER: builtins.int
    CANCELLATION_REASON_FIELD_NUMBER: builtins.int
    STRIPE_SUBSCRIPTION_ID_FIELD_NUMBER: builtins.int
    STRIPE_CUSTOMER_ID_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    id: builtins.str
    tenant_id: builtins.str
    plan_id: builtins.str
    status: SubscriptionStatus.ValueType
    interval: BillingInterval.ValueType
    is_trial: builtins.bool
    """Trial info"""
    cancel_at_period_end: builtins.bool
    """Cancellation"""
    cancellation_reason: builtins.str
    stripe_subscription_id: builtins.str
    """External references"""
    stripe_customer_id: builtins.str
    @builtins.property
    def plan(self) -> Plan: ...
    @builtins.property
    def current_price(self) -> common_pb2.Money:
        """Billing details"""

    @builtins.property
    def current_period_start(self) -> common_pb2.Timestamp: ...
    @builtins.property
    def current_period_end(self) -> common_pb2.Timestamp: ...
    @builtins.property
    def trial_end(self) -> common_pb2.Timestamp: ...
    @builtins.property
    def canceled_at(self) -> common_pb2.Timestamp: ...
    @builtins.property
    def created_at(self) -> common_pb2.Timestamp:
        """Timestamps"""

    @builtins.property
    def updated_at(self) -> common_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        tenant_id: builtins.str = ...,
        plan_id: builtins.str = ...,
        plan: Plan | None = ...,
        status: SubscriptionStatus.ValueType = ...,
        interval: BillingInterval.ValueType = ...,
        current_price: common_pb2.Money | None = ...,
        current_period_start: common_pb2.Timestamp | None = ...,
        current_period_end: common_pb2.Timestamp | None = ...,
        is_trial: builtins.bool = ...,
        trial_end: common_pb2.Timestamp | None = ...,
        cancel_at_period_end: builtins.bool = ...,
        canceled_at: common_pb2.Timestamp | None = ...,
        cancellation_reason: builtins.str = ...,
        stripe_subscription_id: builtins.str = ...,
        stripe_customer_id: builtins.str = ...,
        created_at: common_pb2.Timestamp | None = ...,
        updated_at: common_pb2.Timestamp | None = ...,
    ) -> None: ...
    type _HasFieldArgType = typing.Literal["canceled_at", b"canceled_at", "created_at", b"created_at", "current_period_end", b"current_period_end", "current_period_start", b"current_period_start", "current_price", b"current_price", "plan", b"plan", "trial_end", b"trial_end", "updated_at", b"updated_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    type _ClearFieldArgType = typing.Literal["cancel_at_period_end", b"cancel_at_period_end", "canceled_at", b"canceled_at", "cancellation_reason", b"cancellation_reason", "created_at", b"created_at", "current_period_end", b"current_period_end", "current_period_start", b"current_period_start", "current_price", b"current_price", "id", b"id", "interval", b"interval", "is_trial", b"is_trial", "plan", b"plan", "plan_id", b"plan_id", "status", b"status", "stripe_customer_id", b"stripe_customer_id", "stripe_subscription_id", b"stripe_subscription_id", "tenant_id", b"tenant_id", "trial_end", b"trial_end", "updated_at", b"updated_at"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class Usage(message.Message):
    """Usage metrics"""

    DESCRIPTOR: descriptor.Descriptor

    TENANT_ID_FIELD_NUMBER: builtins.int
    PERIOD_ID_FIELD_NUMBER: builtins.int
    STRATEGIES_CREATED_FIELD_NUMBER: builtins.int
    ACTIVE_STRATEGIES_FIELD_NUMBER: builtins.int
    BACKTESTS_RUN_FIELD_NUMBER: builtins.int
    BACKTEST_COMPUTE_MINUTES_FIELD_NUMBER: builtins.int
    LIVE_SESSIONS_FIELD_NUMBER: builtins.int
    ORDERS_PLACED_FIELD_NUMBER: builtins.int
    MARKET_DATA_REQUESTS_FIELD_NUMBER: builtins.int
    STORAGE_BYTES_FIELD_NUMBER: builtins.int
    API_CALLS_FIELD_NUMBER: builtins.int
    PERIOD_START_FIELD_NUMBER: builtins.int
    PERIOD_END_FIELD_NUMBER: builtins.int
    tenant_id: builtins.str
    period_id: builtins.str
    """e.g., "2024-01" """
    strategies_created: builtins.int
    """Strategy usage"""
    active_strategies: builtins.int
    backtests_run: builtins.int
    """Backtest usage"""
    backtest_compute_minutes: builtins.int
    live_sessions: builtins.int
    """Trading usage"""
    orders_placed: builtins.int
    market_data_requests: builtins.int
    """Data usage"""
    storage_bytes: builtins.int
    api_calls: builtins.int
    """API usage"""
    @builtins.property
    def period_start(self) -> common_pb2.Timestamp: ...
    @builtins.property
    def period_end(self) -> common_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        tenant_id: builtins.str = ...,
        period_id: builtins.str = ...,
        strategies_created: builtins.int = ...,
        active_strategies: builtins.int = ...,
        backtests_run: builtins.int = ...,
        backtest_compute_minutes: builtins.int = ...,
        live_sessions: builtins.int = ...,
        orders_placed: builtins.int = ...,
        market_data_requests: builtins.int = ...,
        storage_bytes: builtins.int = ...,
        api_calls: builtins.int = ...,
        period_start: common_pb2.Timestamp | None = ...,
        period_end: common_pb2.Timestamp | None = ...,
    ) -> None: ...
    type _HasFieldArgType = typing.Literal["period_end", b"period_end", "period_start", b"period_start"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    type _ClearFieldArgType = typing.Literal["active_strategies", b"active_strategies", "api_calls", b"api_calls", "backtest_compute_minutes", b"backtest_compute_minutes", "backtests_run", b"backtests_run", "live_sessions", b"live_sessions", "market_data_requests", b"market_data_requests", "orders_placed", b"orders_placed", "period_end", b"period_end", "period_id", b"period_id", "period_start", b"period_start", "storage_bytes", b"storage_bytes", "strategies_created", b"strategies_created", "tenant_id", b"tenant_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class Invoice(message.Message):
    """Invoice"""

    DESCRIPTOR: descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    TENANT_ID_FIELD_NUMBER: builtins.int
    SUBSCRIPTION_ID_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    AMOUNT_PAID_FIELD_NUMBER: builtins.int
    AMOUNT_REMAINING_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    PERIOD_START_FIELD_NUMBER: builtins.int
    PERIOD_END_FIELD_NUMBER: builtins.int
    DUE_DATE_FIELD_NUMBER: builtins.int
    PAID_AT_FIELD_NUMBER: builtins.int
    PDF_URL_FIELD_NUMBER: builtins.int
    STRIPE_INVOICE_ID_FIELD_NUMBER: builtins.int
    ITEMS_FIELD_NUMBER: builtins.int
    id: builtins.str
    tenant_id: builtins.str
    subscription_id: builtins.str
    status: builtins.str
    """"draft", "open", "paid", "void", "uncollectible" """
    pdf_url: builtins.str
    stripe_invoice_id: builtins.str
    @builtins.property
    def amount(self) -> common_pb2.Money: ...
    @builtins.property
    def amount_paid(self) -> common_pb2.Money: ...
    @builtins.property
    def amount_remaining(self) -> common_pb2.Money: ...
    @builtins.property
    def period_start(self) -> common_pb2.Timestamp: ...
    @builtins.property
    def period_end(self) -> common_pb2.Timestamp: ...
    @builtins.property
    def due_date(self) -> common_pb2.Timestamp: ...
    @builtins.property
    def paid_at(self) -> common_pb2.Timestamp: ...
    @builtins.property
    def items(self) -> containers.RepeatedCompositeFieldContainer[InvoiceItem]: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        tenant_id: builtins.str = ...,
        subscription_id: builtins.str = ...,
        amount: common_pb2.Money | None = ...,
        amount_paid: common_pb2.Money | None = ...,
        amount_remaining: common_pb2.Money | None = ...,
        status: builtins.str = ...,
        period_start: common_pb2.Timestamp | None = ...,
        period_end: common_pb2.Timestamp | None = ...,
        due_date: common_pb2.Timestamp | None = ...,
        paid_at: common_pb2.Timestamp | None = ...,
        pdf_url: builtins.str = ...,
        stripe_invoice_id: builtins.str = ...,
        items: abc.Iterable[InvoiceItem] | None = ...,
    ) -> None: ...
    type _HasFieldArgType = typing.Literal["amount", b"amount", "amount_paid", b"amount_paid", "amount_remaining", b"amount_remaining", "due_date", b"due_date", "paid_at", b"paid_at", "period_end", b"period_end", "period_start", b"period_start"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    type _ClearFieldArgType = typing.Literal["amount", b"amount", "amount_paid", b"amount_paid", "amount_remaining", b"amount_remaining", "due_date", b"due_date", "id", b"id", "items", b"items", "paid_at", b"paid_at", "pdf_url", b"pdf_url", "period_end", b"period_end", "period_start", b"period_start", "status", b"status", "stripe_invoice_id", b"stripe_invoice_id", "subscription_id", b"subscription_id", "tenant_id", b"tenant_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class InvoiceItem(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    DESCRIPTION_FIELD_NUMBER: builtins.int
    QUANTITY_FIELD_NUMBER: builtins.int
    UNIT_PRICE_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    description: builtins.str
    quantity: builtins.int
    @builtins.property
    def unit_price(self) -> common_pb2.Money: ...
    @builtins.property
    def amount(self) -> common_pb2.Money: ...
    def __init__(
        self,
        *,
        description: builtins.str = ...,
        quantity: builtins.int = ...,
        unit_price: common_pb2.Money | None = ...,
        amount: common_pb2.Money | None = ...,
    ) -> None: ...
    type _HasFieldArgType = typing.Literal["amount", b"amount", "unit_price", b"unit_price"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    type _ClearFieldArgType = typing.Literal["amount", b"amount", "description", b"description", "quantity", b"quantity", "unit_price", b"unit_price"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class PaymentMethod(message.Message):
    """Payment method"""

    DESCRIPTOR: descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    IS_DEFAULT_FIELD_NUMBER: builtins.int
    CARD_BRAND_FIELD_NUMBER: builtins.int
    CARD_LAST4_FIELD_NUMBER: builtins.int
    CARD_EXP_MONTH_FIELD_NUMBER: builtins.int
    CARD_EXP_YEAR_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    id: builtins.str
    type: builtins.str
    """"card", "bank_account" """
    is_default: builtins.bool
    card_brand: builtins.str
    """Card details (if type == "card")"""
    card_last4: builtins.str
    card_exp_month: builtins.int
    card_exp_year: builtins.int
    @builtins.property
    def created_at(self) -> common_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        type: builtins.str = ...,
        is_default: builtins.bool = ...,
        card_brand: builtins.str = ...,
        card_last4: builtins.str = ...,
        card_exp_month: builtins.int = ...,
        card_exp_year: builtins.int = ...,
        created_at: common_pb2.Timestamp | None = ...,
    ) -> None: ...
    type _HasFieldArgType = typing.Literal["created_at", b"created_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    type _ClearFieldArgType = typing.Literal["card_brand", b"card_brand", "card_exp_month", b"card_exp_month", "card_exp_year", b"card_exp_year", "card_last4", b"card_last4", "created_at", b"created_at", "id", b"id", "is_default", b"is_default", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class GetSubscriptionRequest(message.Message):
    """=============================================================================
    REQUESTS & RESPONSES
    =============================================================================

    Get subscription
    """

    DESCRIPTOR: descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    @builtins.property
    def context(self) -> common_pb2.TenantContext: ...
    def __init__(
        self,
        *,
        context: common_pb2.TenantContext | None = ...,
    ) -> None: ...
    type _HasFieldArgType = typing.Literal["context", b"context"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    type _ClearFieldArgType = typing.Literal["context", b"context"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class GetSubscriptionResponse(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    SUBSCRIPTION_FIELD_NUMBER: builtins.int
    @builtins.property
    def subscription(self) -> Subscription: ...
    def __init__(
        self,
        *,
        subscription: Subscription | None = ...,
    ) -> None: ...
    type _HasFieldArgType = typing.Literal["subscription", b"subscription"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    type _ClearFieldArgType = typing.Literal["subscription", b"subscription"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class CreateSubscriptionRequest(message.Message):
    """Create subscription"""

    DESCRIPTOR: descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    PLAN_ID_FIELD_NUMBER: builtins.int
    INTERVAL_FIELD_NUMBER: builtins.int
    PAYMENT_METHOD_ID_FIELD_NUMBER: builtins.int
    PROMO_CODE_FIELD_NUMBER: builtins.int
    plan_id: builtins.str
    interval: BillingInterval.ValueType
    payment_method_id: builtins.str
    promo_code: builtins.str
    @builtins.property
    def context(self) -> common_pb2.TenantContext: ...
    def __init__(
        self,
        *,
        context: common_pb2.TenantContext | None = ...,
        plan_id: builtins.str = ...,
        interval: BillingInterval.ValueType = ...,
        payment_method_id: builtins.str = ...,
        promo_code: builtins.str = ...,
    ) -> None: ...
    type _HasFieldArgType = typing.Literal["context", b"context"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    type _ClearFieldArgType = typing.Literal["context", b"context", "interval", b"interval", "payment_method_id", b"payment_method_id", "plan_id", b"plan_id", "promo_code", b"promo_code"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class CreateSubscriptionResponse(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    SUBSCRIPTION_FIELD_NUMBER: builtins.int
    CHECKOUT_URL_FIELD_NUMBER: builtins.int
    checkout_url: builtins.str
    """If additional payment setup needed"""
    @builtins.property
    def subscription(self) -> Subscription: ...
    def __init__(
        self,
        *,
        subscription: Subscription | None = ...,
        checkout_url: builtins.str = ...,
    ) -> None: ...
    type _HasFieldArgType = typing.Literal["subscription", b"subscription"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    type _ClearFieldArgType = typing.Literal["checkout_url", b"checkout_url", "subscription", b"subscription"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class UpdateSubscriptionRequest(message.Message):
    """Update subscription (change plan)"""

    DESCRIPTOR: descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    PLAN_ID_FIELD_NUMBER: builtins.int
    INTERVAL_FIELD_NUMBER: builtins.int
    PRORATE_FIELD_NUMBER: builtins.int
    plan_id: builtins.str
    interval: BillingInterval.ValueType
    prorate: builtins.bool
    @builtins.property
    def context(self) -> common_pb2.TenantContext: ...
    def __init__(
        self,
        *,
        context: common_pb2.TenantContext | None = ...,
        plan_id: builtins.str = ...,
        interval: BillingInterval.ValueType = ...,
        prorate: builtins.bool = ...,
    ) -> None: ...
    type _HasFieldArgType = typing.Literal["context", b"context"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    type _ClearFieldArgType = typing.Literal["context", b"context", "interval", b"interval", "plan_id", b"plan_id", "prorate", b"prorate"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class UpdateSubscriptionResponse(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    SUBSCRIPTION_FIELD_NUMBER: builtins.int
    @builtins.property
    def subscription(self) -> Subscription: ...
    def __init__(
        self,
        *,
        subscription: Subscription | None = ...,
    ) -> None: ...
    type _HasFieldArgType = typing.Literal["subscription", b"subscription"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    type _ClearFieldArgType = typing.Literal["subscription", b"subscription"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class CancelSubscriptionRequest(message.Message):
    """Cancel subscription"""

    DESCRIPTOR: descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    CANCEL_IMMEDIATELY_FIELD_NUMBER: builtins.int
    REASON_FIELD_NUMBER: builtins.int
    cancel_immediately: builtins.bool
    """vs cancel at period end"""
    reason: builtins.str
    @builtins.property
    def context(self) -> common_pb2.TenantContext: ...
    def __init__(
        self,
        *,
        context: common_pb2.TenantContext | None = ...,
        cancel_immediately: builtins.bool = ...,
        reason: builtins.str = ...,
    ) -> None: ...
    type _HasFieldArgType = typing.Literal["context", b"context"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    type _ClearFieldArgType = typing.Literal["cancel_immediately", b"cancel_immediately", "context", b"context", "reason", b"reason"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class CancelSubscriptionResponse(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    SUBSCRIPTION_FIELD_NUMBER: builtins.int
    @builtins.property
    def subscription(self) -> Subscription: ...
    def __init__(
        self,
        *,
        subscription: Subscription | None = ...,
    ) -> None: ...
    type _HasFieldArgType = typing.Literal["subscription", b"subscription"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    type _ClearFieldArgType = typing.Literal["subscription", b"subscription"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class ResumeSubscriptionRequest(message.Message):
    """Resume subscription"""

    DESCRIPTOR: descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    @builtins.property
    def context(self) -> common_pb2.TenantContext: ...
    def __init__(
        self,
        *,
        context: common_pb2.TenantContext | None = ...,
    ) -> None: ...
    type _HasFieldArgType = typing.Literal["context", b"context"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    type _ClearFieldArgType = typing.Literal["context", b"context"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class ResumeSubscriptionResponse(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    SUBSCRIPTION_FIELD_NUMBER: builtins.int
    @builtins.property
    def subscription(self) -> Subscription: ...
    def __init__(
        self,
        *,
        subscription: Subscription | None = ...,
    ) -> None: ...
    type _HasFieldArgType = typing.Literal["subscription", b"subscription"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    type _ClearFieldArgType = typing.Literal["subscription", b"subscription"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class GetUsageRequest(message.Message):
    """Get usage"""

    DESCRIPTOR: descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    PERIOD_ID_FIELD_NUMBER: builtins.int
    period_id: builtins.str
    """Optional: defaults to current period"""
    @builtins.property
    def context(self) -> common_pb2.TenantContext: ...
    def __init__(
        self,
        *,
        context: common_pb2.TenantContext | None = ...,
        period_id: builtins.str = ...,
    ) -> None: ...
    type _HasFieldArgType = typing.Literal["context", b"context"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    type _ClearFieldArgType = typing.Literal["context", b"context", "period_id", b"period_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class GetUsageResponse(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    USAGE_FIELD_NUMBER: builtins.int
    LIMIT_FIELD_NUMBER: builtins.int
    @builtins.property
    def usage(self) -> Usage: ...
    @builtins.property
    def limit(self) -> Usage:
        """Plan limits for comparison"""

    def __init__(
        self,
        *,
        usage: Usage | None = ...,
        limit: Usage | None = ...,
    ) -> None: ...
    type _HasFieldArgType = typing.Literal["limit", b"limit", "usage", b"usage"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    type _ClearFieldArgType = typing.Literal["limit", b"limit", "usage", b"usage"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class ListInvoicesRequest(message.Message):
    """List invoices"""

    DESCRIPTOR: descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    PAGINATION_FIELD_NUMBER: builtins.int
    @builtins.property
    def context(self) -> common_pb2.TenantContext: ...
    @builtins.property
    def pagination(self) -> common_pb2.PaginationRequest: ...
    def __init__(
        self,
        *,
        context: common_pb2.TenantContext | None = ...,
        pagination: common_pb2.PaginationRequest | None = ...,
    ) -> None: ...
    type _HasFieldArgType = typing.Literal["context", b"context", "pagination", b"pagination"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    type _ClearFieldArgType = typing.Literal["context", b"context", "pagination", b"pagination"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class ListInvoicesResponse(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    INVOICES_FIELD_NUMBER: builtins.int
    PAGINATION_FIELD_NUMBER: builtins.int
    @builtins.property
    def invoices(self) -> containers.RepeatedCompositeFieldContainer[Invoice]: ...
    @builtins.property
    def pagination(self) -> common_pb2.PaginationResponse: ...
    def __init__(
        self,
        *,
        invoices: abc.Iterable[Invoice] | None = ...,
        pagination: common_pb2.PaginationResponse | None = ...,
    ) -> None: ...
    type _HasFieldArgType = typing.Literal["pagination", b"pagination"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    type _ClearFieldArgType = typing.Literal["invoices", b"invoices", "pagination", b"pagination"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class GetInvoiceRequest(message.Message):
    """Get invoice"""

    DESCRIPTOR: descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    INVOICE_ID_FIELD_NUMBER: builtins.int
    invoice_id: builtins.str
    @builtins.property
    def context(self) -> common_pb2.TenantContext: ...
    def __init__(
        self,
        *,
        context: common_pb2.TenantContext | None = ...,
        invoice_id: builtins.str = ...,
    ) -> None: ...
    type _HasFieldArgType = typing.Literal["context", b"context"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    type _ClearFieldArgType = typing.Literal["context", b"context", "invoice_id", b"invoice_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class GetInvoiceResponse(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    INVOICE_FIELD_NUMBER: builtins.int
    @builtins.property
    def invoice(self) -> Invoice: ...
    def __init__(
        self,
        *,
        invoice: Invoice | None = ...,
    ) -> None: ...
    type _HasFieldArgType = typing.Literal["invoice", b"invoice"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    type _ClearFieldArgType = typing.Literal["invoice", b"invoice"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class ListPlansRequest(message.Message):
    """List plans"""

    DESCRIPTOR: descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    @builtins.property
    def context(self) -> common_pb2.TenantContext: ...
    def __init__(
        self,
        *,
        context: common_pb2.TenantContext | None = ...,
    ) -> None: ...
    type _HasFieldArgType = typing.Literal["context", b"context"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    type _ClearFieldArgType = typing.Literal["context", b"context"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class ListPlansResponse(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    PLANS_FIELD_NUMBER: builtins.int
    @builtins.property
    def plans(self) -> containers.RepeatedCompositeFieldContainer[Plan]: ...
    def __init__(
        self,
        *,
        plans: abc.Iterable[Plan] | None = ...,
    ) -> None: ...
    type _ClearFieldArgType = typing.Literal["plans", b"plans"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class ListPaymentMethodsRequest(message.Message):
    """List payment methods"""

    DESCRIPTOR: descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    @builtins.property
    def context(self) -> common_pb2.TenantContext: ...
    def __init__(
        self,
        *,
        context: common_pb2.TenantContext | None = ...,
    ) -> None: ...
    type _HasFieldArgType = typing.Literal["context", b"context"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    type _ClearFieldArgType = typing.Literal["context", b"context"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class ListPaymentMethodsResponse(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    PAYMENT_METHODS_FIELD_NUMBER: builtins.int
    @builtins.property
    def payment_methods(self) -> containers.RepeatedCompositeFieldContainer[PaymentMethod]: ...
    def __init__(
        self,
        *,
        payment_methods: abc.Iterable[PaymentMethod] | None = ...,
    ) -> None: ...
    type _ClearFieldArgType = typing.Literal["payment_methods", b"payment_methods"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class AddPaymentMethodRequest(message.Message):
    """Add payment method"""

    DESCRIPTOR: descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    SETUP_INTENT_ID_FIELD_NUMBER: builtins.int
    SET_AS_DEFAULT_FIELD_NUMBER: builtins.int
    setup_intent_id: builtins.str
    """From Stripe.js"""
    set_as_default: builtins.bool
    @builtins.property
    def context(self) -> common_pb2.TenantContext: ...
    def __init__(
        self,
        *,
        context: common_pb2.TenantContext | None = ...,
        setup_intent_id: builtins.str = ...,
        set_as_default: builtins.bool = ...,
    ) -> None: ...
    type _HasFieldArgType = typing.Literal["context", b"context"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    type _ClearFieldArgType = typing.Literal["context", b"context", "set_as_default", b"set_as_default", "setup_intent_id", b"setup_intent_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class AddPaymentMethodResponse(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    PAYMENT_METHOD_FIELD_NUMBER: builtins.int
    @builtins.property
    def payment_method(self) -> PaymentMethod: ...
    def __init__(
        self,
        *,
        payment_method: PaymentMethod | None = ...,
    ) -> None: ...
    type _HasFieldArgType = typing.Literal["payment_method", b"payment_method"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    type _ClearFieldArgType = typing.Literal["payment_method", b"payment_method"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class RemovePaymentMethodRequest(message.Message):
    """Remove payment method"""

    DESCRIPTOR: descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    PAYMENT_METHOD_ID_FIELD_NUMBER: builtins.int
    payment_method_id: builtins.str
    @builtins.property
    def context(self) -> common_pb2.TenantContext: ...
    def __init__(
        self,
        *,
        context: common_pb2.TenantContext | None = ...,
        payment_method_id: builtins.str = ...,
    ) -> None: ...
    type _HasFieldArgType = typing.Literal["context", b"context"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    type _ClearFieldArgType = typing.Literal["context", b"context", "payment_method_id", b"payment_method_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class RemovePaymentMethodResponse(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    success: builtins.bool
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
    ) -> None: ...
    type _ClearFieldArgType = typing.Literal["success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class CreateCheckoutSessionRequest(message.Message):
    """Create checkout session (for initial subscription)"""

    DESCRIPTOR: descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    PLAN_ID_FIELD_NUMBER: builtins.int
    INTERVAL_FIELD_NUMBER: builtins.int
    SUCCESS_URL_FIELD_NUMBER: builtins.int
    CANCEL_URL_FIELD_NUMBER: builtins.int
    plan_id: builtins.str
    interval: BillingInterval.ValueType
    success_url: builtins.str
    cancel_url: builtins.str
    @builtins.property
    def context(self) -> common_pb2.TenantContext: ...
    def __init__(
        self,
        *,
        context: common_pb2.TenantContext | None = ...,
        plan_id: builtins.str = ...,
        interval: BillingInterval.ValueType = ...,
        success_url: builtins.str = ...,
        cancel_url: builtins.str = ...,
    ) -> None: ...
    type _HasFieldArgType = typing.Literal["context", b"context"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    type _ClearFieldArgType = typing.Literal["cancel_url", b"cancel_url", "context", b"context", "interval", b"interval", "plan_id", b"plan_id", "success_url", b"success_url"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class CreateCheckoutSessionResponse(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    CHECKOUT_URL_FIELD_NUMBER: builtins.int
    SESSION_ID_FIELD_NUMBER: builtins.int
    checkout_url: builtins.str
    session_id: builtins.str
    def __init__(
        self,
        *,
        checkout_url: builtins.str = ...,
        session_id: builtins.str = ...,
    ) -> None: ...
    type _ClearFieldArgType = typing.Literal["checkout_url", b"checkout_url", "session_id", b"session_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class CreatePortalSessionRequest(message.Message):
    """Create portal session (for managing subscription)"""

    DESCRIPTOR: descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    RETURN_URL_FIELD_NUMBER: builtins.int
    return_url: builtins.str
    @builtins.property
    def context(self) -> common_pb2.TenantContext: ...
    def __init__(
        self,
        *,
        context: common_pb2.TenantContext | None = ...,
        return_url: builtins.str = ...,
    ) -> None: ...
    type _HasFieldArgType = typing.Literal["context", b"context"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    type _ClearFieldArgType = typing.Literal["context", b"context", "return_url", b"return_url"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class CreatePortalSessionResponse(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    PORTAL_URL_FIELD_NUMBER: builtins.int
    portal_url: builtins.str
    def __init__(
        self,
        *,
        portal_url: builtins.str = ...,
    ) -> None: ...
    type _ClearFieldArgType = typing.Literal["portal_url", b"portal_url"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
