"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as abc
from google.protobuf import descriptor as descriptor
from google.protobuf import message as message
from google.protobuf.internal import containers as containers
from google.protobuf.internal import enum_type_wrapper as enum_type_wrapper
from llamatrade.v1 import common_pb2 as common_pb2
import builtins as builtins
import sys
import typing as typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: descriptor.FileDescriptor

class _Timeframe:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _TimeframeEnumTypeWrapper(enum_type_wrapper._EnumTypeWrapper[_Timeframe.ValueType], builtins.type):
    DESCRIPTOR: descriptor.EnumDescriptor
    TIMEFRAME_UNSPECIFIED: _Timeframe.ValueType  # 0
    TIMEFRAME_1MIN: _Timeframe.ValueType  # 1
    TIMEFRAME_5MIN: _Timeframe.ValueType  # 2
    TIMEFRAME_15MIN: _Timeframe.ValueType  # 3
    TIMEFRAME_30MIN: _Timeframe.ValueType  # 4
    TIMEFRAME_1HOUR: _Timeframe.ValueType  # 5
    TIMEFRAME_4HOUR: _Timeframe.ValueType  # 6
    TIMEFRAME_1DAY: _Timeframe.ValueType  # 7
    TIMEFRAME_1WEEK: _Timeframe.ValueType  # 8
    TIMEFRAME_1MONTH: _Timeframe.ValueType  # 9

class Timeframe(_Timeframe, metaclass=_TimeframeEnumTypeWrapper):
    """=============================================================================
    ENUMS
    =============================================================================

    Timeframe for bar data
    """

TIMEFRAME_UNSPECIFIED: Timeframe.ValueType  # 0
TIMEFRAME_1MIN: Timeframe.ValueType  # 1
TIMEFRAME_5MIN: Timeframe.ValueType  # 2
TIMEFRAME_15MIN: Timeframe.ValueType  # 3
TIMEFRAME_30MIN: Timeframe.ValueType  # 4
TIMEFRAME_1HOUR: Timeframe.ValueType  # 5
TIMEFRAME_4HOUR: Timeframe.ValueType  # 6
TIMEFRAME_1DAY: Timeframe.ValueType  # 7
TIMEFRAME_1WEEK: Timeframe.ValueType  # 8
TIMEFRAME_1MONTH: Timeframe.ValueType  # 9

class _MarketStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _MarketStatusEnumTypeWrapper(enum_type_wrapper._EnumTypeWrapper[_MarketStatus.ValueType], builtins.type):
    DESCRIPTOR: descriptor.EnumDescriptor
    MARKET_STATUS_UNSPECIFIED: _MarketStatus.ValueType  # 0
    MARKET_STATUS_OPEN: _MarketStatus.ValueType  # 1
    MARKET_STATUS_CLOSED: _MarketStatus.ValueType  # 2
    MARKET_STATUS_PRE_MARKET: _MarketStatus.ValueType  # 3
    MARKET_STATUS_AFTER_HOURS: _MarketStatus.ValueType  # 4

class MarketStatus(_MarketStatus, metaclass=_MarketStatusEnumTypeWrapper):
    """Market status"""

MARKET_STATUS_UNSPECIFIED: MarketStatus.ValueType  # 0
MARKET_STATUS_OPEN: MarketStatus.ValueType  # 1
MARKET_STATUS_CLOSED: MarketStatus.ValueType  # 2
MARKET_STATUS_PRE_MARKET: MarketStatus.ValueType  # 3
MARKET_STATUS_AFTER_HOURS: MarketStatus.ValueType  # 4

@typing.final
class Bar(message.Message):
    """=============================================================================
    MESSAGES
    =============================================================================

    OHLCV bar data
    """

    DESCRIPTOR: descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    OPEN_FIELD_NUMBER: builtins.int
    HIGH_FIELD_NUMBER: builtins.int
    LOW_FIELD_NUMBER: builtins.int
    CLOSE_FIELD_NUMBER: builtins.int
    VOLUME_FIELD_NUMBER: builtins.int
    TRADE_COUNT_FIELD_NUMBER: builtins.int
    VWAP_FIELD_NUMBER: builtins.int
    symbol: builtins.str
    volume: builtins.int
    trade_count: builtins.int
    @builtins.property
    def timestamp(self) -> common_pb2.Timestamp: ...
    @builtins.property
    def open(self) -> common_pb2.Decimal: ...
    @builtins.property
    def high(self) -> common_pb2.Decimal: ...
    @builtins.property
    def low(self) -> common_pb2.Decimal: ...
    @builtins.property
    def close(self) -> common_pb2.Decimal: ...
    @builtins.property
    def vwap(self) -> common_pb2.Decimal:
        """Volume-weighted average price"""

    def __init__(
        self,
        *,
        symbol: builtins.str = ...,
        timestamp: common_pb2.Timestamp | None = ...,
        open: common_pb2.Decimal | None = ...,
        high: common_pb2.Decimal | None = ...,
        low: common_pb2.Decimal | None = ...,
        close: common_pb2.Decimal | None = ...,
        volume: builtins.int = ...,
        trade_count: builtins.int = ...,
        vwap: common_pb2.Decimal | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = typing.Literal["close", b"close", "high", b"high", "low", b"low", "open", b"open", "timestamp", b"timestamp", "vwap", b"vwap"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["close", b"close", "high", b"high", "low", b"low", "open", b"open", "symbol", b"symbol", "timestamp", b"timestamp", "trade_count", b"trade_count", "volume", b"volume", "vwap", b"vwap"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class Quote(message.Message):
    """Real-time quote (bid/ask)"""

    DESCRIPTOR: descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    BID_PRICE_FIELD_NUMBER: builtins.int
    BID_SIZE_FIELD_NUMBER: builtins.int
    ASK_PRICE_FIELD_NUMBER: builtins.int
    ASK_SIZE_FIELD_NUMBER: builtins.int
    BID_EXCHANGE_FIELD_NUMBER: builtins.int
    ASK_EXCHANGE_FIELD_NUMBER: builtins.int
    symbol: builtins.str
    bid_size: builtins.int
    ask_size: builtins.int
    bid_exchange: builtins.str
    ask_exchange: builtins.str
    @builtins.property
    def timestamp(self) -> common_pb2.Timestamp: ...
    @builtins.property
    def bid_price(self) -> common_pb2.Decimal: ...
    @builtins.property
    def ask_price(self) -> common_pb2.Decimal: ...
    def __init__(
        self,
        *,
        symbol: builtins.str = ...,
        timestamp: common_pb2.Timestamp | None = ...,
        bid_price: common_pb2.Decimal | None = ...,
        bid_size: builtins.int = ...,
        ask_price: common_pb2.Decimal | None = ...,
        ask_size: builtins.int = ...,
        bid_exchange: builtins.str = ...,
        ask_exchange: builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = typing.Literal["ask_price", b"ask_price", "bid_price", b"bid_price", "timestamp", b"timestamp"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["ask_exchange", b"ask_exchange", "ask_price", b"ask_price", "ask_size", b"ask_size", "bid_exchange", b"bid_exchange", "bid_price", b"bid_price", "bid_size", b"bid_size", "symbol", b"symbol", "timestamp", b"timestamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class Trade(message.Message):
    """Trade tick data"""

    DESCRIPTOR: descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    PRICE_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    EXCHANGE_FIELD_NUMBER: builtins.int
    TRADE_ID_FIELD_NUMBER: builtins.int
    CONDITIONS_FIELD_NUMBER: builtins.int
    symbol: builtins.str
    size: builtins.int
    exchange: builtins.str
    trade_id: builtins.str
    @builtins.property
    def timestamp(self) -> common_pb2.Timestamp: ...
    @builtins.property
    def price(self) -> common_pb2.Decimal: ...
    @builtins.property
    def conditions(self) -> containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        symbol: builtins.str = ...,
        timestamp: common_pb2.Timestamp | None = ...,
        price: common_pb2.Decimal | None = ...,
        size: builtins.int = ...,
        exchange: builtins.str = ...,
        trade_id: builtins.str = ...,
        conditions: abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = typing.Literal["price", b"price", "timestamp", b"timestamp"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["conditions", b"conditions", "exchange", b"exchange", "price", b"price", "size", b"size", "symbol", b"symbol", "timestamp", b"timestamp", "trade_id", b"trade_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class Snapshot(message.Message):
    """Snapshot of current market data"""

    DESCRIPTOR: descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: builtins.int
    LATEST_BAR_FIELD_NUMBER: builtins.int
    LATEST_QUOTE_FIELD_NUMBER: builtins.int
    LATEST_TRADE_FIELD_NUMBER: builtins.int
    DAILY_BAR_FIELD_NUMBER: builtins.int
    PREVIOUS_DAILY_BAR_FIELD_NUMBER: builtins.int
    CHANGE_FIELD_NUMBER: builtins.int
    CHANGE_PERCENT_FIELD_NUMBER: builtins.int
    symbol: builtins.str
    @builtins.property
    def latest_bar(self) -> Bar: ...
    @builtins.property
    def latest_quote(self) -> Quote: ...
    @builtins.property
    def latest_trade(self) -> Trade: ...
    @builtins.property
    def daily_bar(self) -> Bar: ...
    @builtins.property
    def previous_daily_bar(self) -> Bar: ...
    @builtins.property
    def change(self) -> common_pb2.Decimal: ...
    @builtins.property
    def change_percent(self) -> common_pb2.Decimal: ...
    def __init__(
        self,
        *,
        symbol: builtins.str = ...,
        latest_bar: Bar | None = ...,
        latest_quote: Quote | None = ...,
        latest_trade: Trade | None = ...,
        daily_bar: Bar | None = ...,
        previous_daily_bar: Bar | None = ...,
        change: common_pb2.Decimal | None = ...,
        change_percent: common_pb2.Decimal | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = typing.Literal["change", b"change", "change_percent", b"change_percent", "daily_bar", b"daily_bar", "latest_bar", b"latest_bar", "latest_quote", b"latest_quote", "latest_trade", b"latest_trade", "previous_daily_bar", b"previous_daily_bar"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["change", b"change", "change_percent", b"change_percent", "daily_bar", b"daily_bar", "latest_bar", b"latest_bar", "latest_quote", b"latest_quote", "latest_trade", b"latest_trade", "previous_daily_bar", b"previous_daily_bar", "symbol", b"symbol"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class StreamBarsRequest(message.Message):
    """=============================================================================
    REQUESTS & RESPONSES
    =============================================================================

    Stream bars request
    """

    DESCRIPTOR: descriptor.Descriptor

    SYMBOLS_FIELD_NUMBER: builtins.int
    TIMEFRAME_FIELD_NUMBER: builtins.int
    timeframe: Timeframe.ValueType
    @builtins.property
    def symbols(self) -> containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        symbols: abc.Iterable[builtins.str] | None = ...,
        timeframe: Timeframe.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["symbols", b"symbols", "timeframe", b"timeframe"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class GetHistoricalBarsRequest(message.Message):
    """Get historical bars request"""

    DESCRIPTOR: descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: builtins.int
    START_FIELD_NUMBER: builtins.int
    END_FIELD_NUMBER: builtins.int
    TIMEFRAME_FIELD_NUMBER: builtins.int
    PAGINATION_FIELD_NUMBER: builtins.int
    ADJUST_FOR_SPLITS_FIELD_NUMBER: builtins.int
    symbol: builtins.str
    timeframe: Timeframe.ValueType
    adjust_for_splits: builtins.bool
    @builtins.property
    def start(self) -> common_pb2.Timestamp: ...
    @builtins.property
    def end(self) -> common_pb2.Timestamp: ...
    @builtins.property
    def pagination(self) -> common_pb2.PaginationRequest: ...
    def __init__(
        self,
        *,
        symbol: builtins.str = ...,
        start: common_pb2.Timestamp | None = ...,
        end: common_pb2.Timestamp | None = ...,
        timeframe: Timeframe.ValueType = ...,
        pagination: common_pb2.PaginationRequest | None = ...,
        adjust_for_splits: builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = typing.Literal["end", b"end", "pagination", b"pagination", "start", b"start"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["adjust_for_splits", b"adjust_for_splits", "end", b"end", "pagination", b"pagination", "start", b"start", "symbol", b"symbol", "timeframe", b"timeframe"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class GetHistoricalBarsResponse(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    BARS_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    PAGINATION_FIELD_NUMBER: builtins.int
    next_page_token: builtins.str
    @builtins.property
    def bars(self) -> containers.RepeatedCompositeFieldContainer[Bar]: ...
    @builtins.property
    def pagination(self) -> common_pb2.PaginationResponse: ...
    def __init__(
        self,
        *,
        bars: abc.Iterable[Bar] | None = ...,
        next_page_token: builtins.str = ...,
        pagination: common_pb2.PaginationResponse | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = typing.Literal["pagination", b"pagination"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["bars", b"bars", "next_page_token", b"next_page_token", "pagination", b"pagination"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class GetMultiBarsRequest(message.Message):
    """Get multiple symbols bars"""

    DESCRIPTOR: descriptor.Descriptor

    SYMBOLS_FIELD_NUMBER: builtins.int
    START_FIELD_NUMBER: builtins.int
    END_FIELD_NUMBER: builtins.int
    TIMEFRAME_FIELD_NUMBER: builtins.int
    LIMIT_FIELD_NUMBER: builtins.int
    timeframe: Timeframe.ValueType
    limit: builtins.int
    @builtins.property
    def symbols(self) -> containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @builtins.property
    def start(self) -> common_pb2.Timestamp: ...
    @builtins.property
    def end(self) -> common_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        symbols: abc.Iterable[builtins.str] | None = ...,
        start: common_pb2.Timestamp | None = ...,
        end: common_pb2.Timestamp | None = ...,
        timeframe: Timeframe.ValueType = ...,
        limit: builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = typing.Literal["end", b"end", "start", b"start"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["end", b"end", "limit", b"limit", "start", b"start", "symbols", b"symbols", "timeframe", b"timeframe"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class GetMultiBarsResponse(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    @typing.final
    class BarsEntry(message.Message):
        DESCRIPTOR: descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @builtins.property
        def value(self) -> BarList: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: BarList | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    BARS_FIELD_NUMBER: builtins.int
    @builtins.property
    def bars(self) -> containers.MessageMap[builtins.str, BarList]: ...
    def __init__(
        self,
        *,
        bars: abc.Mapping[builtins.str, BarList] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["bars", b"bars"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class BarList(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    BARS_FIELD_NUMBER: builtins.int
    @builtins.property
    def bars(self) -> containers.RepeatedCompositeFieldContainer[Bar]: ...
    def __init__(
        self,
        *,
        bars: abc.Iterable[Bar] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["bars", b"bars"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class StreamQuotesRequest(message.Message):
    """Stream quotes request"""

    DESCRIPTOR: descriptor.Descriptor

    SYMBOLS_FIELD_NUMBER: builtins.int
    @builtins.property
    def symbols(self) -> containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        symbols: abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["symbols", b"symbols"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class StreamTradesRequest(message.Message):
    """Stream trades request"""

    DESCRIPTOR: descriptor.Descriptor

    SYMBOLS_FIELD_NUMBER: builtins.int
    @builtins.property
    def symbols(self) -> containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        symbols: abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["symbols", b"symbols"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class GetSnapshotRequest(message.Message):
    """Get snapshot request"""

    DESCRIPTOR: descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: builtins.int
    symbol: builtins.str
    def __init__(
        self,
        *,
        symbol: builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["symbol", b"symbol"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class GetSnapshotsRequest(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    SYMBOLS_FIELD_NUMBER: builtins.int
    @builtins.property
    def symbols(self) -> containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        symbols: abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["symbols", b"symbols"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class GetSnapshotsResponse(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    @typing.final
    class SnapshotsEntry(message.Message):
        DESCRIPTOR: descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @builtins.property
        def value(self) -> Snapshot: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: Snapshot | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    SNAPSHOTS_FIELD_NUMBER: builtins.int
    @builtins.property
    def snapshots(self) -> containers.MessageMap[builtins.str, Snapshot]: ...
    def __init__(
        self,
        *,
        snapshots: abc.Mapping[builtins.str, Snapshot] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["snapshots", b"snapshots"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class GetMarketStatusRequest(message.Message):
    """Get market status"""

    DESCRIPTOR: descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

@typing.final
class GetMarketStatusResponse(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    NEXT_OPEN_FIELD_NUMBER: builtins.int
    NEXT_CLOSE_FIELD_NUMBER: builtins.int
    status: MarketStatus.ValueType
    @builtins.property
    def next_open(self) -> common_pb2.Timestamp: ...
    @builtins.property
    def next_close(self) -> common_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        status: MarketStatus.ValueType = ...,
        next_open: common_pb2.Timestamp | None = ...,
        next_close: common_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = typing.Literal["next_close", b"next_close", "next_open", b"next_open"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["next_close", b"next_close", "next_open", b"next_open", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
