"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc as _abc_1
import sys
import typing as _typing
from collections import abc as _abc

import grpc as _grpc
from grpc import aio as _aio

from llamatrade.v1 import market_data_pb2 as _market_data_pb2

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class MarketDataServiceStub:
    """=============================================================================
    SERVICE
    =============================================================================
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> MarketDataServiceAsyncStub: ...
    StreamBars: _grpc.UnaryStreamMultiCallable[_market_data_pb2.StreamBarsRequest, _market_data_pb2.Bar]
    """Streaming endpoints"""
    StreamQuotes: _grpc.UnaryStreamMultiCallable[_market_data_pb2.StreamQuotesRequest, _market_data_pb2.Quote]
    StreamTrades: _grpc.UnaryStreamMultiCallable[_market_data_pb2.StreamTradesRequest, _market_data_pb2.Trade]
    GetHistoricalBars: _grpc.UnaryUnaryMultiCallable[_market_data_pb2.GetHistoricalBarsRequest, _market_data_pb2.GetHistoricalBarsResponse]
    """Historical data"""
    GetMultiBars: _grpc.UnaryUnaryMultiCallable[_market_data_pb2.GetMultiBarsRequest, _market_data_pb2.GetMultiBarsResponse]
    GetSnapshot: _grpc.UnaryUnaryMultiCallable[_market_data_pb2.GetSnapshotRequest, _market_data_pb2.Snapshot]
    """Snapshots"""
    GetSnapshots: _grpc.UnaryUnaryMultiCallable[_market_data_pb2.GetSnapshotsRequest, _market_data_pb2.GetSnapshotsResponse]
    GetMarketStatus: _grpc.UnaryUnaryMultiCallable[_market_data_pb2.GetMarketStatusRequest, _market_data_pb2.GetMarketStatusResponse]
    """Market info"""

@_typing.type_check_only
class MarketDataServiceAsyncStub(MarketDataServiceStub):
    """=============================================================================
    SERVICE
    =============================================================================
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    StreamBars: _aio.UnaryStreamMultiCallable[_market_data_pb2.StreamBarsRequest, _market_data_pb2.Bar]  # type: ignore[assignment]
    """Streaming endpoints"""
    StreamQuotes: _aio.UnaryStreamMultiCallable[_market_data_pb2.StreamQuotesRequest, _market_data_pb2.Quote]  # type: ignore[assignment]
    StreamTrades: _aio.UnaryStreamMultiCallable[_market_data_pb2.StreamTradesRequest, _market_data_pb2.Trade]  # type: ignore[assignment]
    GetHistoricalBars: _aio.UnaryUnaryMultiCallable[_market_data_pb2.GetHistoricalBarsRequest, _market_data_pb2.GetHistoricalBarsResponse]  # type: ignore[assignment]
    """Historical data"""
    GetMultiBars: _aio.UnaryUnaryMultiCallable[_market_data_pb2.GetMultiBarsRequest, _market_data_pb2.GetMultiBarsResponse]  # type: ignore[assignment]
    GetSnapshot: _aio.UnaryUnaryMultiCallable[_market_data_pb2.GetSnapshotRequest, _market_data_pb2.Snapshot]  # type: ignore[assignment]
    """Snapshots"""
    GetSnapshots: _aio.UnaryUnaryMultiCallable[_market_data_pb2.GetSnapshotsRequest, _market_data_pb2.GetSnapshotsResponse]  # type: ignore[assignment]
    GetMarketStatus: _aio.UnaryUnaryMultiCallable[_market_data_pb2.GetMarketStatusRequest, _market_data_pb2.GetMarketStatusResponse]  # type: ignore[assignment]
    """Market info"""

class MarketDataServiceServicer(metaclass=_abc_1.ABCMeta):
    """=============================================================================
    SERVICE
    =============================================================================
    """

    @_abc_1.abstractmethod
    def StreamBars(
        self,
        request: _market_data_pb2.StreamBarsRequest,
        context: _ServicerContext,
    ) -> _abc.Iterator[_market_data_pb2.Bar] | _abc.AsyncIterator[_market_data_pb2.Bar]:
        """Streaming endpoints"""

    @_abc_1.abstractmethod
    def StreamQuotes(
        self,
        request: _market_data_pb2.StreamQuotesRequest,
        context: _ServicerContext,
    ) -> _abc.Iterator[_market_data_pb2.Quote] | _abc.AsyncIterator[_market_data_pb2.Quote]: ...

    @_abc_1.abstractmethod
    def StreamTrades(
        self,
        request: _market_data_pb2.StreamTradesRequest,
        context: _ServicerContext,
    ) -> _abc.Iterator[_market_data_pb2.Trade] | _abc.AsyncIterator[_market_data_pb2.Trade]: ...

    @_abc_1.abstractmethod
    def GetHistoricalBars(
        self,
        request: _market_data_pb2.GetHistoricalBarsRequest,
        context: _ServicerContext,
    ) -> _market_data_pb2.GetHistoricalBarsResponse | _abc.Awaitable[_market_data_pb2.GetHistoricalBarsResponse]:
        """Historical data"""

    @_abc_1.abstractmethod
    def GetMultiBars(
        self,
        request: _market_data_pb2.GetMultiBarsRequest,
        context: _ServicerContext,
    ) -> _market_data_pb2.GetMultiBarsResponse | _abc.Awaitable[_market_data_pb2.GetMultiBarsResponse]: ...

    @_abc_1.abstractmethod
    def GetSnapshot(
        self,
        request: _market_data_pb2.GetSnapshotRequest,
        context: _ServicerContext,
    ) -> _market_data_pb2.Snapshot | _abc.Awaitable[_market_data_pb2.Snapshot]:
        """Snapshots"""

    @_abc_1.abstractmethod
    def GetSnapshots(
        self,
        request: _market_data_pb2.GetSnapshotsRequest,
        context: _ServicerContext,
    ) -> _market_data_pb2.GetSnapshotsResponse | _abc.Awaitable[_market_data_pb2.GetSnapshotsResponse]: ...

    @_abc_1.abstractmethod
    def GetMarketStatus(
        self,
        request: _market_data_pb2.GetMarketStatusRequest,
        context: _ServicerContext,
    ) -> _market_data_pb2.GetMarketStatusResponse | _abc.Awaitable[_market_data_pb2.GetMarketStatusResponse]:
        """Market info"""

def add_MarketDataServiceServicer_to_server(servicer: MarketDataServiceServicer, server: _grpc.Server | _aio.Server) -> None: ...
