# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from llamatrade.v1 import portfolio_pb2 as llamatrade_dot_v1_dot_portfolio__pb2


class PortfolioServiceStub:
    """=============================================================================
    SERVICE
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPortfolio = channel.unary_unary(
                '/llamatrade.v1.PortfolioService/GetPortfolio',
                request_serializer=llamatrade_dot_v1_dot_portfolio__pb2.GetPortfolioRequest.SerializeToString,
                response_deserializer=llamatrade_dot_v1_dot_portfolio__pb2.GetPortfolioResponse.FromString,
                _registered_method=True)
        self.ListPortfolios = channel.unary_unary(
                '/llamatrade.v1.PortfolioService/ListPortfolios',
                request_serializer=llamatrade_dot_v1_dot_portfolio__pb2.ListPortfoliosRequest.SerializeToString,
                response_deserializer=llamatrade_dot_v1_dot_portfolio__pb2.ListPortfoliosResponse.FromString,
                _registered_method=True)
        self.GetPerformance = channel.unary_unary(
                '/llamatrade.v1.PortfolioService/GetPerformance',
                request_serializer=llamatrade_dot_v1_dot_portfolio__pb2.GetPerformanceRequest.SerializeToString,
                response_deserializer=llamatrade_dot_v1_dot_portfolio__pb2.GetPerformanceResponse.FromString,
                _registered_method=True)
        self.GetAssetAllocation = channel.unary_unary(
                '/llamatrade.v1.PortfolioService/GetAssetAllocation',
                request_serializer=llamatrade_dot_v1_dot_portfolio__pb2.GetAssetAllocationRequest.SerializeToString,
                response_deserializer=llamatrade_dot_v1_dot_portfolio__pb2.GetAssetAllocationResponse.FromString,
                _registered_method=True)
        self.GetPositions = channel.unary_unary(
                '/llamatrade.v1.PortfolioService/GetPositions',
                request_serializer=llamatrade_dot_v1_dot_portfolio__pb2.GetPositionsRequest.SerializeToString,
                response_deserializer=llamatrade_dot_v1_dot_portfolio__pb2.GetPositionsResponse.FromString,
                _registered_method=True)
        self.ListTransactions = channel.unary_unary(
                '/llamatrade.v1.PortfolioService/ListTransactions',
                request_serializer=llamatrade_dot_v1_dot_portfolio__pb2.ListTransactionsRequest.SerializeToString,
                response_deserializer=llamatrade_dot_v1_dot_portfolio__pb2.ListTransactionsResponse.FromString,
                _registered_method=True)
        self.RecordTransaction = channel.unary_unary(
                '/llamatrade.v1.PortfolioService/RecordTransaction',
                request_serializer=llamatrade_dot_v1_dot_portfolio__pb2.RecordTransactionRequest.SerializeToString,
                response_deserializer=llamatrade_dot_v1_dot_portfolio__pb2.RecordTransactionResponse.FromString,
                _registered_method=True)
        self.SyncPortfolio = channel.unary_unary(
                '/llamatrade.v1.PortfolioService/SyncPortfolio',
                request_serializer=llamatrade_dot_v1_dot_portfolio__pb2.SyncPortfolioRequest.SerializeToString,
                response_deserializer=llamatrade_dot_v1_dot_portfolio__pb2.SyncPortfolioResponse.FromString,
                _registered_method=True)


class PortfolioServiceServicer:
    """=============================================================================
    SERVICE
    =============================================================================

    """

    def GetPortfolio(self, request, context):
        """Portfolio management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPortfolios(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPerformance(self, request, context):
        """Performance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAssetAllocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPositions(self, request, context):
        """Positions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTransactions(self, request, context):
        """Transactions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncPortfolio(self, request, context):
        """Sync with trading
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PortfolioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPortfolio': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPortfolio,
                    request_deserializer=llamatrade_dot_v1_dot_portfolio__pb2.GetPortfolioRequest.FromString,
                    response_serializer=llamatrade_dot_v1_dot_portfolio__pb2.GetPortfolioResponse.SerializeToString,
            ),
            'ListPortfolios': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPortfolios,
                    request_deserializer=llamatrade_dot_v1_dot_portfolio__pb2.ListPortfoliosRequest.FromString,
                    response_serializer=llamatrade_dot_v1_dot_portfolio__pb2.ListPortfoliosResponse.SerializeToString,
            ),
            'GetPerformance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPerformance,
                    request_deserializer=llamatrade_dot_v1_dot_portfolio__pb2.GetPerformanceRequest.FromString,
                    response_serializer=llamatrade_dot_v1_dot_portfolio__pb2.GetPerformanceResponse.SerializeToString,
            ),
            'GetAssetAllocation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAssetAllocation,
                    request_deserializer=llamatrade_dot_v1_dot_portfolio__pb2.GetAssetAllocationRequest.FromString,
                    response_serializer=llamatrade_dot_v1_dot_portfolio__pb2.GetAssetAllocationResponse.SerializeToString,
            ),
            'GetPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPositions,
                    request_deserializer=llamatrade_dot_v1_dot_portfolio__pb2.GetPositionsRequest.FromString,
                    response_serializer=llamatrade_dot_v1_dot_portfolio__pb2.GetPositionsResponse.SerializeToString,
            ),
            'ListTransactions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTransactions,
                    request_deserializer=llamatrade_dot_v1_dot_portfolio__pb2.ListTransactionsRequest.FromString,
                    response_serializer=llamatrade_dot_v1_dot_portfolio__pb2.ListTransactionsResponse.SerializeToString,
            ),
            'RecordTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordTransaction,
                    request_deserializer=llamatrade_dot_v1_dot_portfolio__pb2.RecordTransactionRequest.FromString,
                    response_serializer=llamatrade_dot_v1_dot_portfolio__pb2.RecordTransactionResponse.SerializeToString,
            ),
            'SyncPortfolio': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncPortfolio,
                    request_deserializer=llamatrade_dot_v1_dot_portfolio__pb2.SyncPortfolioRequest.FromString,
                    response_serializer=llamatrade_dot_v1_dot_portfolio__pb2.SyncPortfolioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'llamatrade.v1.PortfolioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('llamatrade.v1.PortfolioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PortfolioService:
    """=============================================================================
    SERVICE
    =============================================================================

    """

    @staticmethod
    def GetPortfolio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llamatrade.v1.PortfolioService/GetPortfolio',
            llamatrade_dot_v1_dot_portfolio__pb2.GetPortfolioRequest.SerializeToString,
            llamatrade_dot_v1_dot_portfolio__pb2.GetPortfolioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPortfolios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llamatrade.v1.PortfolioService/ListPortfolios',
            llamatrade_dot_v1_dot_portfolio__pb2.ListPortfoliosRequest.SerializeToString,
            llamatrade_dot_v1_dot_portfolio__pb2.ListPortfoliosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPerformance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llamatrade.v1.PortfolioService/GetPerformance',
            llamatrade_dot_v1_dot_portfolio__pb2.GetPerformanceRequest.SerializeToString,
            llamatrade_dot_v1_dot_portfolio__pb2.GetPerformanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAssetAllocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llamatrade.v1.PortfolioService/GetAssetAllocation',
            llamatrade_dot_v1_dot_portfolio__pb2.GetAssetAllocationRequest.SerializeToString,
            llamatrade_dot_v1_dot_portfolio__pb2.GetAssetAllocationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llamatrade.v1.PortfolioService/GetPositions',
            llamatrade_dot_v1_dot_portfolio__pb2.GetPositionsRequest.SerializeToString,
            llamatrade_dot_v1_dot_portfolio__pb2.GetPositionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTransactions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llamatrade.v1.PortfolioService/ListTransactions',
            llamatrade_dot_v1_dot_portfolio__pb2.ListTransactionsRequest.SerializeToString,
            llamatrade_dot_v1_dot_portfolio__pb2.ListTransactionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llamatrade.v1.PortfolioService/RecordTransaction',
            llamatrade_dot_v1_dot_portfolio__pb2.RecordTransactionRequest.SerializeToString,
            llamatrade_dot_v1_dot_portfolio__pb2.RecordTransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncPortfolio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llamatrade.v1.PortfolioService/SyncPortfolio',
            llamatrade_dot_v1_dot_portfolio__pb2.SyncPortfolioRequest.SerializeToString,
            llamatrade_dot_v1_dot_portfolio__pb2.SyncPortfolioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
