# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: llamatrade/v1/portfolio.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import llamatrade.v1.portfolio_pb2 as llamatrade_dot_v1_dot_portfolio__pb2


class PortfolioService(Protocol):
    async def get_portfolio(self, request: llamatrade_dot_v1_dot_portfolio__pb2.GetPortfolioRequest, ctx: RequestContext) -> llamatrade_dot_v1_dot_portfolio__pb2.GetPortfolioResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_portfolios(self, request: llamatrade_dot_v1_dot_portfolio__pb2.ListPortfoliosRequest, ctx: RequestContext) -> llamatrade_dot_v1_dot_portfolio__pb2.ListPortfoliosResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_performance(self, request: llamatrade_dot_v1_dot_portfolio__pb2.GetPerformanceRequest, ctx: RequestContext) -> llamatrade_dot_v1_dot_portfolio__pb2.GetPerformanceResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_asset_allocation(self, request: llamatrade_dot_v1_dot_portfolio__pb2.GetAssetAllocationRequest, ctx: RequestContext) -> llamatrade_dot_v1_dot_portfolio__pb2.GetAssetAllocationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_positions(self, request: llamatrade_dot_v1_dot_portfolio__pb2.GetPositionsRequest, ctx: RequestContext) -> llamatrade_dot_v1_dot_portfolio__pb2.GetPositionsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_transactions(self, request: llamatrade_dot_v1_dot_portfolio__pb2.ListTransactionsRequest, ctx: RequestContext) -> llamatrade_dot_v1_dot_portfolio__pb2.ListTransactionsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def record_transaction(self, request: llamatrade_dot_v1_dot_portfolio__pb2.RecordTransactionRequest, ctx: RequestContext) -> llamatrade_dot_v1_dot_portfolio__pb2.RecordTransactionResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def sync_portfolio(self, request: llamatrade_dot_v1_dot_portfolio__pb2.SyncPortfolioRequest, ctx: RequestContext) -> llamatrade_dot_v1_dot_portfolio__pb2.SyncPortfolioResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class PortfolioServiceASGIApplication(ConnectASGIApplication[PortfolioService]):
    def __init__(self, service: PortfolioService | AsyncGenerator[PortfolioService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/llamatrade.v1.PortfolioService/GetPortfolio": Endpoint.unary(
                    method=MethodInfo(
                        name="GetPortfolio",
                        service_name="llamatrade.v1.PortfolioService",
                        input=llamatrade_dot_v1_dot_portfolio__pb2.GetPortfolioRequest,
                        output=llamatrade_dot_v1_dot_portfolio__pb2.GetPortfolioResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_portfolio,
                ),
                "/llamatrade.v1.PortfolioService/ListPortfolios": Endpoint.unary(
                    method=MethodInfo(
                        name="ListPortfolios",
                        service_name="llamatrade.v1.PortfolioService",
                        input=llamatrade_dot_v1_dot_portfolio__pb2.ListPortfoliosRequest,
                        output=llamatrade_dot_v1_dot_portfolio__pb2.ListPortfoliosResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_portfolios,
                ),
                "/llamatrade.v1.PortfolioService/GetPerformance": Endpoint.unary(
                    method=MethodInfo(
                        name="GetPerformance",
                        service_name="llamatrade.v1.PortfolioService",
                        input=llamatrade_dot_v1_dot_portfolio__pb2.GetPerformanceRequest,
                        output=llamatrade_dot_v1_dot_portfolio__pb2.GetPerformanceResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_performance,
                ),
                "/llamatrade.v1.PortfolioService/GetAssetAllocation": Endpoint.unary(
                    method=MethodInfo(
                        name="GetAssetAllocation",
                        service_name="llamatrade.v1.PortfolioService",
                        input=llamatrade_dot_v1_dot_portfolio__pb2.GetAssetAllocationRequest,
                        output=llamatrade_dot_v1_dot_portfolio__pb2.GetAssetAllocationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_asset_allocation,
                ),
                "/llamatrade.v1.PortfolioService/GetPositions": Endpoint.unary(
                    method=MethodInfo(
                        name="GetPositions",
                        service_name="llamatrade.v1.PortfolioService",
                        input=llamatrade_dot_v1_dot_portfolio__pb2.GetPositionsRequest,
                        output=llamatrade_dot_v1_dot_portfolio__pb2.GetPositionsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_positions,
                ),
                "/llamatrade.v1.PortfolioService/ListTransactions": Endpoint.unary(
                    method=MethodInfo(
                        name="ListTransactions",
                        service_name="llamatrade.v1.PortfolioService",
                        input=llamatrade_dot_v1_dot_portfolio__pb2.ListTransactionsRequest,
                        output=llamatrade_dot_v1_dot_portfolio__pb2.ListTransactionsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_transactions,
                ),
                "/llamatrade.v1.PortfolioService/RecordTransaction": Endpoint.unary(
                    method=MethodInfo(
                        name="RecordTransaction",
                        service_name="llamatrade.v1.PortfolioService",
                        input=llamatrade_dot_v1_dot_portfolio__pb2.RecordTransactionRequest,
                        output=llamatrade_dot_v1_dot_portfolio__pb2.RecordTransactionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.record_transaction,
                ),
                "/llamatrade.v1.PortfolioService/SyncPortfolio": Endpoint.unary(
                    method=MethodInfo(
                        name="SyncPortfolio",
                        service_name="llamatrade.v1.PortfolioService",
                        input=llamatrade_dot_v1_dot_portfolio__pb2.SyncPortfolioRequest,
                        output=llamatrade_dot_v1_dot_portfolio__pb2.SyncPortfolioResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.sync_portfolio,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/llamatrade.v1.PortfolioService"


class PortfolioServiceClient(ConnectClient):
    async def get_portfolio(
        self,
        request: llamatrade_dot_v1_dot_portfolio__pb2.GetPortfolioRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> llamatrade_dot_v1_dot_portfolio__pb2.GetPortfolioResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetPortfolio",
                service_name="llamatrade.v1.PortfolioService",
                input=llamatrade_dot_v1_dot_portfolio__pb2.GetPortfolioRequest,
                output=llamatrade_dot_v1_dot_portfolio__pb2.GetPortfolioResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_portfolios(
        self,
        request: llamatrade_dot_v1_dot_portfolio__pb2.ListPortfoliosRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> llamatrade_dot_v1_dot_portfolio__pb2.ListPortfoliosResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListPortfolios",
                service_name="llamatrade.v1.PortfolioService",
                input=llamatrade_dot_v1_dot_portfolio__pb2.ListPortfoliosRequest,
                output=llamatrade_dot_v1_dot_portfolio__pb2.ListPortfoliosResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_performance(
        self,
        request: llamatrade_dot_v1_dot_portfolio__pb2.GetPerformanceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> llamatrade_dot_v1_dot_portfolio__pb2.GetPerformanceResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetPerformance",
                service_name="llamatrade.v1.PortfolioService",
                input=llamatrade_dot_v1_dot_portfolio__pb2.GetPerformanceRequest,
                output=llamatrade_dot_v1_dot_portfolio__pb2.GetPerformanceResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_asset_allocation(
        self,
        request: llamatrade_dot_v1_dot_portfolio__pb2.GetAssetAllocationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> llamatrade_dot_v1_dot_portfolio__pb2.GetAssetAllocationResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetAssetAllocation",
                service_name="llamatrade.v1.PortfolioService",
                input=llamatrade_dot_v1_dot_portfolio__pb2.GetAssetAllocationRequest,
                output=llamatrade_dot_v1_dot_portfolio__pb2.GetAssetAllocationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_positions(
        self,
        request: llamatrade_dot_v1_dot_portfolio__pb2.GetPositionsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> llamatrade_dot_v1_dot_portfolio__pb2.GetPositionsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetPositions",
                service_name="llamatrade.v1.PortfolioService",
                input=llamatrade_dot_v1_dot_portfolio__pb2.GetPositionsRequest,
                output=llamatrade_dot_v1_dot_portfolio__pb2.GetPositionsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_transactions(
        self,
        request: llamatrade_dot_v1_dot_portfolio__pb2.ListTransactionsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> llamatrade_dot_v1_dot_portfolio__pb2.ListTransactionsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListTransactions",
                service_name="llamatrade.v1.PortfolioService",
                input=llamatrade_dot_v1_dot_portfolio__pb2.ListTransactionsRequest,
                output=llamatrade_dot_v1_dot_portfolio__pb2.ListTransactionsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def record_transaction(
        self,
        request: llamatrade_dot_v1_dot_portfolio__pb2.RecordTransactionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> llamatrade_dot_v1_dot_portfolio__pb2.RecordTransactionResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RecordTransaction",
                service_name="llamatrade.v1.PortfolioService",
                input=llamatrade_dot_v1_dot_portfolio__pb2.RecordTransactionRequest,
                output=llamatrade_dot_v1_dot_portfolio__pb2.RecordTransactionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def sync_portfolio(
        self,
        request: llamatrade_dot_v1_dot_portfolio__pb2.SyncPortfolioRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> llamatrade_dot_v1_dot_portfolio__pb2.SyncPortfolioResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SyncPortfolio",
                service_name="llamatrade.v1.PortfolioService",
                input=llamatrade_dot_v1_dot_portfolio__pb2.SyncPortfolioRequest,
                output=llamatrade_dot_v1_dot_portfolio__pb2.SyncPortfolioResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class PortfolioServiceSync(Protocol):
    def get_portfolio(self, request: llamatrade_dot_v1_dot_portfolio__pb2.GetPortfolioRequest, ctx: RequestContext) -> llamatrade_dot_v1_dot_portfolio__pb2.GetPortfolioResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_portfolios(self, request: llamatrade_dot_v1_dot_portfolio__pb2.ListPortfoliosRequest, ctx: RequestContext) -> llamatrade_dot_v1_dot_portfolio__pb2.ListPortfoliosResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_performance(self, request: llamatrade_dot_v1_dot_portfolio__pb2.GetPerformanceRequest, ctx: RequestContext) -> llamatrade_dot_v1_dot_portfolio__pb2.GetPerformanceResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_asset_allocation(self, request: llamatrade_dot_v1_dot_portfolio__pb2.GetAssetAllocationRequest, ctx: RequestContext) -> llamatrade_dot_v1_dot_portfolio__pb2.GetAssetAllocationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_positions(self, request: llamatrade_dot_v1_dot_portfolio__pb2.GetPositionsRequest, ctx: RequestContext) -> llamatrade_dot_v1_dot_portfolio__pb2.GetPositionsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_transactions(self, request: llamatrade_dot_v1_dot_portfolio__pb2.ListTransactionsRequest, ctx: RequestContext) -> llamatrade_dot_v1_dot_portfolio__pb2.ListTransactionsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def record_transaction(self, request: llamatrade_dot_v1_dot_portfolio__pb2.RecordTransactionRequest, ctx: RequestContext) -> llamatrade_dot_v1_dot_portfolio__pb2.RecordTransactionResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def sync_portfolio(self, request: llamatrade_dot_v1_dot_portfolio__pb2.SyncPortfolioRequest, ctx: RequestContext) -> llamatrade_dot_v1_dot_portfolio__pb2.SyncPortfolioResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class PortfolioServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: PortfolioServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/llamatrade.v1.PortfolioService/GetPortfolio": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetPortfolio",
                        service_name="llamatrade.v1.PortfolioService",
                        input=llamatrade_dot_v1_dot_portfolio__pb2.GetPortfolioRequest,
                        output=llamatrade_dot_v1_dot_portfolio__pb2.GetPortfolioResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_portfolio,
                ),
                "/llamatrade.v1.PortfolioService/ListPortfolios": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListPortfolios",
                        service_name="llamatrade.v1.PortfolioService",
                        input=llamatrade_dot_v1_dot_portfolio__pb2.ListPortfoliosRequest,
                        output=llamatrade_dot_v1_dot_portfolio__pb2.ListPortfoliosResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_portfolios,
                ),
                "/llamatrade.v1.PortfolioService/GetPerformance": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetPerformance",
                        service_name="llamatrade.v1.PortfolioService",
                        input=llamatrade_dot_v1_dot_portfolio__pb2.GetPerformanceRequest,
                        output=llamatrade_dot_v1_dot_portfolio__pb2.GetPerformanceResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_performance,
                ),
                "/llamatrade.v1.PortfolioService/GetAssetAllocation": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetAssetAllocation",
                        service_name="llamatrade.v1.PortfolioService",
                        input=llamatrade_dot_v1_dot_portfolio__pb2.GetAssetAllocationRequest,
                        output=llamatrade_dot_v1_dot_portfolio__pb2.GetAssetAllocationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_asset_allocation,
                ),
                "/llamatrade.v1.PortfolioService/GetPositions": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetPositions",
                        service_name="llamatrade.v1.PortfolioService",
                        input=llamatrade_dot_v1_dot_portfolio__pb2.GetPositionsRequest,
                        output=llamatrade_dot_v1_dot_portfolio__pb2.GetPositionsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_positions,
                ),
                "/llamatrade.v1.PortfolioService/ListTransactions": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListTransactions",
                        service_name="llamatrade.v1.PortfolioService",
                        input=llamatrade_dot_v1_dot_portfolio__pb2.ListTransactionsRequest,
                        output=llamatrade_dot_v1_dot_portfolio__pb2.ListTransactionsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_transactions,
                ),
                "/llamatrade.v1.PortfolioService/RecordTransaction": EndpointSync.unary(
                    method=MethodInfo(
                        name="RecordTransaction",
                        service_name="llamatrade.v1.PortfolioService",
                        input=llamatrade_dot_v1_dot_portfolio__pb2.RecordTransactionRequest,
                        output=llamatrade_dot_v1_dot_portfolio__pb2.RecordTransactionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.record_transaction,
                ),
                "/llamatrade.v1.PortfolioService/SyncPortfolio": EndpointSync.unary(
                    method=MethodInfo(
                        name="SyncPortfolio",
                        service_name="llamatrade.v1.PortfolioService",
                        input=llamatrade_dot_v1_dot_portfolio__pb2.SyncPortfolioRequest,
                        output=llamatrade_dot_v1_dot_portfolio__pb2.SyncPortfolioResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.sync_portfolio,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/llamatrade.v1.PortfolioService"


class PortfolioServiceClientSync(ConnectClientSync):
    def get_portfolio(
        self,
        request: llamatrade_dot_v1_dot_portfolio__pb2.GetPortfolioRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> llamatrade_dot_v1_dot_portfolio__pb2.GetPortfolioResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetPortfolio",
                service_name="llamatrade.v1.PortfolioService",
                input=llamatrade_dot_v1_dot_portfolio__pb2.GetPortfolioRequest,
                output=llamatrade_dot_v1_dot_portfolio__pb2.GetPortfolioResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_portfolios(
        self,
        request: llamatrade_dot_v1_dot_portfolio__pb2.ListPortfoliosRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> llamatrade_dot_v1_dot_portfolio__pb2.ListPortfoliosResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListPortfolios",
                service_name="llamatrade.v1.PortfolioService",
                input=llamatrade_dot_v1_dot_portfolio__pb2.ListPortfoliosRequest,
                output=llamatrade_dot_v1_dot_portfolio__pb2.ListPortfoliosResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_performance(
        self,
        request: llamatrade_dot_v1_dot_portfolio__pb2.GetPerformanceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> llamatrade_dot_v1_dot_portfolio__pb2.GetPerformanceResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetPerformance",
                service_name="llamatrade.v1.PortfolioService",
                input=llamatrade_dot_v1_dot_portfolio__pb2.GetPerformanceRequest,
                output=llamatrade_dot_v1_dot_portfolio__pb2.GetPerformanceResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_asset_allocation(
        self,
        request: llamatrade_dot_v1_dot_portfolio__pb2.GetAssetAllocationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> llamatrade_dot_v1_dot_portfolio__pb2.GetAssetAllocationResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetAssetAllocation",
                service_name="llamatrade.v1.PortfolioService",
                input=llamatrade_dot_v1_dot_portfolio__pb2.GetAssetAllocationRequest,
                output=llamatrade_dot_v1_dot_portfolio__pb2.GetAssetAllocationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_positions(
        self,
        request: llamatrade_dot_v1_dot_portfolio__pb2.GetPositionsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> llamatrade_dot_v1_dot_portfolio__pb2.GetPositionsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetPositions",
                service_name="llamatrade.v1.PortfolioService",
                input=llamatrade_dot_v1_dot_portfolio__pb2.GetPositionsRequest,
                output=llamatrade_dot_v1_dot_portfolio__pb2.GetPositionsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_transactions(
        self,
        request: llamatrade_dot_v1_dot_portfolio__pb2.ListTransactionsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> llamatrade_dot_v1_dot_portfolio__pb2.ListTransactionsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListTransactions",
                service_name="llamatrade.v1.PortfolioService",
                input=llamatrade_dot_v1_dot_portfolio__pb2.ListTransactionsRequest,
                output=llamatrade_dot_v1_dot_portfolio__pb2.ListTransactionsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def record_transaction(
        self,
        request: llamatrade_dot_v1_dot_portfolio__pb2.RecordTransactionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> llamatrade_dot_v1_dot_portfolio__pb2.RecordTransactionResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RecordTransaction",
                service_name="llamatrade.v1.PortfolioService",
                input=llamatrade_dot_v1_dot_portfolio__pb2.RecordTransactionRequest,
                output=llamatrade_dot_v1_dot_portfolio__pb2.RecordTransactionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def sync_portfolio(
        self,
        request: llamatrade_dot_v1_dot_portfolio__pb2.SyncPortfolioRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> llamatrade_dot_v1_dot_portfolio__pb2.SyncPortfolioResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SyncPortfolio",
                service_name="llamatrade.v1.PortfolioService",
                input=llamatrade_dot_v1_dot_portfolio__pb2.SyncPortfolioRequest,
                output=llamatrade_dot_v1_dot_portfolio__pb2.SyncPortfolioResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
