"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc as _abc_1
import sys
import typing as _typing
from collections import abc as _abc

import grpc as _grpc
from grpc import aio as _aio

from llamatrade.v1 import strategy_pb2 as _strategy_pb2

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class StrategyServiceStub:
    """=============================================================================
    SERVICE
    =============================================================================
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> StrategyServiceAsyncStub: ...
    GetStrategy: _grpc.UnaryUnaryMultiCallable[_strategy_pb2.GetStrategyRequest, _strategy_pb2.GetStrategyResponse]
    """CRUD operations"""
    ListStrategies: _grpc.UnaryUnaryMultiCallable[_strategy_pb2.ListStrategiesRequest, _strategy_pb2.ListStrategiesResponse]
    CreateStrategy: _grpc.UnaryUnaryMultiCallable[_strategy_pb2.CreateStrategyRequest, _strategy_pb2.CreateStrategyResponse]
    UpdateStrategy: _grpc.UnaryUnaryMultiCallable[_strategy_pb2.UpdateStrategyRequest, _strategy_pb2.UpdateStrategyResponse]
    DeleteStrategy: _grpc.UnaryUnaryMultiCallable[_strategy_pb2.DeleteStrategyRequest, _strategy_pb2.DeleteStrategyResponse]
    CompileStrategy: _grpc.UnaryUnaryMultiCallable[_strategy_pb2.CompileStrategyRequest, _strategy_pb2.CompileStrategyResponse]
    """DSL operations"""
    ValidateStrategy: _grpc.UnaryUnaryMultiCallable[_strategy_pb2.ValidateStrategyRequest, _strategy_pb2.ValidateStrategyResponse]
    ListStrategyVersions: _grpc.UnaryUnaryMultiCallable[_strategy_pb2.ListStrategyVersionsRequest, _strategy_pb2.ListStrategyVersionsResponse]
    """Version management"""
    UpdateStrategyStatus: _grpc.UnaryUnaryMultiCallable[_strategy_pb2.UpdateStrategyStatusRequest, _strategy_pb2.UpdateStrategyStatusResponse]
    """Status management"""

@_typing.type_check_only
class StrategyServiceAsyncStub(StrategyServiceStub):
    """=============================================================================
    SERVICE
    =============================================================================
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    GetStrategy: _aio.UnaryUnaryMultiCallable[_strategy_pb2.GetStrategyRequest, _strategy_pb2.GetStrategyResponse]  # type: ignore[assignment]
    """CRUD operations"""
    ListStrategies: _aio.UnaryUnaryMultiCallable[_strategy_pb2.ListStrategiesRequest, _strategy_pb2.ListStrategiesResponse]  # type: ignore[assignment]
    CreateStrategy: _aio.UnaryUnaryMultiCallable[_strategy_pb2.CreateStrategyRequest, _strategy_pb2.CreateStrategyResponse]  # type: ignore[assignment]
    UpdateStrategy: _aio.UnaryUnaryMultiCallable[_strategy_pb2.UpdateStrategyRequest, _strategy_pb2.UpdateStrategyResponse]  # type: ignore[assignment]
    DeleteStrategy: _aio.UnaryUnaryMultiCallable[_strategy_pb2.DeleteStrategyRequest, _strategy_pb2.DeleteStrategyResponse]  # type: ignore[assignment]
    CompileStrategy: _aio.UnaryUnaryMultiCallable[_strategy_pb2.CompileStrategyRequest, _strategy_pb2.CompileStrategyResponse]  # type: ignore[assignment]
    """DSL operations"""
    ValidateStrategy: _aio.UnaryUnaryMultiCallable[_strategy_pb2.ValidateStrategyRequest, _strategy_pb2.ValidateStrategyResponse]  # type: ignore[assignment]
    ListStrategyVersions: _aio.UnaryUnaryMultiCallable[_strategy_pb2.ListStrategyVersionsRequest, _strategy_pb2.ListStrategyVersionsResponse]  # type: ignore[assignment]
    """Version management"""
    UpdateStrategyStatus: _aio.UnaryUnaryMultiCallable[_strategy_pb2.UpdateStrategyStatusRequest, _strategy_pb2.UpdateStrategyStatusResponse]  # type: ignore[assignment]
    """Status management"""

class StrategyServiceServicer(metaclass=_abc_1.ABCMeta):
    """=============================================================================
    SERVICE
    =============================================================================
    """

    @_abc_1.abstractmethod
    def GetStrategy(
        self,
        request: _strategy_pb2.GetStrategyRequest,
        context: _ServicerContext,
    ) -> _strategy_pb2.GetStrategyResponse | _abc.Awaitable[_strategy_pb2.GetStrategyResponse]:
        """CRUD operations"""

    @_abc_1.abstractmethod
    def ListStrategies(
        self,
        request: _strategy_pb2.ListStrategiesRequest,
        context: _ServicerContext,
    ) -> _strategy_pb2.ListStrategiesResponse | _abc.Awaitable[_strategy_pb2.ListStrategiesResponse]: ...

    @_abc_1.abstractmethod
    def CreateStrategy(
        self,
        request: _strategy_pb2.CreateStrategyRequest,
        context: _ServicerContext,
    ) -> _strategy_pb2.CreateStrategyResponse | _abc.Awaitable[_strategy_pb2.CreateStrategyResponse]: ...

    @_abc_1.abstractmethod
    def UpdateStrategy(
        self,
        request: _strategy_pb2.UpdateStrategyRequest,
        context: _ServicerContext,
    ) -> _strategy_pb2.UpdateStrategyResponse | _abc.Awaitable[_strategy_pb2.UpdateStrategyResponse]: ...

    @_abc_1.abstractmethod
    def DeleteStrategy(
        self,
        request: _strategy_pb2.DeleteStrategyRequest,
        context: _ServicerContext,
    ) -> _strategy_pb2.DeleteStrategyResponse | _abc.Awaitable[_strategy_pb2.DeleteStrategyResponse]: ...

    @_abc_1.abstractmethod
    def CompileStrategy(
        self,
        request: _strategy_pb2.CompileStrategyRequest,
        context: _ServicerContext,
    ) -> _strategy_pb2.CompileStrategyResponse | _abc.Awaitable[_strategy_pb2.CompileStrategyResponse]:
        """DSL operations"""

    @_abc_1.abstractmethod
    def ValidateStrategy(
        self,
        request: _strategy_pb2.ValidateStrategyRequest,
        context: _ServicerContext,
    ) -> _strategy_pb2.ValidateStrategyResponse | _abc.Awaitable[_strategy_pb2.ValidateStrategyResponse]: ...

    @_abc_1.abstractmethod
    def ListStrategyVersions(
        self,
        request: _strategy_pb2.ListStrategyVersionsRequest,
        context: _ServicerContext,
    ) -> _strategy_pb2.ListStrategyVersionsResponse | _abc.Awaitable[_strategy_pb2.ListStrategyVersionsResponse]:
        """Version management"""

    @_abc_1.abstractmethod
    def UpdateStrategyStatus(
        self,
        request: _strategy_pb2.UpdateStrategyStatusRequest,
        context: _ServicerContext,
    ) -> _strategy_pb2.UpdateStrategyStatusResponse | _abc.Awaitable[_strategy_pb2.UpdateStrategyStatusResponse]:
        """Status management"""

def add_StrategyServiceServicer_to_server(servicer: StrategyServiceServicer, server: _grpc.Server | _aio.Server) -> None: ...
