# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: llamatrade/v1/strategy.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import llamatrade.v1.strategy_pb2 as llamatrade_dot_v1_dot_strategy__pb2


class StrategyService(Protocol):
    async def get_strategy(self, request: llamatrade_dot_v1_dot_strategy__pb2.GetStrategyRequest, ctx: RequestContext) -> llamatrade_dot_v1_dot_strategy__pb2.GetStrategyResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_strategies(self, request: llamatrade_dot_v1_dot_strategy__pb2.ListStrategiesRequest, ctx: RequestContext) -> llamatrade_dot_v1_dot_strategy__pb2.ListStrategiesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def create_strategy(self, request: llamatrade_dot_v1_dot_strategy__pb2.CreateStrategyRequest, ctx: RequestContext) -> llamatrade_dot_v1_dot_strategy__pb2.CreateStrategyResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_strategy(self, request: llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyRequest, ctx: RequestContext) -> llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_strategy(self, request: llamatrade_dot_v1_dot_strategy__pb2.DeleteStrategyRequest, ctx: RequestContext) -> llamatrade_dot_v1_dot_strategy__pb2.DeleteStrategyResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def compile_strategy(self, request: llamatrade_dot_v1_dot_strategy__pb2.CompileStrategyRequest, ctx: RequestContext) -> llamatrade_dot_v1_dot_strategy__pb2.CompileStrategyResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def validate_strategy(self, request: llamatrade_dot_v1_dot_strategy__pb2.ValidateStrategyRequest, ctx: RequestContext) -> llamatrade_dot_v1_dot_strategy__pb2.ValidateStrategyResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_strategy_versions(self, request: llamatrade_dot_v1_dot_strategy__pb2.ListStrategyVersionsRequest, ctx: RequestContext) -> llamatrade_dot_v1_dot_strategy__pb2.ListStrategyVersionsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_strategy_status(self, request: llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyStatusRequest, ctx: RequestContext) -> llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyStatusResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class StrategyServiceASGIApplication(ConnectASGIApplication[StrategyService]):
    def __init__(self, service: StrategyService | AsyncGenerator[StrategyService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/llamatrade.v1.StrategyService/GetStrategy": Endpoint.unary(
                    method=MethodInfo(
                        name="GetStrategy",
                        service_name="llamatrade.v1.StrategyService",
                        input=llamatrade_dot_v1_dot_strategy__pb2.GetStrategyRequest,
                        output=llamatrade_dot_v1_dot_strategy__pb2.GetStrategyResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_strategy,
                ),
                "/llamatrade.v1.StrategyService/ListStrategies": Endpoint.unary(
                    method=MethodInfo(
                        name="ListStrategies",
                        service_name="llamatrade.v1.StrategyService",
                        input=llamatrade_dot_v1_dot_strategy__pb2.ListStrategiesRequest,
                        output=llamatrade_dot_v1_dot_strategy__pb2.ListStrategiesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_strategies,
                ),
                "/llamatrade.v1.StrategyService/CreateStrategy": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateStrategy",
                        service_name="llamatrade.v1.StrategyService",
                        input=llamatrade_dot_v1_dot_strategy__pb2.CreateStrategyRequest,
                        output=llamatrade_dot_v1_dot_strategy__pb2.CreateStrategyResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_strategy,
                ),
                "/llamatrade.v1.StrategyService/UpdateStrategy": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateStrategy",
                        service_name="llamatrade.v1.StrategyService",
                        input=llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyRequest,
                        output=llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_strategy,
                ),
                "/llamatrade.v1.StrategyService/DeleteStrategy": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteStrategy",
                        service_name="llamatrade.v1.StrategyService",
                        input=llamatrade_dot_v1_dot_strategy__pb2.DeleteStrategyRequest,
                        output=llamatrade_dot_v1_dot_strategy__pb2.DeleteStrategyResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_strategy,
                ),
                "/llamatrade.v1.StrategyService/CompileStrategy": Endpoint.unary(
                    method=MethodInfo(
                        name="CompileStrategy",
                        service_name="llamatrade.v1.StrategyService",
                        input=llamatrade_dot_v1_dot_strategy__pb2.CompileStrategyRequest,
                        output=llamatrade_dot_v1_dot_strategy__pb2.CompileStrategyResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.compile_strategy,
                ),
                "/llamatrade.v1.StrategyService/ValidateStrategy": Endpoint.unary(
                    method=MethodInfo(
                        name="ValidateStrategy",
                        service_name="llamatrade.v1.StrategyService",
                        input=llamatrade_dot_v1_dot_strategy__pb2.ValidateStrategyRequest,
                        output=llamatrade_dot_v1_dot_strategy__pb2.ValidateStrategyResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.validate_strategy,
                ),
                "/llamatrade.v1.StrategyService/ListStrategyVersions": Endpoint.unary(
                    method=MethodInfo(
                        name="ListStrategyVersions",
                        service_name="llamatrade.v1.StrategyService",
                        input=llamatrade_dot_v1_dot_strategy__pb2.ListStrategyVersionsRequest,
                        output=llamatrade_dot_v1_dot_strategy__pb2.ListStrategyVersionsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_strategy_versions,
                ),
                "/llamatrade.v1.StrategyService/UpdateStrategyStatus": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateStrategyStatus",
                        service_name="llamatrade.v1.StrategyService",
                        input=llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyStatusRequest,
                        output=llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyStatusResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_strategy_status,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/llamatrade.v1.StrategyService"


class StrategyServiceClient(ConnectClient):
    async def get_strategy(
        self,
        request: llamatrade_dot_v1_dot_strategy__pb2.GetStrategyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> llamatrade_dot_v1_dot_strategy__pb2.GetStrategyResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetStrategy",
                service_name="llamatrade.v1.StrategyService",
                input=llamatrade_dot_v1_dot_strategy__pb2.GetStrategyRequest,
                output=llamatrade_dot_v1_dot_strategy__pb2.GetStrategyResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_strategies(
        self,
        request: llamatrade_dot_v1_dot_strategy__pb2.ListStrategiesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> llamatrade_dot_v1_dot_strategy__pb2.ListStrategiesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListStrategies",
                service_name="llamatrade.v1.StrategyService",
                input=llamatrade_dot_v1_dot_strategy__pb2.ListStrategiesRequest,
                output=llamatrade_dot_v1_dot_strategy__pb2.ListStrategiesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def create_strategy(
        self,
        request: llamatrade_dot_v1_dot_strategy__pb2.CreateStrategyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> llamatrade_dot_v1_dot_strategy__pb2.CreateStrategyResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateStrategy",
                service_name="llamatrade.v1.StrategyService",
                input=llamatrade_dot_v1_dot_strategy__pb2.CreateStrategyRequest,
                output=llamatrade_dot_v1_dot_strategy__pb2.CreateStrategyResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_strategy(
        self,
        request: llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateStrategy",
                service_name="llamatrade.v1.StrategyService",
                input=llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyRequest,
                output=llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_strategy(
        self,
        request: llamatrade_dot_v1_dot_strategy__pb2.DeleteStrategyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> llamatrade_dot_v1_dot_strategy__pb2.DeleteStrategyResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteStrategy",
                service_name="llamatrade.v1.StrategyService",
                input=llamatrade_dot_v1_dot_strategy__pb2.DeleteStrategyRequest,
                output=llamatrade_dot_v1_dot_strategy__pb2.DeleteStrategyResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def compile_strategy(
        self,
        request: llamatrade_dot_v1_dot_strategy__pb2.CompileStrategyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> llamatrade_dot_v1_dot_strategy__pb2.CompileStrategyResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CompileStrategy",
                service_name="llamatrade.v1.StrategyService",
                input=llamatrade_dot_v1_dot_strategy__pb2.CompileStrategyRequest,
                output=llamatrade_dot_v1_dot_strategy__pb2.CompileStrategyResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def validate_strategy(
        self,
        request: llamatrade_dot_v1_dot_strategy__pb2.ValidateStrategyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> llamatrade_dot_v1_dot_strategy__pb2.ValidateStrategyResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ValidateStrategy",
                service_name="llamatrade.v1.StrategyService",
                input=llamatrade_dot_v1_dot_strategy__pb2.ValidateStrategyRequest,
                output=llamatrade_dot_v1_dot_strategy__pb2.ValidateStrategyResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_strategy_versions(
        self,
        request: llamatrade_dot_v1_dot_strategy__pb2.ListStrategyVersionsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> llamatrade_dot_v1_dot_strategy__pb2.ListStrategyVersionsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListStrategyVersions",
                service_name="llamatrade.v1.StrategyService",
                input=llamatrade_dot_v1_dot_strategy__pb2.ListStrategyVersionsRequest,
                output=llamatrade_dot_v1_dot_strategy__pb2.ListStrategyVersionsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_strategy_status(
        self,
        request: llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyStatusRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyStatusResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateStrategyStatus",
                service_name="llamatrade.v1.StrategyService",
                input=llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyStatusRequest,
                output=llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyStatusResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class StrategyServiceSync(Protocol):
    def get_strategy(self, request: llamatrade_dot_v1_dot_strategy__pb2.GetStrategyRequest, ctx: RequestContext) -> llamatrade_dot_v1_dot_strategy__pb2.GetStrategyResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_strategies(self, request: llamatrade_dot_v1_dot_strategy__pb2.ListStrategiesRequest, ctx: RequestContext) -> llamatrade_dot_v1_dot_strategy__pb2.ListStrategiesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def create_strategy(self, request: llamatrade_dot_v1_dot_strategy__pb2.CreateStrategyRequest, ctx: RequestContext) -> llamatrade_dot_v1_dot_strategy__pb2.CreateStrategyResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_strategy(self, request: llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyRequest, ctx: RequestContext) -> llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_strategy(self, request: llamatrade_dot_v1_dot_strategy__pb2.DeleteStrategyRequest, ctx: RequestContext) -> llamatrade_dot_v1_dot_strategy__pb2.DeleteStrategyResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def compile_strategy(self, request: llamatrade_dot_v1_dot_strategy__pb2.CompileStrategyRequest, ctx: RequestContext) -> llamatrade_dot_v1_dot_strategy__pb2.CompileStrategyResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def validate_strategy(self, request: llamatrade_dot_v1_dot_strategy__pb2.ValidateStrategyRequest, ctx: RequestContext) -> llamatrade_dot_v1_dot_strategy__pb2.ValidateStrategyResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_strategy_versions(self, request: llamatrade_dot_v1_dot_strategy__pb2.ListStrategyVersionsRequest, ctx: RequestContext) -> llamatrade_dot_v1_dot_strategy__pb2.ListStrategyVersionsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_strategy_status(self, request: llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyStatusRequest, ctx: RequestContext) -> llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyStatusResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class StrategyServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: StrategyServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/llamatrade.v1.StrategyService/GetStrategy": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetStrategy",
                        service_name="llamatrade.v1.StrategyService",
                        input=llamatrade_dot_v1_dot_strategy__pb2.GetStrategyRequest,
                        output=llamatrade_dot_v1_dot_strategy__pb2.GetStrategyResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_strategy,
                ),
                "/llamatrade.v1.StrategyService/ListStrategies": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListStrategies",
                        service_name="llamatrade.v1.StrategyService",
                        input=llamatrade_dot_v1_dot_strategy__pb2.ListStrategiesRequest,
                        output=llamatrade_dot_v1_dot_strategy__pb2.ListStrategiesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_strategies,
                ),
                "/llamatrade.v1.StrategyService/CreateStrategy": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateStrategy",
                        service_name="llamatrade.v1.StrategyService",
                        input=llamatrade_dot_v1_dot_strategy__pb2.CreateStrategyRequest,
                        output=llamatrade_dot_v1_dot_strategy__pb2.CreateStrategyResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_strategy,
                ),
                "/llamatrade.v1.StrategyService/UpdateStrategy": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateStrategy",
                        service_name="llamatrade.v1.StrategyService",
                        input=llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyRequest,
                        output=llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_strategy,
                ),
                "/llamatrade.v1.StrategyService/DeleteStrategy": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteStrategy",
                        service_name="llamatrade.v1.StrategyService",
                        input=llamatrade_dot_v1_dot_strategy__pb2.DeleteStrategyRequest,
                        output=llamatrade_dot_v1_dot_strategy__pb2.DeleteStrategyResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_strategy,
                ),
                "/llamatrade.v1.StrategyService/CompileStrategy": EndpointSync.unary(
                    method=MethodInfo(
                        name="CompileStrategy",
                        service_name="llamatrade.v1.StrategyService",
                        input=llamatrade_dot_v1_dot_strategy__pb2.CompileStrategyRequest,
                        output=llamatrade_dot_v1_dot_strategy__pb2.CompileStrategyResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.compile_strategy,
                ),
                "/llamatrade.v1.StrategyService/ValidateStrategy": EndpointSync.unary(
                    method=MethodInfo(
                        name="ValidateStrategy",
                        service_name="llamatrade.v1.StrategyService",
                        input=llamatrade_dot_v1_dot_strategy__pb2.ValidateStrategyRequest,
                        output=llamatrade_dot_v1_dot_strategy__pb2.ValidateStrategyResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.validate_strategy,
                ),
                "/llamatrade.v1.StrategyService/ListStrategyVersions": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListStrategyVersions",
                        service_name="llamatrade.v1.StrategyService",
                        input=llamatrade_dot_v1_dot_strategy__pb2.ListStrategyVersionsRequest,
                        output=llamatrade_dot_v1_dot_strategy__pb2.ListStrategyVersionsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_strategy_versions,
                ),
                "/llamatrade.v1.StrategyService/UpdateStrategyStatus": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateStrategyStatus",
                        service_name="llamatrade.v1.StrategyService",
                        input=llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyStatusRequest,
                        output=llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyStatusResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_strategy_status,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/llamatrade.v1.StrategyService"


class StrategyServiceClientSync(ConnectClientSync):
    def get_strategy(
        self,
        request: llamatrade_dot_v1_dot_strategy__pb2.GetStrategyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> llamatrade_dot_v1_dot_strategy__pb2.GetStrategyResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetStrategy",
                service_name="llamatrade.v1.StrategyService",
                input=llamatrade_dot_v1_dot_strategy__pb2.GetStrategyRequest,
                output=llamatrade_dot_v1_dot_strategy__pb2.GetStrategyResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_strategies(
        self,
        request: llamatrade_dot_v1_dot_strategy__pb2.ListStrategiesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> llamatrade_dot_v1_dot_strategy__pb2.ListStrategiesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListStrategies",
                service_name="llamatrade.v1.StrategyService",
                input=llamatrade_dot_v1_dot_strategy__pb2.ListStrategiesRequest,
                output=llamatrade_dot_v1_dot_strategy__pb2.ListStrategiesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def create_strategy(
        self,
        request: llamatrade_dot_v1_dot_strategy__pb2.CreateStrategyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> llamatrade_dot_v1_dot_strategy__pb2.CreateStrategyResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateStrategy",
                service_name="llamatrade.v1.StrategyService",
                input=llamatrade_dot_v1_dot_strategy__pb2.CreateStrategyRequest,
                output=llamatrade_dot_v1_dot_strategy__pb2.CreateStrategyResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_strategy(
        self,
        request: llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateStrategy",
                service_name="llamatrade.v1.StrategyService",
                input=llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyRequest,
                output=llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_strategy(
        self,
        request: llamatrade_dot_v1_dot_strategy__pb2.DeleteStrategyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> llamatrade_dot_v1_dot_strategy__pb2.DeleteStrategyResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteStrategy",
                service_name="llamatrade.v1.StrategyService",
                input=llamatrade_dot_v1_dot_strategy__pb2.DeleteStrategyRequest,
                output=llamatrade_dot_v1_dot_strategy__pb2.DeleteStrategyResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def compile_strategy(
        self,
        request: llamatrade_dot_v1_dot_strategy__pb2.CompileStrategyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> llamatrade_dot_v1_dot_strategy__pb2.CompileStrategyResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CompileStrategy",
                service_name="llamatrade.v1.StrategyService",
                input=llamatrade_dot_v1_dot_strategy__pb2.CompileStrategyRequest,
                output=llamatrade_dot_v1_dot_strategy__pb2.CompileStrategyResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def validate_strategy(
        self,
        request: llamatrade_dot_v1_dot_strategy__pb2.ValidateStrategyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> llamatrade_dot_v1_dot_strategy__pb2.ValidateStrategyResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ValidateStrategy",
                service_name="llamatrade.v1.StrategyService",
                input=llamatrade_dot_v1_dot_strategy__pb2.ValidateStrategyRequest,
                output=llamatrade_dot_v1_dot_strategy__pb2.ValidateStrategyResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_strategy_versions(
        self,
        request: llamatrade_dot_v1_dot_strategy__pb2.ListStrategyVersionsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> llamatrade_dot_v1_dot_strategy__pb2.ListStrategyVersionsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListStrategyVersions",
                service_name="llamatrade.v1.StrategyService",
                input=llamatrade_dot_v1_dot_strategy__pb2.ListStrategyVersionsRequest,
                output=llamatrade_dot_v1_dot_strategy__pb2.ListStrategyVersionsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_strategy_status(
        self,
        request: llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyStatusRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyStatusResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateStrategyStatus",
                service_name="llamatrade.v1.StrategyService",
                input=llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyStatusRequest,
                output=llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyStatusResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
