# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from llamatrade.v1 import strategy_pb2 as llamatrade_dot_v1_dot_strategy__pb2


class StrategyServiceStub:
    """=============================================================================
    SERVICE
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStrategy = channel.unary_unary(
                '/llamatrade.v1.StrategyService/GetStrategy',
                request_serializer=llamatrade_dot_v1_dot_strategy__pb2.GetStrategyRequest.SerializeToString,
                response_deserializer=llamatrade_dot_v1_dot_strategy__pb2.GetStrategyResponse.FromString,
                _registered_method=True)
        self.ListStrategies = channel.unary_unary(
                '/llamatrade.v1.StrategyService/ListStrategies',
                request_serializer=llamatrade_dot_v1_dot_strategy__pb2.ListStrategiesRequest.SerializeToString,
                response_deserializer=llamatrade_dot_v1_dot_strategy__pb2.ListStrategiesResponse.FromString,
                _registered_method=True)
        self.CreateStrategy = channel.unary_unary(
                '/llamatrade.v1.StrategyService/CreateStrategy',
                request_serializer=llamatrade_dot_v1_dot_strategy__pb2.CreateStrategyRequest.SerializeToString,
                response_deserializer=llamatrade_dot_v1_dot_strategy__pb2.CreateStrategyResponse.FromString,
                _registered_method=True)
        self.UpdateStrategy = channel.unary_unary(
                '/llamatrade.v1.StrategyService/UpdateStrategy',
                request_serializer=llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyRequest.SerializeToString,
                response_deserializer=llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyResponse.FromString,
                _registered_method=True)
        self.DeleteStrategy = channel.unary_unary(
                '/llamatrade.v1.StrategyService/DeleteStrategy',
                request_serializer=llamatrade_dot_v1_dot_strategy__pb2.DeleteStrategyRequest.SerializeToString,
                response_deserializer=llamatrade_dot_v1_dot_strategy__pb2.DeleteStrategyResponse.FromString,
                _registered_method=True)
        self.CompileStrategy = channel.unary_unary(
                '/llamatrade.v1.StrategyService/CompileStrategy',
                request_serializer=llamatrade_dot_v1_dot_strategy__pb2.CompileStrategyRequest.SerializeToString,
                response_deserializer=llamatrade_dot_v1_dot_strategy__pb2.CompileStrategyResponse.FromString,
                _registered_method=True)
        self.ValidateStrategy = channel.unary_unary(
                '/llamatrade.v1.StrategyService/ValidateStrategy',
                request_serializer=llamatrade_dot_v1_dot_strategy__pb2.ValidateStrategyRequest.SerializeToString,
                response_deserializer=llamatrade_dot_v1_dot_strategy__pb2.ValidateStrategyResponse.FromString,
                _registered_method=True)
        self.ListStrategyVersions = channel.unary_unary(
                '/llamatrade.v1.StrategyService/ListStrategyVersions',
                request_serializer=llamatrade_dot_v1_dot_strategy__pb2.ListStrategyVersionsRequest.SerializeToString,
                response_deserializer=llamatrade_dot_v1_dot_strategy__pb2.ListStrategyVersionsResponse.FromString,
                _registered_method=True)
        self.UpdateStrategyStatus = channel.unary_unary(
                '/llamatrade.v1.StrategyService/UpdateStrategyStatus',
                request_serializer=llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyStatusRequest.SerializeToString,
                response_deserializer=llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyStatusResponse.FromString,
                _registered_method=True)


class StrategyServiceServicer:
    """=============================================================================
    SERVICE
    =============================================================================

    """

    def GetStrategy(self, request, context):
        """CRUD operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListStrategies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateStrategy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStrategy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteStrategy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompileStrategy(self, request, context):
        """DSL operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateStrategy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListStrategyVersions(self, request, context):
        """Version management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStrategyStatus(self, request, context):
        """Status management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StrategyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStrategy,
                    request_deserializer=llamatrade_dot_v1_dot_strategy__pb2.GetStrategyRequest.FromString,
                    response_serializer=llamatrade_dot_v1_dot_strategy__pb2.GetStrategyResponse.SerializeToString,
            ),
            'ListStrategies': grpc.unary_unary_rpc_method_handler(
                    servicer.ListStrategies,
                    request_deserializer=llamatrade_dot_v1_dot_strategy__pb2.ListStrategiesRequest.FromString,
                    response_serializer=llamatrade_dot_v1_dot_strategy__pb2.ListStrategiesResponse.SerializeToString,
            ),
            'CreateStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateStrategy,
                    request_deserializer=llamatrade_dot_v1_dot_strategy__pb2.CreateStrategyRequest.FromString,
                    response_serializer=llamatrade_dot_v1_dot_strategy__pb2.CreateStrategyResponse.SerializeToString,
            ),
            'UpdateStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStrategy,
                    request_deserializer=llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyRequest.FromString,
                    response_serializer=llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyResponse.SerializeToString,
            ),
            'DeleteStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteStrategy,
                    request_deserializer=llamatrade_dot_v1_dot_strategy__pb2.DeleteStrategyRequest.FromString,
                    response_serializer=llamatrade_dot_v1_dot_strategy__pb2.DeleteStrategyResponse.SerializeToString,
            ),
            'CompileStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.CompileStrategy,
                    request_deserializer=llamatrade_dot_v1_dot_strategy__pb2.CompileStrategyRequest.FromString,
                    response_serializer=llamatrade_dot_v1_dot_strategy__pb2.CompileStrategyResponse.SerializeToString,
            ),
            'ValidateStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateStrategy,
                    request_deserializer=llamatrade_dot_v1_dot_strategy__pb2.ValidateStrategyRequest.FromString,
                    response_serializer=llamatrade_dot_v1_dot_strategy__pb2.ValidateStrategyResponse.SerializeToString,
            ),
            'ListStrategyVersions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListStrategyVersions,
                    request_deserializer=llamatrade_dot_v1_dot_strategy__pb2.ListStrategyVersionsRequest.FromString,
                    response_serializer=llamatrade_dot_v1_dot_strategy__pb2.ListStrategyVersionsResponse.SerializeToString,
            ),
            'UpdateStrategyStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStrategyStatus,
                    request_deserializer=llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyStatusRequest.FromString,
                    response_serializer=llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'llamatrade.v1.StrategyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('llamatrade.v1.StrategyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StrategyService:
    """=============================================================================
    SERVICE
    =============================================================================

    """

    @staticmethod
    def GetStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llamatrade.v1.StrategyService/GetStrategy',
            llamatrade_dot_v1_dot_strategy__pb2.GetStrategyRequest.SerializeToString,
            llamatrade_dot_v1_dot_strategy__pb2.GetStrategyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListStrategies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llamatrade.v1.StrategyService/ListStrategies',
            llamatrade_dot_v1_dot_strategy__pb2.ListStrategiesRequest.SerializeToString,
            llamatrade_dot_v1_dot_strategy__pb2.ListStrategiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llamatrade.v1.StrategyService/CreateStrategy',
            llamatrade_dot_v1_dot_strategy__pb2.CreateStrategyRequest.SerializeToString,
            llamatrade_dot_v1_dot_strategy__pb2.CreateStrategyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llamatrade.v1.StrategyService/UpdateStrategy',
            llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyRequest.SerializeToString,
            llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llamatrade.v1.StrategyService/DeleteStrategy',
            llamatrade_dot_v1_dot_strategy__pb2.DeleteStrategyRequest.SerializeToString,
            llamatrade_dot_v1_dot_strategy__pb2.DeleteStrategyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompileStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llamatrade.v1.StrategyService/CompileStrategy',
            llamatrade_dot_v1_dot_strategy__pb2.CompileStrategyRequest.SerializeToString,
            llamatrade_dot_v1_dot_strategy__pb2.CompileStrategyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llamatrade.v1.StrategyService/ValidateStrategy',
            llamatrade_dot_v1_dot_strategy__pb2.ValidateStrategyRequest.SerializeToString,
            llamatrade_dot_v1_dot_strategy__pb2.ValidateStrategyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListStrategyVersions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llamatrade.v1.StrategyService/ListStrategyVersions',
            llamatrade_dot_v1_dot_strategy__pb2.ListStrategyVersionsRequest.SerializeToString,
            llamatrade_dot_v1_dot_strategy__pb2.ListStrategyVersionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateStrategyStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llamatrade.v1.StrategyService/UpdateStrategyStatus',
            llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyStatusRequest.SerializeToString,
            llamatrade_dot_v1_dot_strategy__pb2.UpdateStrategyStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
