"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as abc
from google.protobuf import descriptor as descriptor
from google.protobuf import message as message
from google.protobuf.internal import containers as containers
from google.protobuf.internal import enum_type_wrapper as enum_type_wrapper
from llamatrade.v1 import common_pb2 as common_pb2
import builtins as builtins
import sys
import typing as typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: descriptor.FileDescriptor

class _StrategyStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _StrategyStatusEnumTypeWrapper(enum_type_wrapper._EnumTypeWrapper[_StrategyStatus.ValueType], builtins.type):
    DESCRIPTOR: descriptor.EnumDescriptor
    STRATEGY_STATUS_UNSPECIFIED: _StrategyStatus.ValueType  # 0
    STRATEGY_STATUS_DRAFT: _StrategyStatus.ValueType  # 1
    STRATEGY_STATUS_ACTIVE: _StrategyStatus.ValueType  # 2
    STRATEGY_STATUS_PAUSED: _StrategyStatus.ValueType  # 3
    STRATEGY_STATUS_ARCHIVED: _StrategyStatus.ValueType  # 4

class StrategyStatus(_StrategyStatus, metaclass=_StrategyStatusEnumTypeWrapper):
    """=============================================================================
    ENUMS
    =============================================================================

    Strategy status
    """

STRATEGY_STATUS_UNSPECIFIED: StrategyStatus.ValueType  # 0
STRATEGY_STATUS_DRAFT: StrategyStatus.ValueType  # 1
STRATEGY_STATUS_ACTIVE: StrategyStatus.ValueType  # 2
STRATEGY_STATUS_PAUSED: StrategyStatus.ValueType  # 3
STRATEGY_STATUS_ARCHIVED: StrategyStatus.ValueType  # 4

class _StrategyType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _StrategyTypeEnumTypeWrapper(enum_type_wrapper._EnumTypeWrapper[_StrategyType.ValueType], builtins.type):
    DESCRIPTOR: descriptor.EnumDescriptor
    STRATEGY_TYPE_UNSPECIFIED: _StrategyType.ValueType  # 0
    STRATEGY_TYPE_DSL: _StrategyType.ValueType  # 1
    """DSL-based strategy"""
    STRATEGY_TYPE_PYTHON: _StrategyType.ValueType  # 2
    """Python script"""
    STRATEGY_TYPE_TEMPLATE: _StrategyType.ValueType  # 3
    """Template-based"""

class StrategyType(_StrategyType, metaclass=_StrategyTypeEnumTypeWrapper):
    """Strategy type"""

STRATEGY_TYPE_UNSPECIFIED: StrategyType.ValueType  # 0
STRATEGY_TYPE_DSL: StrategyType.ValueType  # 1
"""DSL-based strategy"""
STRATEGY_TYPE_PYTHON: StrategyType.ValueType  # 2
"""Python script"""
STRATEGY_TYPE_TEMPLATE: StrategyType.ValueType  # 3
"""Template-based"""

@typing.final
class Strategy(message.Message):
    """=============================================================================
    MESSAGES
    =============================================================================

    Strategy definition
    """

    DESCRIPTOR: descriptor.Descriptor

    @typing.final
    class TemplateParamsEntry(message.Message):
        DESCRIPTOR: descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @typing.final
    class ParametersEntry(message.Message):
        DESCRIPTOR: descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    ID_FIELD_NUMBER: builtins.int
    TENANT_ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    DSL_CODE_FIELD_NUMBER: builtins.int
    COMPILED_JSON_FIELD_NUMBER: builtins.int
    TEMPLATE_ID_FIELD_NUMBER: builtins.int
    TEMPLATE_PARAMS_FIELD_NUMBER: builtins.int
    SYMBOLS_FIELD_NUMBER: builtins.int
    TIMEFRAME_FIELD_NUMBER: builtins.int
    PARAMETERS_FIELD_NUMBER: builtins.int
    CREATED_BY_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    BEST_SHARPE_FIELD_NUMBER: builtins.int
    BEST_RETURN_FIELD_NUMBER: builtins.int
    id: builtins.str
    tenant_id: builtins.str
    name: builtins.str
    description: builtins.str
    type: StrategyType.ValueType
    status: StrategyStatus.ValueType
    version: builtins.int
    dsl_code: builtins.str
    """DSL definition (for DSL strategies)"""
    compiled_json: builtins.str
    """Compiled strategy (JSON representation)"""
    template_id: builtins.str
    """Template info (for template strategies)"""
    timeframe: builtins.str
    created_by: builtins.str
    """Metadata"""
    @builtins.property
    def template_params(self) -> containers.ScalarMap[builtins.str, builtins.str]: ...
    @builtins.property
    def symbols(self) -> containers.RepeatedScalarFieldContainer[builtins.str]:
        """Configuration"""

    @builtins.property
    def parameters(self) -> containers.ScalarMap[builtins.str, builtins.str]: ...
    @builtins.property
    def created_at(self) -> common_pb2.Timestamp: ...
    @builtins.property
    def updated_at(self) -> common_pb2.Timestamp: ...
    @builtins.property
    def best_sharpe(self) -> common_pb2.Decimal:
        """Performance summary (from backtests)"""

    @builtins.property
    def best_return(self) -> common_pb2.Decimal: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        tenant_id: builtins.str = ...,
        name: builtins.str = ...,
        description: builtins.str = ...,
        type: StrategyType.ValueType = ...,
        status: StrategyStatus.ValueType = ...,
        version: builtins.int = ...,
        dsl_code: builtins.str = ...,
        compiled_json: builtins.str = ...,
        template_id: builtins.str = ...,
        template_params: abc.Mapping[builtins.str, builtins.str] | None = ...,
        symbols: abc.Iterable[builtins.str] | None = ...,
        timeframe: builtins.str = ...,
        parameters: abc.Mapping[builtins.str, builtins.str] | None = ...,
        created_by: builtins.str = ...,
        created_at: common_pb2.Timestamp | None = ...,
        updated_at: common_pb2.Timestamp | None = ...,
        best_sharpe: common_pb2.Decimal | None = ...,
        best_return: common_pb2.Decimal | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = typing.Literal["best_return", b"best_return", "best_sharpe", b"best_sharpe", "created_at", b"created_at", "updated_at", b"updated_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["best_return", b"best_return", "best_sharpe", b"best_sharpe", "compiled_json", b"compiled_json", "created_at", b"created_at", "created_by", b"created_by", "description", b"description", "dsl_code", b"dsl_code", "id", b"id", "name", b"name", "parameters", b"parameters", "status", b"status", "symbols", b"symbols", "template_id", b"template_id", "template_params", b"template_params", "tenant_id", b"tenant_id", "timeframe", b"timeframe", "type", b"type", "updated_at", b"updated_at", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class StrategyVersion(message.Message):
    """Strategy version for history"""

    DESCRIPTOR: descriptor.Descriptor

    @typing.final
    class ParametersEntry(message.Message):
        DESCRIPTOR: descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    STRATEGY_ID_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    DSL_CODE_FIELD_NUMBER: builtins.int
    COMPILED_JSON_FIELD_NUMBER: builtins.int
    PARAMETERS_FIELD_NUMBER: builtins.int
    CHANGE_SUMMARY_FIELD_NUMBER: builtins.int
    CREATED_BY_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    strategy_id: builtins.str
    version: builtins.int
    dsl_code: builtins.str
    compiled_json: builtins.str
    change_summary: builtins.str
    created_by: builtins.str
    @builtins.property
    def parameters(self) -> containers.ScalarMap[builtins.str, builtins.str]: ...
    @builtins.property
    def created_at(self) -> common_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        strategy_id: builtins.str = ...,
        version: builtins.int = ...,
        dsl_code: builtins.str = ...,
        compiled_json: builtins.str = ...,
        parameters: abc.Mapping[builtins.str, builtins.str] | None = ...,
        change_summary: builtins.str = ...,
        created_by: builtins.str = ...,
        created_at: common_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = typing.Literal["created_at", b"created_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["change_summary", b"change_summary", "compiled_json", b"compiled_json", "created_at", b"created_at", "created_by", b"created_by", "dsl_code", b"dsl_code", "parameters", b"parameters", "strategy_id", b"strategy_id", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class CompilationResult(message.Message):
    """DSL compilation result"""

    DESCRIPTOR: descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    COMPILED_JSON_FIELD_NUMBER: builtins.int
    ERRORS_FIELD_NUMBER: builtins.int
    WARNINGS_FIELD_NUMBER: builtins.int
    success: builtins.bool
    compiled_json: builtins.str
    @builtins.property
    def errors(self) -> containers.RepeatedCompositeFieldContainer[CompilationError]: ...
    @builtins.property
    def warnings(self) -> containers.RepeatedCompositeFieldContainer[CompilationWarning]: ...
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        compiled_json: builtins.str = ...,
        errors: abc.Iterable[CompilationError] | None = ...,
        warnings: abc.Iterable[CompilationWarning] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["compiled_json", b"compiled_json", "errors", b"errors", "success", b"success", "warnings", b"warnings"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class CompilationError(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    LINE_FIELD_NUMBER: builtins.int
    COLUMN_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    CODE_FIELD_NUMBER: builtins.int
    line: builtins.int
    column: builtins.int
    message: builtins.str
    code: builtins.str
    def __init__(
        self,
        *,
        line: builtins.int = ...,
        column: builtins.int = ...,
        message: builtins.str = ...,
        code: builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["code", b"code", "column", b"column", "line", b"line", "message", b"message"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class CompilationWarning(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    LINE_FIELD_NUMBER: builtins.int
    COLUMN_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    CODE_FIELD_NUMBER: builtins.int
    line: builtins.int
    column: builtins.int
    message: builtins.str
    code: builtins.str
    def __init__(
        self,
        *,
        line: builtins.int = ...,
        column: builtins.int = ...,
        message: builtins.str = ...,
        code: builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["code", b"code", "column", b"column", "line", b"line", "message", b"message"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class ValidationResult(message.Message):
    """DSL validation result"""

    DESCRIPTOR: descriptor.Descriptor

    VALID_FIELD_NUMBER: builtins.int
    ERRORS_FIELD_NUMBER: builtins.int
    WARNINGS_FIELD_NUMBER: builtins.int
    DETECTED_SYMBOLS_FIELD_NUMBER: builtins.int
    DETECTED_INDICATORS_FIELD_NUMBER: builtins.int
    valid: builtins.bool
    @builtins.property
    def errors(self) -> containers.RepeatedCompositeFieldContainer[CompilationError]: ...
    @builtins.property
    def warnings(self) -> containers.RepeatedCompositeFieldContainer[CompilationWarning]: ...
    @builtins.property
    def detected_symbols(self) -> containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @builtins.property
    def detected_indicators(self) -> containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        valid: builtins.bool = ...,
        errors: abc.Iterable[CompilationError] | None = ...,
        warnings: abc.Iterable[CompilationWarning] | None = ...,
        detected_symbols: abc.Iterable[builtins.str] | None = ...,
        detected_indicators: abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["detected_indicators", b"detected_indicators", "detected_symbols", b"detected_symbols", "errors", b"errors", "valid", b"valid", "warnings", b"warnings"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class GetStrategyRequest(message.Message):
    """=============================================================================
    REQUESTS & RESPONSES
    =============================================================================

    Get strategy
    """

    DESCRIPTOR: descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    STRATEGY_ID_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    strategy_id: builtins.str
    version: builtins.int
    """Optional: specific version (0 = latest)"""
    @builtins.property
    def context(self) -> common_pb2.TenantContext: ...
    def __init__(
        self,
        *,
        context: common_pb2.TenantContext | None = ...,
        strategy_id: builtins.str = ...,
        version: builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = typing.Literal["context", b"context"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["context", b"context", "strategy_id", b"strategy_id", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class GetStrategyResponse(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    STRATEGY_FIELD_NUMBER: builtins.int
    @builtins.property
    def strategy(self) -> Strategy: ...
    def __init__(
        self,
        *,
        strategy: Strategy | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = typing.Literal["strategy", b"strategy"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["strategy", b"strategy"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class ListStrategiesRequest(message.Message):
    """List strategies"""

    DESCRIPTOR: descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    STATUSES_FIELD_NUMBER: builtins.int
    TYPES_FIELD_NUMBER: builtins.int
    SEARCH_FIELD_NUMBER: builtins.int
    PAGINATION_FIELD_NUMBER: builtins.int
    SORT_FIELD_NUMBER: builtins.int
    search: builtins.str
    """Search by name/description"""
    @builtins.property
    def context(self) -> common_pb2.TenantContext: ...
    @builtins.property
    def statuses(self) -> containers.RepeatedScalarFieldContainer[StrategyStatus.ValueType]: ...
    @builtins.property
    def types(self) -> containers.RepeatedScalarFieldContainer[StrategyType.ValueType]: ...
    @builtins.property
    def pagination(self) -> common_pb2.PaginationRequest: ...
    @builtins.property
    def sort(self) -> common_pb2.SortSpec: ...
    def __init__(
        self,
        *,
        context: common_pb2.TenantContext | None = ...,
        statuses: abc.Iterable[StrategyStatus.ValueType] | None = ...,
        types: abc.Iterable[StrategyType.ValueType] | None = ...,
        search: builtins.str = ...,
        pagination: common_pb2.PaginationRequest | None = ...,
        sort: common_pb2.SortSpec | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = typing.Literal["context", b"context", "pagination", b"pagination", "sort", b"sort"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["context", b"context", "pagination", b"pagination", "search", b"search", "sort", b"sort", "statuses", b"statuses", "types", b"types"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class ListStrategiesResponse(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    STRATEGIES_FIELD_NUMBER: builtins.int
    PAGINATION_FIELD_NUMBER: builtins.int
    @builtins.property
    def strategies(self) -> containers.RepeatedCompositeFieldContainer[Strategy]: ...
    @builtins.property
    def pagination(self) -> common_pb2.PaginationResponse: ...
    def __init__(
        self,
        *,
        strategies: abc.Iterable[Strategy] | None = ...,
        pagination: common_pb2.PaginationResponse | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = typing.Literal["pagination", b"pagination"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["pagination", b"pagination", "strategies", b"strategies"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class CreateStrategyRequest(message.Message):
    """Create strategy"""

    DESCRIPTOR: descriptor.Descriptor

    @typing.final
    class TemplateParamsEntry(message.Message):
        DESCRIPTOR: descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @typing.final
    class ParametersEntry(message.Message):
        DESCRIPTOR: descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    CONTEXT_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    DSL_CODE_FIELD_NUMBER: builtins.int
    TEMPLATE_ID_FIELD_NUMBER: builtins.int
    TEMPLATE_PARAMS_FIELD_NUMBER: builtins.int
    SYMBOLS_FIELD_NUMBER: builtins.int
    TIMEFRAME_FIELD_NUMBER: builtins.int
    PARAMETERS_FIELD_NUMBER: builtins.int
    name: builtins.str
    description: builtins.str
    type: StrategyType.ValueType
    dsl_code: builtins.str
    """For DSL strategies"""
    template_id: builtins.str
    """For template strategies"""
    timeframe: builtins.str
    @builtins.property
    def context(self) -> common_pb2.TenantContext: ...
    @builtins.property
    def template_params(self) -> containers.ScalarMap[builtins.str, builtins.str]: ...
    @builtins.property
    def symbols(self) -> containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @builtins.property
    def parameters(self) -> containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        context: common_pb2.TenantContext | None = ...,
        name: builtins.str = ...,
        description: builtins.str = ...,
        type: StrategyType.ValueType = ...,
        dsl_code: builtins.str = ...,
        template_id: builtins.str = ...,
        template_params: abc.Mapping[builtins.str, builtins.str] | None = ...,
        symbols: abc.Iterable[builtins.str] | None = ...,
        timeframe: builtins.str = ...,
        parameters: abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = typing.Literal["context", b"context"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["context", b"context", "description", b"description", "dsl_code", b"dsl_code", "name", b"name", "parameters", b"parameters", "symbols", b"symbols", "template_id", b"template_id", "template_params", b"template_params", "timeframe", b"timeframe", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class CreateStrategyResponse(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    STRATEGY_FIELD_NUMBER: builtins.int
    @builtins.property
    def strategy(self) -> Strategy: ...
    def __init__(
        self,
        *,
        strategy: Strategy | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = typing.Literal["strategy", b"strategy"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["strategy", b"strategy"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class UpdateStrategyRequest(message.Message):
    """Update strategy"""

    DESCRIPTOR: descriptor.Descriptor

    @typing.final
    class ParametersEntry(message.Message):
        DESCRIPTOR: descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    CONTEXT_FIELD_NUMBER: builtins.int
    STRATEGY_ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    DSL_CODE_FIELD_NUMBER: builtins.int
    SYMBOLS_FIELD_NUMBER: builtins.int
    TIMEFRAME_FIELD_NUMBER: builtins.int
    PARAMETERS_FIELD_NUMBER: builtins.int
    CHANGE_SUMMARY_FIELD_NUMBER: builtins.int
    strategy_id: builtins.str
    name: builtins.str
    description: builtins.str
    dsl_code: builtins.str
    timeframe: builtins.str
    change_summary: builtins.str
    """For version history"""
    @builtins.property
    def context(self) -> common_pb2.TenantContext: ...
    @builtins.property
    def symbols(self) -> containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @builtins.property
    def parameters(self) -> containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        context: common_pb2.TenantContext | None = ...,
        strategy_id: builtins.str = ...,
        name: builtins.str = ...,
        description: builtins.str = ...,
        dsl_code: builtins.str = ...,
        symbols: abc.Iterable[builtins.str] | None = ...,
        timeframe: builtins.str = ...,
        parameters: abc.Mapping[builtins.str, builtins.str] | None = ...,
        change_summary: builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = typing.Literal["context", b"context"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["change_summary", b"change_summary", "context", b"context", "description", b"description", "dsl_code", b"dsl_code", "name", b"name", "parameters", b"parameters", "strategy_id", b"strategy_id", "symbols", b"symbols", "timeframe", b"timeframe"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class UpdateStrategyResponse(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    STRATEGY_FIELD_NUMBER: builtins.int
    @builtins.property
    def strategy(self) -> Strategy: ...
    def __init__(
        self,
        *,
        strategy: Strategy | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = typing.Literal["strategy", b"strategy"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["strategy", b"strategy"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class DeleteStrategyRequest(message.Message):
    """Delete strategy"""

    DESCRIPTOR: descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    STRATEGY_ID_FIELD_NUMBER: builtins.int
    strategy_id: builtins.str
    @builtins.property
    def context(self) -> common_pb2.TenantContext: ...
    def __init__(
        self,
        *,
        context: common_pb2.TenantContext | None = ...,
        strategy_id: builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = typing.Literal["context", b"context"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["context", b"context", "strategy_id", b"strategy_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class DeleteStrategyResponse(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    success: builtins.bool
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class CompileStrategyRequest(message.Message):
    """Compile DSL strategy"""

    DESCRIPTOR: descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    DSL_CODE_FIELD_NUMBER: builtins.int
    VALIDATE_ONLY_FIELD_NUMBER: builtins.int
    dsl_code: builtins.str
    validate_only: builtins.bool
    """Just validate, don't compile"""
    @builtins.property
    def context(self) -> common_pb2.TenantContext: ...
    def __init__(
        self,
        *,
        context: common_pb2.TenantContext | None = ...,
        dsl_code: builtins.str = ...,
        validate_only: builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = typing.Literal["context", b"context"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["context", b"context", "dsl_code", b"dsl_code", "validate_only", b"validate_only"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class CompileStrategyResponse(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    RESULT_FIELD_NUMBER: builtins.int
    @builtins.property
    def result(self) -> CompilationResult: ...
    def __init__(
        self,
        *,
        result: CompilationResult | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = typing.Literal["result", b"result"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["result", b"result"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class ValidateStrategyRequest(message.Message):
    """Validate strategy"""

    DESCRIPTOR: descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    STRATEGY_ID_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    strategy_id: builtins.str
    version: builtins.int
    @builtins.property
    def context(self) -> common_pb2.TenantContext: ...
    def __init__(
        self,
        *,
        context: common_pb2.TenantContext | None = ...,
        strategy_id: builtins.str = ...,
        version: builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = typing.Literal["context", b"context"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["context", b"context", "strategy_id", b"strategy_id", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class ValidateStrategyResponse(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    RESULT_FIELD_NUMBER: builtins.int
    @builtins.property
    def result(self) -> ValidationResult: ...
    def __init__(
        self,
        *,
        result: ValidationResult | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = typing.Literal["result", b"result"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["result", b"result"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class ListStrategyVersionsRequest(message.Message):
    """Get strategy versions"""

    DESCRIPTOR: descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    STRATEGY_ID_FIELD_NUMBER: builtins.int
    PAGINATION_FIELD_NUMBER: builtins.int
    strategy_id: builtins.str
    @builtins.property
    def context(self) -> common_pb2.TenantContext: ...
    @builtins.property
    def pagination(self) -> common_pb2.PaginationRequest: ...
    def __init__(
        self,
        *,
        context: common_pb2.TenantContext | None = ...,
        strategy_id: builtins.str = ...,
        pagination: common_pb2.PaginationRequest | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = typing.Literal["context", b"context", "pagination", b"pagination"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["context", b"context", "pagination", b"pagination", "strategy_id", b"strategy_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class ListStrategyVersionsResponse(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    VERSIONS_FIELD_NUMBER: builtins.int
    PAGINATION_FIELD_NUMBER: builtins.int
    @builtins.property
    def versions(self) -> containers.RepeatedCompositeFieldContainer[StrategyVersion]: ...
    @builtins.property
    def pagination(self) -> common_pb2.PaginationResponse: ...
    def __init__(
        self,
        *,
        versions: abc.Iterable[StrategyVersion] | None = ...,
        pagination: common_pb2.PaginationResponse | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = typing.Literal["pagination", b"pagination"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["pagination", b"pagination", "versions", b"versions"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class UpdateStrategyStatusRequest(message.Message):
    """Update strategy status"""

    DESCRIPTOR: descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    STRATEGY_ID_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    strategy_id: builtins.str
    status: StrategyStatus.ValueType
    @builtins.property
    def context(self) -> common_pb2.TenantContext: ...
    def __init__(
        self,
        *,
        context: common_pb2.TenantContext | None = ...,
        strategy_id: builtins.str = ...,
        status: StrategyStatus.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = typing.Literal["context", b"context"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["context", b"context", "status", b"status", "strategy_id", b"strategy_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final
class UpdateStrategyStatusResponse(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    STRATEGY_FIELD_NUMBER: builtins.int
    @builtins.property
    def strategy(self) -> Strategy: ...
    def __init__(
        self,
        *,
        strategy: Strategy | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = typing.Literal["strategy", b"strategy"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["strategy", b"strategy"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
