"""Strategy runner for live trading execution."""

import asyncio
import contextlib
import logging
import os
import time
from collections import deque
from collections.abc import AsyncIterator, Callable, Mapping, Sequence
from dataclasses import dataclass, field
from datetime import UTC, datetime, timedelta
from decimal import Decimal
from typing import Any, Literal, Protocol
from uuid import UUID

from sqlalchemy import select

from llamatrade_alpaca import (
    FillData,
    MockTradeStream,
    TradeEvent,
    TradeEventType,
    TradingClient,
    TradingStreamClient,
)
from llamatrade_alpaca import (
    StreamBar as BarData,
)
from llamatrade_proto.generated.common_pb2 import EXECUTION_MODE_LIVE, EXECUTION_MODE_PAPER
from llamatrade_proto.generated.trading_pb2 import (
    ORDER_TYPE_MARKET,
    TIME_IN_FORCE_DAY,
)
from llamatrade_runtime import Bar as CompilerBar
from llamatrade_runtime import (
    FormingBarAggregator,
    Holding,
    StrategySession,
    quantize_quantity,
)

from src.circuit_breaker import (
    CircuitBreaker,
    CircuitBreakerConfig,
    create_circuit_breaker,
)
from src.clients.portfolio_client import PortfolioLedgerClient
from src.executor.order_executor import OrderExecutor
from src.ledger_events import build_ledger_fill_payload, build_ledger_lifecycle_payload
from src.metrics import (
    record_bar_latency,
    record_bar_processed,
    record_degraded_evals,
    record_evaluation_stall,
    record_fill_processed,
    record_position_reconciliation,
    record_signal,
    record_slippage,
    record_strategy_error,
    record_sub_notional_skips,
    record_symbol_halt,
    record_trade_stream_event,
    record_trade_stream_reconnect,
    update_runner_gauge,
)
from src.models import (
    SESSION_DEGRADED_KEY,
    OrderCreate,
    RiskLimits,
    SessionDegradation,
    signal_type_to_order_side,
)
from src.risk.risk_manager import RiskManager
from src.runner.intent_capture import (
    LOOP_HAND_ROLLED,
    LOOP_RUNTIME,
    BookContext,
    CaptureObserver,
    OrderIntent,
    capture_from_env,
)
from src.runner.runtime_adapters import to_compiler_bar
from src.services.alert_service import AlertService
from src.streaming.publisher import TradingEventPublisher
from src.symbol_status import asset_halt_reason, halt_description
from src.utils.trading_hours import TradingHoursChecker, TradingHoursConfig

logger = logging.getLogger(__name__)

# Max time the all-symbols evaluation gate may stay shut before the session is reported stalled.
EVALUATION_STALL_SECONDS = int(os.getenv("TRADING_EVALUATION_STALL_SECONDS", "300"))

# Order-quantity rounding at the sizer boundary: fractional symbols round to SHARE_DECIMALS places (Alpaca accepts at most 9), else whole shares.
_FRACTIONAL_SHARES = os.getenv("TRADING_FRACTIONAL_SHARES", "true").lower() in ("1", "true", "yes")
_SHARE_DECIMALS = int(os.getenv("TRADING_SHARE_DECIMALS", "9"))
_MIN_ORDER_NOTIONAL = Decimal(os.getenv("TRADING_MIN_ORDER_NOTIONAL", "1"))

# Trade-stream supervisor restart backoff (see StrategyRunner._trade_stream_loop).
_TRADE_STREAM_RESTART_BASE_DELAY_S = 1.0
_TRADE_STREAM_RESTART_MAX_DELAY_S = 60.0


@dataclass
class Signal:
    """Trading signal generated by strategy."""

    type: str  # "buy", "sell", "short", "cover"
    symbol: str
    quantity: Decimal
    price: Decimal
    timestamp: datetime = field(default_factory=lambda: datetime.now(UTC))


@dataclass
class RunnerPosition:
    """Current position in a symbol."""

    symbol: str
    side: str  # "long", "short", "flat"
    quantity: Decimal
    entry_price: Decimal
    entry_date: datetime


def _realized_pnl(
    *, entry_price: Decimal, exit_price: Decimal, qty: Decimal, is_long: bool
) -> Decimal:
    """Realized P&L for a closed position (exact Decimal)."""
    return (exit_price - entry_price if is_long else entry_price - exit_price) * qty


def _book_context(holdings: Mapping[str, Holding], equity: float) -> BookContext:
    """The capture's view of the book an evaluation is about to size against."""
    return BookContext(equity=equity, holdings={s: h.quantity for s, h in holdings.items()})


@dataclass
class RunnerConfig:
    """Configuration for strategy runner."""

    tenant_id: UUID
    execution_id: UUID
    strategy_id: UUID
    symbols: list[str]
    timeframe: str
    warmup_bars: int = 50
    risk_limits: RiskLimits | None = None
    mode: int = EXECUTION_MODE_PAPER  # ExecutionMode proto value: PAPER=1, LIVE=2

    # Ledger identity from the funded execution; None = unfunded session, no ledger events. See portfolio-ledger.md.
    sleeve_id: UUID | None = None
    account_id: UUID | None = None

    # Alert once when every-symbol bar sync has been blocked this long
    evaluation_stall_seconds: int = EVALUATION_STALL_SECONDS

    # Order-quantity rounding at the sizer boundary (see quantize_quantity).
    fractional_shares: bool = _FRACTIONAL_SHARES
    share_decimals: int = _SHARE_DECIMALS
    min_order_notional: Decimal = _MIN_ORDER_NOTIONAL

    # Probe each subscribed symbol's broker asset status on the reconciliation tick
    symbol_lifecycle_check_enabled: bool = True

    position_reconciliation_enabled: bool = True
    position_reconciliation_interval_seconds: int = 300  # 5 minutes
    position_drift_auto_correct_threshold_pct: float = 5.0  # Auto-correct if < 5% drift
    position_drift_alert_threshold_pct: float = 10.0  # Alert if >= 10% drift

    # Idempotent ledger re-publish drain; window is measured on the order's terminal transition (updated_at), so it must exceed the longest tolerable publish outage.
    ledger_republish_interval_seconds: int = 120
    ledger_republish_window_seconds: int = 3600

    enforce_trading_hours: bool = True  # Skip signals outside market hours
    allow_premarket: bool = False  # Allow trading during pre-market (4 AM - 9:30 AM ET)
    allow_afterhours: bool = False  # Allow trading during after-hours (4 PM - 8 PM ET)


class BarStream(Protocol):
    """The live bar-stream surface the runner drives.

    Satisfied structurally by ``BarStreamClient`` (per-tenant Alpaca WebSocket),
    ``ServiceBarStream`` (shared market-data fan-out), and ``MockBarStream`` (tests),
    so a new stream source is pluggable without widening a concrete union.
    """

    @property
    def connected(self) -> bool: ...
    async def connect(self) -> bool: ...
    async def subscribe(self, symbols: list[str]) -> bool: ...
    def stream(self) -> AsyncIterator[BarData]: ...
    async def disconnect(self) -> None: ...


class StrategyFunction(Protocol):
    """Protocol for compiled strategy functions.

    The bars parameter accepts any sequence type (list, deque, etc.)
    to allow for efficient O(1) append operations in the runner.
    """

    def __call__(
        self,
        symbol: str,
        bars: Sequence[BarData],
        position: RunnerPosition | None,
        equity: float,
    ) -> Signal | None: ...


class StrategyRunner:
    """Runs a compiled strategy against real-time bar data.

    The runner:
    1. Subscribes to bar stream for strategy symbols
    2. Accumulates bar history per symbol
    3. Invokes strategy function on each new bar
    4. Routes generated signals through risk checks and order execution
    5. Periodically syncs equity from Alpaca account
    """

    def __init__(
        self,
        config: RunnerConfig,
        strategy_fn: StrategyFunction | None,
        bar_stream: BarStream,
        trade_stream: TradingStreamClient | MockTradeStream,
        order_executor: OrderExecutor,
        risk_manager: RiskManager,
        alpaca_client: TradingClient | None = None,
        alert_service: AlertService | None = None,
        strategy_name: str = "Unknown Strategy",
        circuit_breaker_config: CircuitBreakerConfig | None = None,
        ledger_publisher: TradingEventPublisher | None = None,
        portfolio_client: PortfolioLedgerClient | None = None,
        session: StrategySession | None = None,
        trade_stream_factory: Callable[[], TradingStreamClient | MockTradeStream] | None = None,
    ):
        # One eval source: the merged-symbol session (prod) or a per-symbol strategy_fn (tests).
        if session is None and strategy_fn is None:
            raise ValueError("StrategyRunner requires either a session or a strategy_fn")
        self.config = config
        self.strategy_fn = strategy_fn
        self._session = session
        # Folds the one-minute stream into one forming bar per symbol per strategy period so live indicators read the same grid a backtest does; seeded from the warm-up preload's in-progress bar.
        self._aggregator = FormingBarAggregator(
            seed=session.last_bars() if session is not None else None
        )
        # Session-path eval buffers: latest bar + timestamp per symbol; last period evaluated.
        self._latest_bars: dict[str, CompilerBar] = {}
        self._latest_ts: dict[str, datetime] = {}
        self._last_evaluated_ts: datetime | None = None
        # Last observed cumulative session counters, to emit deltas rather than absolutes.
        self._last_degraded_eval_count = 0
        self._last_sub_notional_skip_count = 0
        # Evaluation-gate health: when it last opened, and whether the current stall episode was already alerted (one alert per episode).
        self._last_gate_open_at: datetime | None = None
        self._stall_alerted = False
        # Symbols the broker no longer lists as active and tradable.
        self._halted_symbols: set[str] = set()
        self.bar_stream = bar_stream
        self.order_executor = order_executor
        self.risk_manager = risk_manager
        self.alpaca_client = alpaca_client
        self.alerts = alert_service
        self.strategy_name = strategy_name
        self.trade_stream = trade_stream
        # Rebuilds a fresh trade-update client when the supervised fill stream gives up (resets the reconnect-attempt counter); None in tests.
        self._trade_stream_factory = trade_stream_factory
        self.ledger_publisher = ledger_publisher
        self.portfolio_client = portfolio_client

        self._running = False
        self._paused = False
        # deque with maxlen for O(1) append and automatic size limiting
        max_history_size = config.warmup_bars + 100
        self._bar_history: dict[str, deque[BarData]] = {
            s: deque(maxlen=max_history_size) for s in config.symbols
        }
        self._positions: dict[str, RunnerPosition] = {}
        self._equity = Decimal("100000")  # Default, will be synced from Alpaca/sleeve
        self._free_cash: Decimal | None = None  # Sleeve free cash (book of record)
        self._equity_sync_task: asyncio.Task[None] | None = None
        self._position_sync_task: asyncio.Task[None] | None = None
        self._trade_stream_task: asyncio.Task[None] | None = None
        self._ledger_republish_task: asyncio.Task[None] | None = None

        # Pending (submitted, unfilled) orders: client_order_id -> signal, for fill-time updates.
        self._pending_orders: dict[str, Signal] = {}

        # Cumulative filled qty already applied to the local book per client_order_id, so partial + terminal fill events book only their delta.
        self._applied_fill_qty: dict[str, Decimal] = {}
        # Recently-terminal orders — a replayed fill event for one must not re-apply.
        self._terminal_order_ids: deque[str] = deque(maxlen=512)

        # Opt-in: drive the live loop through the shared StrategyRuntime (default off; hand-rolled loop is the production path).
        self._use_runtime_loop = os.getenv("TRADING_USE_RUNTIME_LOOP", "").lower() in (
            "1",
            "true",
            "yes",
        )
        # Which loop start() dispatches on; the intent capture (off unless TRADING_INTENT_CAPTURE_DIR is set) labels its records with it.
        self._runtime_loop_selected = self._use_runtime_loop and session is not None
        self._intent_capture = capture_from_env(
            config.execution_id,
            LOOP_RUNTIME if self._runtime_loop_selected else LOOP_HAND_ROLLED,
        )

        self._circuit_breaker = create_circuit_breaker(
            tenant_id=config.tenant_id,
            session_id=config.execution_id,
            callback=alert_service,
            starting_equity=self._equity,
            config=circuit_breaker_config,
        )

        self._trading_hours: TradingHoursChecker | None = None
        if config.enforce_trading_hours:
            trading_hours_config = TradingHoursConfig(
                allow_premarket=config.allow_premarket,
                allow_afterhours=config.allow_afterhours,
            )
            self._trading_hours = TradingHoursChecker(trading_hours_config)

        self._signals_generated = 0
        self._orders_submitted = 0
        self._orders_rejected = 0
        self._fills_processed = 0

        self._last_reconciliation_time: datetime | None = None
        self._reconciliation_error_count: int = 0

    @property
    def running(self) -> bool:
        """Check if runner is active."""
        return self._running

    @property
    def paused(self) -> bool:
        """Check if runner is paused."""
        return self._paused

    @property
    def positions(self) -> dict[str, RunnerPosition]:
        """Get current positions."""
        return self._positions.copy()

    @property
    def metrics(self) -> dict[str, Any]:
        """Get runner metrics."""
        cb_status = self._circuit_breaker.get_status()
        return {
            "signals_generated": self._signals_generated,
            "orders_submitted": self._orders_submitted,
            "orders_rejected": self._orders_rejected,
            "fills_processed": self._fills_processed,
            "pending_orders": len(self._pending_orders),
            "positions": len(self._positions),
            "bar_history_sizes": {s: len(bars) for s, bars in self._bar_history.items()},
            "circuit_breaker_state": cb_status.state.value,
            "circuit_breaker_triggered_at": (
                cb_status.triggered_at.isoformat() if cb_status.triggered_at else None
            ),
            "circuit_breaker_reason": (
                cb_status.triggered_reason.value if cb_status.triggered_reason else None
            ),
            "last_reconciliation_time": (
                self._last_reconciliation_time.isoformat()
                if self._last_reconciliation_time
                else None
            ),
            "reconciliation_error_count": self._reconciliation_error_count,
            "trade_stream_connected": self.trade_stream.connected,
            "halted_symbols": sorted(self._halted_symbols),
            "evaluation_stalled": self._stall_alerted,
        }

    @property
    def last_reconciliation_time(self) -> datetime | None:
        """Get last successful reconciliation time."""
        return self._last_reconciliation_time

    @property
    def reconciliation_error_count(self) -> int:
        """Get count of consecutive reconciliation errors."""
        return self._reconciliation_error_count

    @property
    def circuit_breaker(self) -> CircuitBreaker:
        """Get the circuit breaker instance."""
        return self._circuit_breaker

    @property
    def circuit_breaker_triggered(self) -> bool:
        """Check if circuit breaker is triggered."""
        return self._circuit_breaker.is_triggered

    async def start(self) -> None:
        """Start the strategy runner."""
        if self._running:
            logger.warning("Runner already started")
            return

        logger.info(f"Starting strategy runner for execution {self.config.execution_id}")

        # Sync equity before starting; positions are recovered from the broker (source of truth) via the periodic reconciliation loop below.
        await self._sync_equity()

        # Reconcile orders a prior crash left PENDING with no broker id: adopt those the broker placed, reject those it never received. Best-effort — a hiccup must not block session start.
        try:
            recovered = await self.order_executor.recover_stranded_orders(
                self.config.tenant_id, self.config.execution_id
            )
            if recovered:
                logger.info("Recovered %d stranded order(s) at startup", recovered)
        except Exception as e:
            logger.warning("Stranded-order recovery failed at startup: %s", e)

        # Re-emit ledger events for recently-terminal orders whose original publish may have failed before a crash (4A safety net); idempotent at the ledger.
        if self.config.sleeve_id is not None:
            try:
                republished = await self.order_executor.republish_ledger_for_terminal_orders(
                    self.config.tenant_id,
                    self.config.execution_id,
                    since=datetime.now(UTC) - timedelta(days=1),
                )
                if republished:
                    logger.info("Re-published ledger events for %d terminal order(s)", republished)
            except Exception as e:
                logger.warning("Ledger re-publish at startup failed: %s", e)

        if not self.bar_stream.connected:
            if not await self.bar_stream.connect():
                if self.alerts:
                    await self.alerts.on_connection_lost(
                        tenant_id=self.config.tenant_id,
                        session_id=self.config.execution_id,
                        service="bar_stream",
                    )
                raise RuntimeError("Failed to connect to bar stream")

        if not await self.bar_stream.subscribe(self.config.symbols):
            raise RuntimeError("Failed to subscribe to symbols")

        if not self.trade_stream.connected:
            if not await self.trade_stream.connect():
                if self.alerts:
                    await self.alerts.on_connection_lost(
                        tenant_id=self.config.tenant_id,
                        session_id=self.config.execution_id,
                        service="trade_stream",
                    )
                raise RuntimeError("Failed to connect to trade stream")

        if not await self.trade_stream.subscribe():
            raise RuntimeError("Failed to subscribe to trade updates")

        logger.info("Connected to trade stream for fill updates")

        self._running = True
        # Staleness is measured from here until the gate first opens.
        self._last_gate_open_at = datetime.now(UTC)

        mode: Literal["live", "paper"] = (
            "live" if self.config.mode == EXECUTION_MODE_LIVE else "paper"
        )

        if self.alerts:
            await self.alerts.on_session_started(
                tenant_id=self.config.tenant_id,
                session_id=self.config.execution_id,
                strategy_name=self.strategy_name,
                mode=mode,
            )

        self._equity_sync_task = asyncio.create_task(self._equity_sync_loop())

        if self.config.position_reconciliation_enabled and self.alpaca_client:
            self._position_sync_task = asyncio.create_task(self._position_sync_loop())

        self._trade_stream_task = asyncio.create_task(self._trade_stream_loop())

        if self.config.sleeve_id is not None:
            self._ledger_republish_task = asyncio.create_task(self._ledger_republish_loop())

        try:
            if self._runtime_loop_selected:
                await self._run_via_runtime()
            else:
                async for bar in self.bar_stream.stream():
                    if not self._running:
                        break

                    if self._paused:
                        continue

                    await self._process_bar(bar)

        except asyncio.CancelledError:
            logger.info("Runner cancelled")
        except Exception as e:
            logger.error(f"Runner error: {e}")
            if self.alerts:
                await self.alerts.on_session_error(
                    tenant_id=self.config.tenant_id,
                    session_id=self.config.execution_id,
                    error=str(e),
                )
            raise
        finally:
            self._running = False
            self._drain_session_counters()
            if self._trade_stream_task:
                self._trade_stream_task.cancel()
                try:
                    await self._trade_stream_task
                except asyncio.CancelledError:
                    pass
            if self._equity_sync_task:
                self._equity_sync_task.cancel()
                try:
                    await self._equity_sync_task
                except asyncio.CancelledError:
                    pass
            if self._position_sync_task:
                self._position_sync_task.cancel()
                try:
                    await self._position_sync_task
                except asyncio.CancelledError:
                    pass
            if self._ledger_republish_task:
                self._ledger_republish_task.cancel()
                try:
                    await self._ledger_republish_task
                except asyncio.CancelledError:
                    pass
            logger.info("Runner stopped")

    async def stop(self, reason: str | None = None) -> None:
        """Stop the strategy runner."""
        logger.info(f"Stopping runner for execution {self.config.execution_id}")
        self._running = False

        await self.bar_stream.disconnect()
        await self.trade_stream.disconnect()

        if self._trade_stream_task and not self._trade_stream_task.done():
            self._trade_stream_task.cancel()
            try:
                await self._trade_stream_task
            except asyncio.CancelledError:
                pass

        if self.alerts:
            await self.alerts.on_session_stopped(
                tenant_id=self.config.tenant_id,
                session_id=self.config.execution_id,
                reason=reason,
            )

    def pause(self) -> None:
        """Pause signal generation (continues receiving bars)."""
        logger.info(f"Pausing runner for execution {self.config.execution_id}")
        self._paused = True

    def resume(self) -> None:
        """Resume signal generation."""
        logger.info(f"Resuming runner for execution {self.config.execution_id}")
        self._paused = False

    async def reset_circuit_breaker(self, force: bool = False) -> bool:
        """Reset the circuit breaker to allow trading.

        Args:
            force: If True, reset even if cooldown hasn't elapsed.

        Returns:
            True if reset was successful.
        """
        success = await self._circuit_breaker.reset(force=force)
        if success:
            logger.info(f"Circuit breaker reset for execution {self.config.execution_id}")
        return success

    async def trigger_circuit_breaker(self, reason: str | None = None) -> None:
        """Manually trigger the circuit breaker.

        Args:
            reason: Optional reason for manual trigger.
        """
        await self._circuit_breaker.manual_trigger(reason)
        self.pause()

    async def _run_via_runtime(self) -> None:
        """Drive the live session through the shared StrategyRuntime (async stream loop).

        Reuses the runner's hardened submit (``_process_signal``), fill-maintained state, and bar
        stream — only the loop is unified with backtest. Off by default (see ``_use_runtime_loop``).
        """
        from llamatrade_runtime import StrategyRuntime

        from src.runner.runtime_adapters import LedgerPortfolio, RunnerExecution, StreamBarFeed

        assert self._session is not None
        feed = StreamBarFeed(
            self.bar_stream,
            self.config.symbols,
            aggregator=self._aggregator,
            gate=self._live_gate,
            on_bar=self._store_live_bar,
            is_running=lambda: self._running,
        )
        portfolio = LedgerPortfolio(self._runtime_holdings, self._live_equity)
        execution = RunnerExecution(self._submit_runtime_order)
        # The tick observer closes each evaluation's capture record, including empty ones.
        observer = (
            CaptureObserver(self._intent_capture) if self._intent_capture is not None else None
        )
        runtime = StrategyRuntime(self._session, portfolio, execution, observer=observer)
        await runtime.stream(feed, should_stop=lambda: not self._running)

    def _live_gate(self, ts: datetime) -> bool:
        """Whether the runtime feed may evaluate+trade this period (pause / market-open / breaker).

        Pause skips the period (the feed keeps iterating); only a stop breaks the feed.
        """
        if self._paused:
            return False
        if self._trading_hours and not self._trading_hours.is_market_open(ts):
            return False
        return self._circuit_breaker.can_trade()

    def _store_live_bar(self, bar: BarData) -> None:
        """Per-bar side effects for the runtime path — mirrors ``_process_bar``'s history + latency."""
        latency = (datetime.now(UTC) - bar.timestamp).total_seconds()
        if latency > 0:
            record_bar_latency(latency)
        if bar.symbol in self._bar_history:
            self._bar_history[bar.symbol].append(bar)
        # Same gate bookkeeping as the hand-rolled path, so stall detection applies here too.
        self._latest_ts[bar.symbol] = bar.timestamp
        if all(self._latest_ts.get(s) == bar.timestamp for s in self.config.symbols):
            self._note_gate_open()

    def _live_holdings(self) -> dict[str, Holding]:
        return {
            s: Holding(s, float(p.quantity)) for s, p in self._positions.items() if p.quantity > 0
        }

    def _runtime_holdings(self) -> dict[str, Holding]:
        """Holdings for a runtime tick, staging the book its evaluation will size against."""
        holdings = self._live_holdings()
        if self._intent_capture is not None:
            self._intent_capture.stage_book(_book_context(holdings, self._live_equity()))
        return holdings

    def _live_equity(self) -> float:
        return float(self._equity)

    async def _submit_runtime_order(
        self, side: str, symbol: str, quantity: float, price: float, ts: datetime
    ) -> None:
        """Build a Signal from a runtime order and submit it through the hardened path."""
        if self._intent_capture is not None:
            self._intent_capture.stage(OrderIntent(symbol, side, quantity, price))
        signal = Signal(
            type=side,
            symbol=symbol,
            quantity=Decimal(str(quantity)),
            price=Decimal(str(price)),
            timestamp=ts,
        )
        self._signals_generated += 1
        record_signal(signal.type)
        await self._process_signal(signal)

    async def _process_bar(self, bar: BarData) -> None:
        """Process an incoming bar."""
        start_time = time.perf_counter()
        symbol = bar.symbol

        # Bar receive latency (bar ts -> now); the shared lib stream is metrics-agnostic.
        latency = (datetime.now(UTC) - bar.timestamp).total_seconds()
        if latency > 0:
            record_bar_latency(latency)

        if symbol not in self._bar_history:
            return

        self._bar_history[symbol].append(bar)

        # Production path: the shared merged-symbol session evaluates all symbols together.
        if self._session is not None:
            try:
                await self._evaluate_session(bar)
            except Exception as e:
                logger.error(f"Strategy error for {symbol}: {e}")
                record_strategy_error("signal_generation")
                await self._circuit_breaker.record_api_error(str(e))
                if self.alerts:
                    await self.alerts.on_strategy_error(
                        tenant_id=self.config.tenant_id,
                        session_id=self.config.execution_id,
                        error=f"Error processing {symbol}: {e}",
                    )
            finally:
                record_bar_processed(time.perf_counter() - start_time)
            return

        # Legacy per-symbol path (tests / strategy_fn). Skip if warming up.
        if len(self._bar_history[symbol]) < self.config.warmup_bars:
            logger.debug(
                f"Warming up {symbol}: {len(self._bar_history[symbol])}/{self.config.warmup_bars}"
            )
            return

        if self._trading_hours and not self._trading_hours.is_market_open(bar.timestamp):
            logger.debug(
                f"Market closed at {bar.timestamp}, skipping signal generation for {symbol}"
            )
            return

        position = self._positions.get(symbol)

        if not self._circuit_breaker.can_trade():
            logger.debug(f"Circuit breaker triggered, skipping signal generation for {symbol}")
            return

        try:
            assert self.strategy_fn is not None  # guaranteed when session is None
            signal = self.strategy_fn(
                symbol=symbol,
                bars=self._bar_history[symbol],
                position=position,
                equity=float(self._equity),  # strategy engine is float-native
            )

            if signal:
                self._signals_generated += 1
                record_signal(signal.type)
                await self._process_signal(signal)

        except Exception as e:
            logger.error(f"Strategy error for {symbol}: {e}")
            record_strategy_error("signal_generation")
            await self._circuit_breaker.record_api_error(str(e))
            if self.alerts:
                await self.alerts.on_strategy_error(
                    tenant_id=self.config.tenant_id,
                    session_id=self.config.execution_id,
                    error=f"Error processing {symbol}: {e}",
                )
        finally:
            duration = time.perf_counter() - start_time
            record_bar_processed(duration)

    async def _evaluate_session(self, bar: BarData) -> None:
        """Merged-symbol evaluation via the shared StrategySession.

        Folds the bar into its symbol's forming period bar and evaluates the strategy **once per
        bar period**, only when every subscribed symbol has produced a bar for that timestamp.
        This gives the session a complete cross-symbol snapshot (so conditions like
        "hold TLT when RSI(SPY) > 70" work) and a single portfolio-level rebalance, over the same
        one-bar-per-period history a backtest of the strategy reads.
        """
        assert self._session is not None
        self._latest_bars[bar.symbol] = self._aggregator.update(bar.symbol, to_compiler_bar(bar))
        self._latest_ts[bar.symbol] = bar.timestamp
        ts = bar.timestamp

        # Wait until every subscribed symbol has this period's bar.
        missing = [s for s in self.config.symbols if self._latest_ts.get(s) != ts]
        if missing:
            await self._check_evaluation_stall(missing)
            return
        self._note_gate_open()

        # Evaluate each period at most once.
        if ts == self._last_evaluated_ts:
            return
        self._last_evaluated_ts = ts

        if self._trading_hours and not self._trading_hours.is_market_open(ts):
            return
        if not self._circuit_breaker.can_trade():
            return

        holdings = {
            s: Holding(s, float(p.quantity)) for s, p in self._positions.items() if p.quantity > 0
        }
        # Offload the strategy/indicator math (NumPy, releases the GIL) so it never blocks the fill/equity event loop; safe because this session is owned solely by this runner and evaluated serially.
        orders = await asyncio.to_thread(
            self._session.evaluate, self._latest_bars, holdings, float(self._equity)
        )

        self._drain_session_counters()

        if self._intent_capture is not None:
            self._intent_capture.record(
                ts,
                [OrderIntent(o.symbol, o.side, o.quantity, o.price) for o in orders],
                _book_context(holdings, float(self._equity)),
            )

        for order in orders:
            signal = Signal(
                type=order.side,
                symbol=order.symbol,
                quantity=Decimal(str(order.quantity)),  # compiler is float-native
                price=Decimal(str(order.price)),
                timestamp=ts,
            )
            self._signals_generated += 1
            record_signal(signal.type)
            await self._process_signal(signal)

    def _drain_session_counters(self) -> None:
        """Emit the increments of the session's degraded-eval and sub-notional-skip counters.

        Both are cumulative on the session and carry no metric labels, so a strategy that
        silently produces "no signal" (stale/missing indicator data) or whose orders keep
        falling under the broker's notional floor is observable at the fleet level. Called
        from both live loops: per evaluation on the hand-rolled path, on the equity-sync
        tick (which covers the runtime loop) and once more when the runner winds down.
        """
        if self._session is None:
            return
        degraded = self._session.degraded_eval_count
        if degraded > self._last_degraded_eval_count:
            record_degraded_evals(degraded - self._last_degraded_eval_count)
            self._last_degraded_eval_count = degraded
        skipped = self._session.sub_notional_skip_count
        if skipped > self._last_sub_notional_skip_count:
            record_sub_notional_skips(skipped - self._last_sub_notional_skip_count)
            self._last_sub_notional_skip_count = skipped

    def _note_gate_open(self) -> None:
        """Record that every subscribed symbol has the current period's bar."""
        self._last_gate_open_at = datetime.now(UTC)
        if self._stall_alerted:
            logger.info("Evaluation gate recovered for execution %s", self.config.execution_id)
            self._stall_alerted = False

    def _stalled_symbols(self) -> list[str]:
        """Symbols holding the evaluation gate shut (behind the newest bar period).

        With no per-symbol lag the whole feed is stale, so every subscribed
        symbol is reported.
        """
        if not self._latest_ts:
            return list(self.config.symbols)
        newest = max(self._latest_ts.values())
        behind = [s for s in self.config.symbols if self._latest_ts.get(s) != newest]
        return behind or list(self.config.symbols)

    async def _check_evaluation_stall(self, missing: list[str]) -> None:
        """Alert once per episode when the all-symbols gate stays shut too long.

        One symbol whose bars stop arriving freezes the whole strategy: it keeps
        running but never evaluates, rebalances or trades, which is otherwise
        indistinguishable from "the strategy chose to do nothing".
        """
        # Only the merged-symbol session path has an all-symbols gate to watch.
        if self._session is None:
            return
        now = datetime.now(UTC)
        # A paused session, or a closed market, is not a stall — restart the clock.
        if self._paused or (self._trading_hours and not self._trading_hours.is_market_open(now)):
            self._last_gate_open_at = now
            return
        since = self._last_gate_open_at
        if since is None:
            return
        stale_seconds = (now - since).total_seconds()
        if stale_seconds < self.config.evaluation_stall_seconds or self._stall_alerted:
            return

        self._stall_alerted = True
        record_evaluation_stall()
        logger.warning(
            "Evaluation stalled for execution %s: no complete bar set for %.0fs (waiting on %s)",
            self.config.execution_id,
            stale_seconds,
            ", ".join(missing),
        )
        if self.alerts:
            await self.alerts.on_evaluation_stalled(
                tenant_id=self.config.tenant_id,
                session_id=self.config.execution_id,
                symbols=missing,
                stale_seconds=stale_seconds,
            )

    async def _check_symbol_lifecycle(self) -> None:
        """Flag subscribed symbols the broker stopped listing as active and tradable.

        Nothing is force-closed: the session is marked degraded and the user is
        alerted to decide, since liquidating a delisted holding is their call.
        Each symbol is reported once.
        """
        if not self.alpaca_client or not self.config.symbol_lifecycle_check_enabled:
            return

        for symbol in self.config.symbols:
            if symbol in self._halted_symbols:
                continue
            try:
                asset = await self.alpaca_client.get_asset(symbol)
            except Exception as e:
                logger.warning("Asset status check failed for %s: %s", symbol, e)
                continue
            reason = asset_halt_reason(asset)
            if reason is None:
                continue

            self._halted_symbols.add(symbol)
            record_symbol_halt(reason)
            logger.warning(
                "Symbol %s is %s; marking execution %s degraded",
                symbol,
                halt_description(reason),
                self.config.execution_id,
            )
            await self._mark_session_degraded(reason)
            if self.alerts:
                await self.alerts.on_symbol_not_tradable(
                    tenant_id=self.config.tenant_id,
                    session_id=self.config.execution_id,
                    symbol=symbol,
                    reason=reason,
                    description=halt_description(reason),
                )

    async def _mark_session_degraded(self, reason: str) -> None:
        """Persist the degradation marker on the session row for session reads.

        Best-effort: the alert is the primary notification, so a write failure
        must not take the runner down.
        """
        from llamatrade_db import get_session_maker
        from llamatrade_db.models.trading import TradingSession
        from llamatrade_db.session import bind_tenant_guc

        symbols = sorted(self._halted_symbols)
        marker = SessionDegradation(
            reason=reason,
            symbols=symbols,
            detail=f"{', '.join(symbols)} {halt_description(reason)}",
            detected_at=datetime.now(UTC),
        )
        try:
            async with get_session_maker()() as db:
                bind_tenant_guc(db, self.config.tenant_id)
                session = await db.scalar(
                    select(TradingSession).where(
                        TradingSession.id == self.config.execution_id,
                        TradingSession.tenant_id == self.config.tenant_id,
                    )
                )
                if session is None:
                    return
                session.config = {
                    **(session.config or {}),
                    SESSION_DEGRADED_KEY: marker.model_dump(mode="json"),
                }
                await db.commit()
        except Exception as e:
            logger.warning(
                "Failed to persist degraded marker for execution %s: %s",
                self.config.execution_id,
                e,
            )

    async def _process_signal(self, signal: Signal) -> None:
        """Process a trading signal."""
        logger.info(f"Signal: {signal.type} {signal.quantity} {signal.symbol}")

        # Double-check circuit breaker (may have triggered since bar processing)
        if not self._circuit_breaker.can_trade():
            logger.warning(f"Circuit breaker triggered, rejecting signal for {signal.symbol}")
            return

        # Ledger accounting is long-only: lots have no short side, so a short would be silently miscounted — reject rather than corrupt.
        if signal.type in ("short", "cover") and self.config.sleeve_id is not None:
            logger.warning(
                f"Rejecting {signal.type} signal for {signal.symbol}: "
                "short selling is not supported for sleeve-attributed sessions"
            )
            record_strategy_error("short_unsupported_for_sleeve")
            return

        # Sleeve free-cash fit: scale buys down to what the sleeve can afford rather than overdraw (mirrors portfolio sizing.fit_to_free_cash).
        if signal.type in ("buy", "cover") and self._free_cash is not None and signal.price > 0:
            affordable_qty = self._free_cash / signal.price
            if affordable_qty <= 0:
                logger.info(f"Skipping {signal.type} {signal.symbol}: sleeve free cash exhausted")
                return
            if signal.quantity > affordable_qty:
                logger.info(
                    f"Fitting {signal.symbol} buy to sleeve free cash: "
                    f"{signal.quantity:.4f} → {affordable_qty:.4f}"
                )
                signal.quantity = affordable_qty

        # Round to a tradable share increment (shared sizer) so live matches a quantizing backtest, then re-check the notional floor since rounding can drop an order below the broker minimum.
        rounded = Decimal(
            str(
                quantize_quantity(
                    float(signal.quantity),
                    fractional=self.config.fractional_shares,
                    decimals=self.config.share_decimals,
                )
            )
        )
        if rounded <= 0:
            logger.info(f"Skipping {signal.type} {signal.symbol}: rounds to zero shares")
            record_sub_notional_skips(1)
            return
        if signal.price > 0 and rounded * signal.price < self.config.min_order_notional:
            logger.info(
                f"Skipping {signal.type} {signal.symbol}: notional "
                f"${rounded * signal.price:.2f} below floor ${self.config.min_order_notional:.2f}"
            )
            record_sub_notional_skips(1)
            return
        signal.quantity = rounded

        order = self._signal_to_order(signal)

        # Submit order via the OrderExecutor (DB-backed, broker is source of truth).
        try:
            # Single risk check with full context (sleeve + session), reusing the signal's evaluation price so no market-data RPC is needed; the result is passed into submit_order so it is not re-run there.
            risk_result = await self.risk_manager.check_order(
                tenant_id=self.config.tenant_id,
                symbol=signal.symbol,
                side=signal.type,
                qty=signal.quantity,
                order_type="market",
                session_id=self.config.execution_id,
                sleeve_id=self.config.sleeve_id,
                reference_price=signal.price if signal.price > 0 else None,
            )

            if not risk_result.passed:
                logger.warning(f"Signal rejected by risk: {risk_result.violations}")
                self._orders_rejected += 1
                if self.alerts:
                    await self.alerts.on_risk_breach(
                        tenant_id=self.config.tenant_id,
                        session_id=self.config.execution_id,
                        breach_type="signal_rejected",
                        details={
                            "symbol": signal.symbol,
                            "signal_type": signal.type,
                            "quantity": float(signal.quantity),
                            "violations": risk_result.violations,
                        },
                    )
                return

            # signal_timestamp makes the client_order_id deterministic, so a retry after a crash collapses onto the same broker order.
            result = await self.order_executor.submit_order(
                tenant_id=self.config.tenant_id,
                session_id=self.config.execution_id,
                order=order,
                signal_timestamp=signal.timestamp,
                risk_result=risk_result,
            )
            self._orders_submitted += 1
            logger.info(f"Order submitted: {result.id} status={result.status}")

            # Track pending order for fill-based position update
            if result.client_order_id:
                self._pending_orders[result.client_order_id] = signal

            # Position updates come from trade-stream fill events (broker reality), not here.

        except Exception as e:
            logger.error(f"Order submission failed: {e}")
            self._orders_rejected += 1
            record_strategy_error("order_submission")
            await self._circuit_breaker.record_order_error(str(e))

    def _signal_to_order(self, signal: Signal) -> OrderCreate:
        """Convert a signal to an order request."""
        side = signal_type_to_order_side(signal.type)

        return OrderCreate(
            symbol=signal.symbol,
            side=side,
            qty=signal.quantity,
            order_type=ORDER_TYPE_MARKET,
            time_in_force=TIME_IN_FORCE_DAY,
            sleeve_id=self.config.sleeve_id,
            account_id=self.config.account_id,
            est_price=signal.price if signal.price > 0 else None,
        )

    def set_equity(self, equity: Decimal) -> None:
        """Update equity value (called by external sync)."""
        self._equity = equity

    def sync_position(self, symbol: str, position: RunnerPosition | None) -> None:
        """Sync position from external source (e.g., Alpaca)."""
        if position:
            self._positions[symbol] = position
        elif symbol in self._positions:
            del self._positions[symbol]

    async def _sync_equity(self) -> None:
        """Sync equity — from the sleeve when ledger execution is on, else Alpaca.

        Sleeve equity is what fixes multi-strategy double-counting: two
        runners on one brokerage account each size against their own
        allocation instead of the whole account.
        """
        if await self._sync_sleeve_equity():
            return

        if not self.alpaca_client:
            return

        try:
            account = await self.alpaca_client.get_account()
            self._equity = account.equity
            logger.debug(f"Synced equity: ${self._equity:,.2f}")

            self._circuit_breaker.update_equity(self._equity)

            if not self._circuit_breaker.is_triggered:
                triggered = await self._circuit_breaker.check_thresholds()
                if triggered:
                    logger.warning("Circuit breaker triggered during equity sync health check")
                    self.pause()

        except Exception as e:
            logger.warning(f"Failed to sync equity: {e}")
            await self._circuit_breaker.record_api_error(str(e))

    async def _sync_sleeve_equity(self) -> bool:
        """Sync equity + free cash from the sleeve projection. True if handled.

        Sleeve equity = free cash + Σ(lot qty × latest bar close). Falls back
        to a lot's average cost when no bar has arrived yet for its symbol.
        Returns False (caller uses account equity) when this session has no
        sleeve or no portfolio client.
        """
        if self.portfolio_client is None or self.config.sleeve_id is None:
            return False

        try:
            detail = await self.portfolio_client.get_sleeve(
                self.config.tenant_id, "", self.config.sleeve_id
            )
        except Exception as e:
            logger.warning(f"Failed to sync sleeve equity: {e}")
            await self._circuit_breaker.record_api_error(str(e))
            return True  # handled (do NOT fall back to whole-account equity)

        # Sleeve retired (stop/archive): holdings are re-homed, nothing left to manage — stop this session (loops honor _running and wind down next iteration).
        from llamatrade_proto.generated.ledger_pb2 import SLEEVE_STATUS_CLOSED

        if detail.sleeve.status == SLEEVE_STATUS_CLOSED:
            logger.info(
                "Sleeve %s is closed; stopping runner for execution %s",
                self.config.sleeve_id,
                self.config.execution_id,
            )
            self._running = False
            return True

        free_cash = Decimal(str(detail.sleeve.cash.free))
        equity = free_cash
        for lot in detail.lots:
            bars = self._bar_history.get(lot.symbol)
            price = Decimal(str(bars[-1].close)) if bars else Decimal(str(lot.avg_price))
            equity += Decimal(str(lot.qty)) * price

        self._free_cash = free_cash
        self._equity = equity
        logger.debug(f"Synced sleeve equity: ${equity:,.2f} (free cash ${free_cash:,.2f})")

        self._circuit_breaker.update_equity(self._equity)
        if not self._circuit_breaker.is_triggered:
            triggered = await self._circuit_breaker.check_thresholds()
            if triggered:
                logger.warning("Circuit breaker triggered during sleeve equity sync")
                self.pause()
        return True

    async def _equity_sync_loop(self) -> None:
        """Periodically sync equity, watch the evaluation gate, and drain session counters.

        The stall check rides this loop as well as the bar path, so a feed that
        goes completely silent (no bars at all) is still reported. The counter
        drain rides it because the runtime loop has no per-evaluation runner hook.
        """
        while self._running:
            await asyncio.sleep(60)
            if self._running:
                await self._sync_equity()
                await self._check_evaluation_stall(self._stalled_symbols())
                self._drain_session_counters()

    async def _position_sync_loop(self) -> None:
        """Periodically reconcile positions and re-check symbol tradability."""
        interval = self.config.position_reconciliation_interval_seconds
        while self._running:
            await asyncio.sleep(interval)
            if self._running:
                await self._sync_positions()
                await self._check_symbol_lifecycle()

    async def _ledger_republish_loop(self) -> None:
        """Proactively re-emit ledger events for recently-terminal orders (4A drain)."""
        interval = self.config.ledger_republish_interval_seconds
        window = timedelta(seconds=self.config.ledger_republish_window_seconds)
        while self._running:
            await asyncio.sleep(interval)
            if not self._running:
                break
            try:
                await self.order_executor.republish_ledger_for_terminal_orders(
                    self.config.tenant_id,
                    self.config.execution_id,
                    since=datetime.now(UTC) - window,
                )
            except Exception as e:
                logger.warning("Periodic ledger re-publish failed: %s", e)

    async def _trade_stream_loop(self) -> None:
        """Supervise the trade-updates stream for the runner's lifetime.

        Fills are the source of truth for position state, so the fill feed must
        never end silently. The client reconnects on transient drops, but after
        it exhausts its own attempts ``stream()`` returns normally — the async
        ``for`` would then end with no exception and never restart. This loop
        treats generator exhaustion (and any crash) as a fault: it alerts, backs
        off, rebuilds the client (resetting its attempt counter), and resumes, so
        a multi-minute outage degrades to reconnection latency rather than the
        runner trading blind while the bar loop keeps submitting orders.
        """
        logger.info("Starting trade stream supervisor loop")
        backoff = _TRADE_STREAM_RESTART_BASE_DELAY_S
        while self._running:
            try:
                async for event in self.trade_stream.stream():
                    if not self._running:
                        return
                    backoff = _TRADE_STREAM_RESTART_BASE_DELAY_S  # healthy feed
                    record_trade_stream_event(event.event_type.value)
                    try:
                        await self._handle_trade_event(event)
                    except Exception as e:
                        logger.error(f"Error handling trade event: {e}")
                        record_strategy_error("trade_event_processing")
            except asyncio.CancelledError:
                logger.info("Trade stream loop cancelled")
                return
            except Exception as e:
                logger.error(f"Trade stream loop error: {e}")

            if not self._running:
                return

            # Feed ended/crashed while the session is live and fills stopped arriving: alert, back off, rebuild the client, retry.
            logger.error(
                "Trade stream ended for execution %s; fills are not being received. "
                "Restarting in %.0fs",
                self.config.execution_id,
                backoff,
            )
            record_strategy_error("trade_stream_exhausted")
            if self.alerts:
                await self.alerts.on_connection_lost(
                    tenant_id=self.config.tenant_id,
                    session_id=self.config.execution_id,
                    service="trade_stream",
                )
            try:
                await asyncio.sleep(backoff)
            except asyncio.CancelledError:
                return
            backoff = min(backoff * 2, _TRADE_STREAM_RESTART_MAX_DELAY_S)
            if not self._running:
                return
            await self._rebuild_trade_stream()
        logger.info("Trade stream supervisor loop stopped")

    async def _rebuild_trade_stream(self) -> None:
        """Replace the trade-update client with a fresh one, then reconnect+subscribe.

        A fresh client (from the factory) starts with a zeroed reconnect-attempt
        counter, so the next ``stream()`` reconnects from scratch instead of being
        stuck past the give-up threshold. With no factory (tests) the existing
        client is reconnected — ``connect()`` also resets the counter on success.
        Best-effort: a failure here is retried on the next supervisor pass.
        """
        record_trade_stream_reconnect()
        try:
            if self._trade_stream_factory is not None:
                with contextlib.suppress(Exception):
                    await self.trade_stream.disconnect()
                self.trade_stream = self._trade_stream_factory()
            if not self.trade_stream.connected and not await self.trade_stream.connect():
                logger.warning("Trade stream reconnect failed; will retry")
                return
            if not await self.trade_stream.subscribe():
                logger.warning("Trade stream re-subscribe failed; will retry")
        except asyncio.CancelledError:
            raise
        except Exception as e:
            logger.warning("Trade stream rebuild failed: %s", e)

    async def _handle_trade_event(self, event: TradeEvent) -> None:
        """Handle a trade update event from Alpaca.

        Args:
            event: The trade event to process
        """
        if event.symbol not in self.config.symbols:
            return

        logger.debug(
            f"Trade event: {event.event_type.value} {event.symbol} order={event.order_id[:8]}..."
        )

        if event.event_type == TradeEventType.FILL:
            await self._handle_fill_event(event)
        elif event.event_type == TradeEventType.PARTIAL_FILL:
            await self._handle_partial_fill_event(event)
        elif event.event_type == TradeEventType.CANCELED:
            await self._handle_order_canceled(event)
        elif event.event_type == TradeEventType.EXPIRED:
            await self._handle_order_canceled(event)
        elif event.event_type == TradeEventType.REJECTED:
            await self._handle_order_rejected(event)

        # Ledger emission: one fill payload per order at terminal state only (builder returns None otherwise); a publish failure never breaks trade-event processing.
        await self._publish_ledger_fill(event)

    async def _publish_ledger_fill(self, event: TradeEvent) -> None:
        """Publish ledger payloads for a terminal trade event.

        - §1a fill payload (terminal fills, cancel/expiry with a filled portion);
        - §4 reservation release (cancel/reject/expiry) — idempotent at the
          ledger, so the executor's own release for API-initiated cancels never
          double-counts.
        """
        if (
            self.ledger_publisher is None
            or self.config.sleeve_id is None
            or self.config.account_id is None
        ):
            return

        payload = build_ledger_fill_payload(
            tenant_id=self.config.tenant_id,
            account_id=self.config.account_id,
            sleeve_id=self.config.sleeve_id,
            event=event,
        )
        try:
            if payload is not None:
                await self.ledger_publisher.publish_ledger_fill(payload)
            if event.event_type in (
                TradeEventType.CANCELED,
                TradeEventType.EXPIRED,
                TradeEventType.REJECTED,
            ):
                kind = (
                    "order_rejected"
                    if event.event_type is TradeEventType.REJECTED
                    else "order_cancelled"
                )
                release = build_ledger_lifecycle_payload(
                    kind=kind,
                    tenant_id=self.config.tenant_id,
                    account_id=self.config.account_id,
                    sleeve_id=self.config.sleeve_id,
                    client_order_id=event.client_order_id,
                    symbol=event.symbol,
                    side=event.side,
                )
                await self.ledger_publisher.publish_ledger_fill(release)
        except Exception as e:
            logger.error(f"Failed to publish ledger event for {event.client_order_id}: {e}")

        # A terminal event changes sleeve cash/lots — drop the cached state so the next equity sync (and free-cash fit) sees fresh numbers.
        if payload is not None and self.portfolio_client is not None:
            self.portfolio_client.invalidate(self.config.sleeve_id)

    async def _handle_fill_event(self, event: TradeEvent) -> None:
        """Handle a complete fill event - update position based on broker confirmation.

        Args:
            event: The fill event from Alpaca
        """
        start_time = time.perf_counter()

        if not event.fill:
            logger.warning(f"Fill event missing fill data: {event.order_id}")
            return

        fill = event.fill
        symbol = fill.symbol
        side = fill.side
        fill_price = fill.fill_price

        fill_qty = self._unapplied_fill_delta(event.event_type, fill)
        if fill_qty <= 0:
            logger.info(
                f"Skipping duplicate/out-of-order {event.event_type.value} event "
                f"for order {fill.client_order_id} ({symbol})"
            )
            return

        logger.info(f"Processing fill: {side} {fill_qty} {symbol} @ ${fill_price:.2f}")

        # Drop pending-order bookkeeping for this fill; position state below derives from the broker fill (source of truth). Keep the originating signal to measure slippage against its pre-trade price.
        pending_signal = self._pending_orders.pop(fill.client_order_id, None)

        old_position = self._positions.get(symbol)

        if side == "buy":
            # Opening or adding to long position
            if old_position and old_position.side == "long":
                # Adding to existing long position
                new_qty = old_position.quantity + fill_qty
                new_avg = (
                    (old_position.entry_price * old_position.quantity) + (fill_price * fill_qty)
                ) / new_qty
                self._positions[symbol] = RunnerPosition(
                    symbol=symbol,
                    side="long",
                    quantity=new_qty,
                    entry_price=new_avg,
                    entry_date=old_position.entry_date,
                )
            elif old_position and old_position.side == "short":
                # Closing short position (cover)
                remaining = old_position.quantity - fill_qty
                if remaining <= 0:
                    # Fully closed
                    pnl = _realized_pnl(
                        entry_price=old_position.entry_price,
                        exit_price=fill_price,
                        qty=old_position.quantity,
                        is_long=False,
                    )
                    del self._positions[symbol]
                    await self._circuit_breaker.record_trade(is_win=pnl >= 0, pnl=pnl)
                    if self.alerts:
                        await self.alerts.on_position_closed(
                            tenant_id=self.config.tenant_id,
                            session_id=self.config.execution_id,
                            symbol=symbol,
                            qty=float(old_position.quantity),
                            pnl=float(pnl),
                        )
                else:
                    # Partially closed
                    self._positions[symbol] = RunnerPosition(
                        symbol=symbol,
                        side="short",
                        quantity=remaining,
                        entry_price=old_position.entry_price,
                        entry_date=old_position.entry_date,
                    )
            else:
                # New long position
                self._positions[symbol] = RunnerPosition(
                    symbol=symbol,
                    side="long",
                    quantity=fill_qty,
                    entry_price=fill_price,
                    entry_date=event.timestamp,
                )
                if self.alerts:
                    await self.alerts.on_position_opened(
                        tenant_id=self.config.tenant_id,
                        session_id=self.config.execution_id,
                        symbol=symbol,
                        side="long",
                        qty=float(fill_qty),
                        price=float(fill_price),
                    )

        else:  # sell
            # Closing long position or opening short
            if old_position and old_position.side == "long":
                # Closing long position
                remaining = old_position.quantity - fill_qty
                if remaining <= 0:
                    # Fully closed
                    pnl = _realized_pnl(
                        entry_price=old_position.entry_price,
                        exit_price=fill_price,
                        qty=old_position.quantity,
                        is_long=True,
                    )
                    del self._positions[symbol]
                    await self._circuit_breaker.record_trade(is_win=pnl >= 0, pnl=pnl)
                    if self.alerts:
                        await self.alerts.on_position_closed(
                            tenant_id=self.config.tenant_id,
                            session_id=self.config.execution_id,
                            symbol=symbol,
                            qty=float(old_position.quantity),
                            pnl=float(pnl),
                        )
                else:
                    # Partially closed
                    self._positions[symbol] = RunnerPosition(
                        symbol=symbol,
                        side="long",
                        quantity=remaining,
                        entry_price=old_position.entry_price,
                        entry_date=old_position.entry_date,
                    )
            elif old_position and old_position.side == "short":
                # Adding to short position
                new_qty = old_position.quantity + fill_qty
                new_avg = (
                    (old_position.entry_price * old_position.quantity) + (fill_price * fill_qty)
                ) / new_qty
                self._positions[symbol] = RunnerPosition(
                    symbol=symbol,
                    side="short",
                    quantity=new_qty,
                    entry_price=new_avg,
                    entry_date=old_position.entry_date,
                )
            else:
                # New short position
                self._positions[symbol] = RunnerPosition(
                    symbol=symbol,
                    side="short",
                    quantity=fill_qty,
                    entry_price=fill_price,
                    entry_date=event.timestamp,
                )
                if self.alerts:
                    await self.alerts.on_position_opened(
                        tenant_id=self.config.tenant_id,
                        session_id=self.config.execution_id,
                        symbol=symbol,
                        side="short",
                        qty=float(fill_qty),
                        price=float(fill_price),
                    )

        self._fills_processed += 1
        duration = time.perf_counter() - start_time
        record_fill_processed(side=side, fill_type="full", duration=duration)

        # Slippage: compare the broker fill against the signal's pre-trade estimate, only when we still have the originating signal with a usable reference price.
        if pending_signal is not None:
            record_slippage(
                side=side, fill_price=float(fill_price), est_price=float(pending_signal.price)
            )

        logger.info(f"Fill processed: {symbol} now {self._positions.get(symbol, 'flat')}")

    def _unapplied_fill_delta(self, event_type: TradeEventType, fill: FillData) -> Decimal:
        """Portion of the order's cumulative filled qty not yet applied locally.

        Tracks cumulative filled qty per client_order_id so a partial followed by
        the terminal fill books only the remainder, and a duplicate or
        out-of-order event yields a non-positive delta (the caller skips it).
        Terminal fills clear the entry and remember the order id so a replayed
        event can never re-apply.
        """
        coid = fill.client_order_id
        if coid in self._terminal_order_ids:
            return Decimal("0")
        applied = self._applied_fill_qty.get(coid, Decimal("0"))
        # A stream that doesn't report cumulative qty degrades to per-event booking.
        cumulative = fill.total_filled_qty if fill.total_filled_qty > 0 else applied + fill.fill_qty
        if event_type is TradeEventType.FILL:
            self._applied_fill_qty.pop(coid, None)
            self._terminal_order_ids.append(coid)
        elif cumulative > applied:
            self._applied_fill_qty[coid] = cumulative
        return cumulative - applied

    def _clear_fill_tracking(self, client_order_id: str) -> None:
        """Drop per-order fill tracking at a terminal (cancel/expiry/reject) event."""
        self._applied_fill_qty.pop(client_order_id, None)
        self._terminal_order_ids.append(client_order_id)

    async def _handle_partial_fill_event(self, event: TradeEvent) -> None:
        """Handle a partial fill event.

        For partial fills, we update position incrementally.
        """
        await self._handle_fill_event(event)

        if event.fill:
            logger.info(
                f"Partial fill: {event.fill.fill_qty}/{event.qty} "
                f"remaining={event.fill.remaining_qty}"
            )

    async def _handle_order_canceled(self, event: TradeEvent) -> None:
        """Handle an order cancellation.

        Remove from pending orders - no position update needed.
        """
        signal = self._pending_orders.pop(event.client_order_id, None)
        self._clear_fill_tracking(event.client_order_id)
        if signal:
            logger.info(f"Order canceled: {event.symbol} {signal.type} {signal.quantity}")

    async def _handle_order_rejected(self, event: TradeEvent) -> None:
        """Handle an order rejection.

        Remove from pending orders and alert.
        """
        signal = self._pending_orders.pop(event.client_order_id, None)
        self._clear_fill_tracking(event.client_order_id)
        if signal:
            logger.warning(f"Order rejected: {event.symbol} {signal.type} {signal.quantity}")
            self._orders_rejected += 1
            record_strategy_error("order_rejected")

            if self.alerts:
                await self.alerts.on_strategy_error(
                    tenant_id=self.config.tenant_id,
                    session_id=self.config.execution_id,
                    error=f"Order rejected by broker: {event.symbol} {signal.type}",
                )

    async def _sync_positions(self) -> None:
        """Reconcile local positions with Alpaca broker positions.

        This method:
        1. Fetches all positions from Alpaca
        2. Compares with local position tracking
        3. Auto-corrects small drifts (< auto_correct_threshold)
        4. Alerts on large drifts (>= alert_threshold)
        5. Handles missing positions in either direction

        When the portfolio ledger owns reconciliation (a sleeve-attributed
        session), this becomes READ-ONLY: drift is logged and alerted but local
        state is never auto-corrected — two writers "correcting" the same drift
        would fight each other.
        """
        if not self.alpaca_client:
            return

        # Portfolio owns reconciliation for sleeve-attributed sessions
        ledger_owns_reconciliation = self.config.sleeve_id is not None

        import time

        start_time = time.perf_counter()

        try:
            broker_positions = await self.alpaca_client.get_positions()

            broker_by_symbol = {p.symbol: p for p in broker_positions}
            local_symbols = set(self._positions.keys())
            broker_symbols = set(broker_by_symbol.keys())

            strategy_symbols = set(self.config.symbols)

            all_ok = True

            # 1. Positions we track locally but broker doesn't have
            missing_at_broker = local_symbols - broker_symbols
            for symbol in missing_at_broker:
                # Only care about symbols in our strategy
                if symbol not in strategy_symbols:
                    continue

                local_pos = self._positions[symbol]
                logger.warning(
                    f"Position drift: {symbol} exists locally "
                    f"({local_pos.side} {local_pos.quantity}) but not at broker"
                )

                duration = time.perf_counter() - start_time
                record_position_reconciliation(
                    result="drift_alerted",
                    duration=duration,
                    drift_type="missing_broker",
                    drift_percent=100.0,  # 100% missing
                )

                # Alert on missing broker position
                if self.alerts:
                    await self.alerts.on_position_drift(
                        tenant_id=self.config.tenant_id,
                        session_id=self.config.execution_id,
                        symbol=symbol,
                        drift_type="missing_broker",
                        local_qty=float(local_pos.quantity),
                        broker_qty=0.0,
                        action="alerted",
                    )

                all_ok = False

            # 2. Positions broker has but we don't track locally
            missing_locally = broker_symbols - local_symbols
            for symbol in missing_locally:
                # Only care about symbols in our strategy
                if symbol not in strategy_symbols:
                    continue

                broker_pos = broker_by_symbol[symbol]
                logger.warning(
                    f"Position drift: {symbol} exists at broker "
                    f"({broker_pos.side} {broker_pos.qty}) but not locally"
                )

                if ledger_owns_reconciliation:
                    # Read-only: surface the drift, let the ledger reconcile it
                    duration = time.perf_counter() - start_time
                    record_position_reconciliation(
                        result="drift_alerted",
                        duration=duration,
                        drift_type="missing_local",
                        drift_percent=100.0,
                    )
                    if self.alerts:
                        await self.alerts.on_position_drift(
                            tenant_id=self.config.tenant_id,
                            session_id=self.config.execution_id,
                            symbol=symbol,
                            drift_type="missing_local",
                            local_qty=0.0,
                            broker_qty=float(broker_pos.qty),
                            action="alerted",
                        )
                    all_ok = False
                    continue

                # Auto-add missing position (broker is source of truth)
                broker_qty = broker_pos.qty
                self._positions[symbol] = RunnerPosition(
                    symbol=symbol,
                    side=broker_pos.side,
                    quantity=broker_qty,
                    entry_price=(
                        broker_pos.cost_basis / broker_qty if broker_qty > 0 else Decimal("0")
                    ),
                    entry_date=datetime.now(UTC),  # Approximate
                )

                duration = time.perf_counter() - start_time
                record_position_reconciliation(
                    result="drift_corrected",
                    duration=duration,
                    drift_type="missing_local",
                    drift_percent=100.0,
                )

                logger.info(f"Auto-corrected: Added missing local position for {symbol}")

                if self.alerts:
                    await self.alerts.on_position_drift(
                        tenant_id=self.config.tenant_id,
                        session_id=self.config.execution_id,
                        symbol=symbol,
                        drift_type="missing_local",
                        local_qty=0.0,
                        broker_qty=float(broker_pos.qty),
                        action="corrected",
                    )

                all_ok = False

            # 3. Check quantity/side mismatches for symbols we both have
            common_symbols = local_symbols & broker_symbols & strategy_symbols
            for symbol in common_symbols:
                local_pos = self._positions[symbol]
                broker_pos = broker_by_symbol[symbol]

                # Check side mismatch
                if local_pos.side != broker_pos.side:
                    logger.error(
                        f"Position drift: {symbol} side mismatch - "
                        f"local={local_pos.side}, broker={broker_pos.side}"
                    )

                    duration = time.perf_counter() - start_time
                    record_position_reconciliation(
                        result="drift_alerted",
                        duration=duration,
                        drift_type="side_mismatch",
                    )

                    if self.alerts:
                        await self.alerts.on_position_drift(
                            tenant_id=self.config.tenant_id,
                            session_id=self.config.execution_id,
                            symbol=symbol,
                            drift_type="side_mismatch",
                            local_qty=float(local_pos.quantity),
                            broker_qty=float(broker_pos.qty),
                            action="alerted",
                        )

                    all_ok = False
                    continue

                # Check quantity mismatch
                broker_qty = broker_pos.qty
                if local_pos.quantity != broker_qty:
                    drift_pct = (
                        abs(local_pos.quantity - broker_qty)
                        / max(local_pos.quantity, broker_qty, Decimal("0.001"))
                        * 100
                    )

                    auto_correct_threshold = self.config.position_drift_auto_correct_threshold_pct
                    alert_threshold = self.config.position_drift_alert_threshold_pct

                    if ledger_owns_reconciliation:
                        # Read-only: never mutate; alert on material drift
                        duration = time.perf_counter() - start_time
                        record_position_reconciliation(
                            result="drift_alerted",
                            duration=duration,
                            drift_type="quantity_mismatch",
                            drift_percent=float(drift_pct),
                        )
                        logger.warning(
                            f"Position drift (ledger-owned): {symbol} "
                            f"local={local_pos.quantity}, broker={broker_pos.qty} "
                            f"({drift_pct:.1f}%)"
                        )
                        if self.alerts and drift_pct >= alert_threshold:
                            await self.alerts.on_position_drift(
                                tenant_id=self.config.tenant_id,
                                session_id=self.config.execution_id,
                                symbol=symbol,
                                drift_type="quantity_mismatch",
                                local_qty=float(local_pos.quantity),
                                broker_qty=float(broker_pos.qty),
                                action="alerted",
                            )
                        all_ok = False
                    elif drift_pct < auto_correct_threshold:
                        # Auto-correct small drift
                        old_qty = local_pos.quantity
                        local_pos.quantity = broker_qty

                        duration = time.perf_counter() - start_time
                        record_position_reconciliation(
                            result="drift_corrected",
                            duration=duration,
                            drift_type="quantity_mismatch",
                            drift_percent=float(drift_pct),
                        )

                        logger.info(
                            f"Auto-corrected: {symbol} quantity drift "
                            f"{old_qty} -> {broker_pos.qty} ({drift_pct:.1f}%)"
                        )

                        if self.alerts:
                            await self.alerts.on_position_drift(
                                tenant_id=self.config.tenant_id,
                                session_id=self.config.execution_id,
                                symbol=symbol,
                                drift_type="quantity_mismatch",
                                local_qty=float(old_qty),
                                broker_qty=float(broker_pos.qty),
                                action="corrected",
                            )

                    elif drift_pct >= alert_threshold:
                        # Large drift - alert but don't auto-correct
                        duration = time.perf_counter() - start_time
                        record_position_reconciliation(
                            result="drift_alerted",
                            duration=duration,
                            drift_type="quantity_mismatch",
                            drift_percent=float(drift_pct),
                        )

                        logger.warning(
                            f"Position drift: {symbol} quantity mismatch - "
                            f"local={local_pos.quantity}, broker={broker_pos.qty} "
                            f"({drift_pct:.1f}% drift)"
                        )

                        if self.alerts:
                            await self.alerts.on_position_drift(
                                tenant_id=self.config.tenant_id,
                                session_id=self.config.execution_id,
                                symbol=symbol,
                                drift_type="quantity_mismatch",
                                local_qty=float(local_pos.quantity),
                                broker_qty=float(broker_pos.qty),
                                action="alerted",
                            )

                        all_ok = False

                    else:
                        # Medium drift - log but don't act
                        logger.debug(
                            f"Position drift (ignored): {symbol} {drift_pct:.1f}% "
                            f"(local={local_pos.quantity}, broker={broker_pos.qty})"
                        )

            # Record overall success if no issues
            if all_ok:
                duration = time.perf_counter() - start_time
                record_position_reconciliation(result="match", duration=duration)
                logger.debug(
                    f"Position reconciliation complete: {len(common_symbols)} positions match"
                )

            # Track successful reconciliation
            self._last_reconciliation_time = datetime.now(UTC)
            self._reconciliation_error_count = 0  # Reset error count on success

        except Exception as e:
            duration = time.perf_counter() - start_time
            record_position_reconciliation(result="error", duration=duration)
            logger.error(f"Failed to reconcile positions: {e}")

            self._reconciliation_error_count += 1

            # Alert if 3+ consecutive failures
            if self._reconciliation_error_count >= 3 and self.alerts:
                await self.alerts.on_strategy_error(
                    tenant_id=self.config.tenant_id,
                    session_id=self.config.execution_id,
                    error=f"Position reconciliation failing ({self._reconciliation_error_count} consecutive errors): {e}",
                )

            await self._circuit_breaker.record_api_error(str(e))


class RunnerManager:
    """Manages multiple strategy runners."""

    def __init__(self) -> None:
        self._runners: dict[UUID, StrategyRunner] = {}
        self._tasks: dict[UUID, asyncio.Task[None]] = {}

    @property
    def active_runners(self) -> list[UUID]:
        """Get IDs of active runners."""
        return [uid for uid, runner in self._runners.items() if runner.running]

    def get_runner(self, execution_id: UUID) -> StrategyRunner | None:
        """Get a runner by deployment ID."""
        return self._runners.get(execution_id)

    async def start_runner(
        self,
        config: RunnerConfig,
        strategy_fn: StrategyFunction | None,
        bar_stream: BarStream,
        trade_stream: TradingStreamClient | MockTradeStream,
        order_executor: OrderExecutor,
        risk_manager: RiskManager,
        alpaca_client: TradingClient | None = None,
        alert_service: AlertService | None = None,
        strategy_name: str = "Unknown Strategy",
        circuit_breaker_config: CircuitBreakerConfig | None = None,
        ledger_publisher: TradingEventPublisher | None = None,
        portfolio_client: PortfolioLedgerClient | None = None,
        session: StrategySession | None = None,
        trade_stream_factory: Callable[[], TradingStreamClient | MockTradeStream] | None = None,
    ) -> StrategyRunner:
        """Create and start a new runner.

        Args:
            config: Runner configuration.
            strategy_fn: Compiled strategy function.
            bar_stream: Bar data stream.
            trade_stream: Trade update stream.
            order_executor: Order executor for submitting orders.
            risk_manager: Risk manager for order validation.
            alpaca_client: Alpaca trading client.
            alert_service: Alert service for notifications.
            strategy_name: Human-readable strategy name.
            circuit_breaker_config: Circuit breaker configuration.

        Returns:
            Started StrategyRunner instance.
        """
        execution_id = config.execution_id

        if execution_id in self._runners:
            raise ValueError(f"Runner already exists for execution {execution_id}")

        runner = StrategyRunner(
            config=config,
            strategy_fn=strategy_fn,
            bar_stream=bar_stream,
            trade_stream=trade_stream,
            order_executor=order_executor,
            risk_manager=risk_manager,
            alpaca_client=alpaca_client,
            alert_service=alert_service,
            strategy_name=strategy_name,
            circuit_breaker_config=circuit_breaker_config,
            ledger_publisher=ledger_publisher,
            portfolio_client=portfolio_client,
            session=session,
            trade_stream_factory=trade_stream_factory,
        )

        self._runners[execution_id] = runner

        task = asyncio.create_task(runner.start())
        self._tasks[execution_id] = task

        update_runner_gauge(len(self.active_runners))

        return runner

    async def stop_runner(self, execution_id: UUID) -> bool:
        """Stop a runner."""
        runner = self._runners.get(execution_id)
        if not runner:
            return False

        await runner.stop()

        task = self._tasks.get(execution_id)
        if task:
            task.cancel()
            try:
                await task
            except asyncio.CancelledError:
                pass

        del self._runners[execution_id]
        del self._tasks[execution_id]

        update_runner_gauge(len(self.active_runners))

        return True

    async def stop_all(self) -> None:
        """Stop all runners."""
        for execution_id in list(self._runners.keys()):
            await self.stop_runner(execution_id)


# Singleton manager
_manager: RunnerManager | None = None


def get_runner_manager() -> RunnerManager:
    """Get the runner manager instance."""
    global _manager
    if _manager is None:
        _manager = RunnerManager()
    return _manager
