"""Strategy runner for live trading execution."""

import asyncio
import logging
from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import Protocol
from uuid import UUID

from src.alpaca_client import AlpacaTradingClient
from src.executor.order_executor import OrderExecutor
from src.models import OrderCreate, OrderSide, OrderType, RiskLimits, TimeInForce
from src.risk.risk_manager import RiskManager
from src.runner.bar_stream import AlpacaBarStream, BarData, MockBarStream

logger = logging.getLogger(__name__)


@dataclass
class Signal:
    """Trading signal generated by strategy."""

    type: str  # "buy", "sell", "short", "cover"
    symbol: str
    quantity: float
    price: float
    timestamp: datetime = field(default_factory=lambda: datetime.now(UTC))


@dataclass
class Position:
    """Current position in a symbol."""

    symbol: str
    side: str  # "long", "short", "flat"
    quantity: float
    entry_price: float
    entry_date: datetime


@dataclass
class RunnerConfig:
    """Configuration for strategy runner."""

    tenant_id: UUID
    deployment_id: UUID
    strategy_id: UUID
    symbols: list[str]
    timeframe: str
    warmup_bars: int = 50
    risk_limits: RiskLimits | None = None


class StrategyFunction(Protocol):
    """Protocol for compiled strategy functions."""

    def __call__(
        self,
        symbol: str,
        bars: list[BarData],
        position: Position | None,
        equity: float,
    ) -> Signal | None: ...


class StrategyRunner:
    """Runs a compiled strategy against real-time bar data.

    The runner:
    1. Subscribes to bar stream for strategy symbols
    2. Accumulates bar history per symbol
    3. Invokes strategy function on each new bar
    4. Routes generated signals through risk checks and order execution
    5. Periodically syncs equity from Alpaca account
    """

    def __init__(
        self,
        config: RunnerConfig,
        strategy_fn: StrategyFunction,
        bar_stream: AlpacaBarStream | MockBarStream,
        order_executor: OrderExecutor,
        risk_manager: RiskManager,
        alpaca_client: AlpacaTradingClient | None = None,
    ):
        self.config = config
        self.strategy_fn = strategy_fn
        self.bar_stream = bar_stream
        self.order_executor = order_executor
        self.risk_manager = risk_manager
        self.alpaca_client = alpaca_client

        # State
        self._running = False
        self._paused = False
        self._bar_history: dict[str, list[BarData]] = {s: [] for s in config.symbols}
        self._positions: dict[str, Position] = {}
        self._equity = 100000.0  # Default, will be synced from Alpaca
        self._equity_sync_task: asyncio.Task | None = None

        # Metrics
        self._signals_generated = 0
        self._orders_submitted = 0
        self._orders_rejected = 0

    @property
    def running(self) -> bool:
        """Check if runner is active."""
        return self._running

    @property
    def paused(self) -> bool:
        """Check if runner is paused."""
        return self._paused

    @property
    def positions(self) -> dict[str, Position]:
        """Get current positions."""
        return self._positions.copy()

    @property
    def metrics(self) -> dict:
        """Get runner metrics."""
        return {
            "signals_generated": self._signals_generated,
            "orders_submitted": self._orders_submitted,
            "orders_rejected": self._orders_rejected,
            "positions": len(self._positions),
            "bar_history_sizes": {s: len(bars) for s, bars in self._bar_history.items()},
        }

    async def start(self) -> None:
        """Start the strategy runner."""
        if self._running:
            logger.warning("Runner already started")
            return

        logger.info(f"Starting strategy runner for deployment {self.config.deployment_id}")

        # Sync equity before starting
        await self._sync_equity()

        # Connect to bar stream
        if not self.bar_stream.connected:
            if not await self.bar_stream.connect():
                raise RuntimeError("Failed to connect to bar stream")

        # Subscribe to symbols
        if not await self.bar_stream.subscribe(self.config.symbols):
            raise RuntimeError("Failed to subscribe to symbols")

        self._running = True

        # Start periodic equity sync task
        self._equity_sync_task = asyncio.create_task(self._equity_sync_loop())

        # Main processing loop
        try:
            async for bar in self.bar_stream.stream():
                if not self._running:
                    break

                if self._paused:
                    continue

                await self._process_bar(bar)

        except asyncio.CancelledError:
            logger.info("Runner cancelled")
        except Exception as e:
            logger.error(f"Runner error: {e}")
            raise
        finally:
            self._running = False
            if self._equity_sync_task:
                self._equity_sync_task.cancel()
                try:
                    await self._equity_sync_task
                except asyncio.CancelledError:
                    pass
            logger.info("Runner stopped")

    async def stop(self) -> None:
        """Stop the strategy runner."""
        logger.info(f"Stopping runner for deployment {self.config.deployment_id}")
        self._running = False
        await self.bar_stream.disconnect()

    def pause(self) -> None:
        """Pause signal generation (continues receiving bars)."""
        logger.info(f"Pausing runner for deployment {self.config.deployment_id}")
        self._paused = True

    def resume(self) -> None:
        """Resume signal generation."""
        logger.info(f"Resuming runner for deployment {self.config.deployment_id}")
        self._paused = False

    async def _process_bar(self, bar: BarData) -> None:
        """Process an incoming bar."""
        symbol = bar.symbol

        # Ignore bars for untracked symbols
        if symbol not in self._bar_history:
            return

        # Add to history
        self._bar_history[symbol].append(bar)

        # Limit history size
        max_history = self.config.warmup_bars + 100
        if len(self._bar_history[symbol]) > max_history:
            self._bar_history[symbol] = self._bar_history[symbol][-max_history:]

        # Skip if warming up
        if len(self._bar_history[symbol]) < self.config.warmup_bars:
            logger.debug(
                f"Warming up {symbol}: {len(self._bar_history[symbol])}/{self.config.warmup_bars}"
            )
            return

        # Get current position
        position = self._positions.get(symbol)

        # Generate signal
        try:
            signal = self.strategy_fn(
                symbol=symbol,
                bars=self._bar_history[symbol],
                position=position,
                equity=self._equity,
            )

            if signal:
                self._signals_generated += 1
                await self._process_signal(signal)

        except Exception as e:
            logger.error(f"Strategy error for {symbol}: {e}")

    async def _process_signal(self, signal: Signal) -> None:
        """Process a trading signal."""
        logger.info(f"Signal: {signal.type} {signal.quantity} {signal.symbol}")

        # Run risk checks
        risk_result = await self.risk_manager.check_order(
            tenant_id=self.config.tenant_id,
            symbol=signal.symbol,
            side=signal.type,
            qty=signal.quantity,
            order_type="market",
        )

        if not risk_result.passed:
            logger.warning(f"Signal rejected by risk: {risk_result.violations}")
            self._orders_rejected += 1
            return

        # Convert signal to order
        order = self._signal_to_order(signal)

        # Submit order
        try:
            result = await self.order_executor.submit_order(
                tenant_id=self.config.tenant_id,
                session_id=self.config.deployment_id,
                order=order,
            )

            self._orders_submitted += 1
            logger.info(f"Order submitted: {result.id} status={result.status}")

            # Update position tracking
            await self._update_position(signal)

        except Exception as e:
            logger.error(f"Order submission failed: {e}")
            self._orders_rejected += 1

    def _signal_to_order(self, signal: Signal) -> OrderCreate:
        """Convert a signal to an order request."""
        side = OrderSide.BUY if signal.type in ("buy", "cover") else OrderSide.SELL

        return OrderCreate(
            symbol=signal.symbol,
            side=side,
            qty=signal.quantity,
            order_type=OrderType.MARKET,
            time_in_force=TimeInForce.DAY,
        )

    async def _update_position(self, signal: Signal) -> None:
        """Update position tracking after signal."""
        symbol = signal.symbol

        if signal.type == "buy":
            self._positions[symbol] = Position(
                symbol=symbol,
                side="long",
                quantity=signal.quantity,
                entry_price=signal.price,
                entry_date=signal.timestamp,
            )

        elif signal.type == "sell":
            if symbol in self._positions:
                del self._positions[symbol]

        elif signal.type == "short":
            self._positions[symbol] = Position(
                symbol=symbol,
                side="short",
                quantity=signal.quantity,
                entry_price=signal.price,
                entry_date=signal.timestamp,
            )

        elif signal.type == "cover":
            if symbol in self._positions:
                del self._positions[symbol]

    def set_equity(self, equity: float) -> None:
        """Update equity value (called by external sync)."""
        self._equity = equity

    def sync_position(self, symbol: str, position: Position | None) -> None:
        """Sync position from external source (e.g., Alpaca)."""
        if position:
            self._positions[symbol] = position
        elif symbol in self._positions:
            del self._positions[symbol]

    async def _sync_equity(self) -> None:
        """Sync equity from Alpaca account."""
        if not self.alpaca_client:
            return

        try:
            account = await self.alpaca_client.get_account()
            equity_str = account.get("equity", "100000")
            self._equity = float(equity_str)
            logger.debug(f"Synced equity: ${self._equity:,.2f}")
        except Exception as e:
            logger.warning(f"Failed to sync equity: {e}")

    async def _equity_sync_loop(self) -> None:
        """Periodically sync equity from Alpaca (every 60 seconds)."""
        while self._running:
            await asyncio.sleep(60)
            if self._running:
                await self._sync_equity()


class RunnerManager:
    """Manages multiple strategy runners."""

    def __init__(self) -> None:
        self._runners: dict[UUID, StrategyRunner] = {}
        self._tasks: dict[UUID, asyncio.Task[None]] = {}

    @property
    def active_runners(self) -> list[UUID]:
        """Get IDs of active runners."""
        return [uid for uid, runner in self._runners.items() if runner.running]

    def get_runner(self, deployment_id: UUID) -> StrategyRunner | None:
        """Get a runner by deployment ID."""
        return self._runners.get(deployment_id)

    async def start_runner(
        self,
        config: RunnerConfig,
        strategy_fn: StrategyFunction,
        bar_stream: AlpacaBarStream | MockBarStream,
        order_executor: OrderExecutor,
        risk_manager: RiskManager,
        alpaca_client: AlpacaTradingClient | None = None,
    ) -> StrategyRunner:
        """Create and start a new runner."""
        deployment_id = config.deployment_id

        if deployment_id in self._runners:
            raise ValueError(f"Runner already exists for deployment {deployment_id}")

        runner = StrategyRunner(
            config=config,
            strategy_fn=strategy_fn,
            bar_stream=bar_stream,
            order_executor=order_executor,
            risk_manager=risk_manager,
            alpaca_client=alpaca_client,
        )

        self._runners[deployment_id] = runner

        # Start in background task
        task = asyncio.create_task(runner.start())
        self._tasks[deployment_id] = task

        return runner

    async def stop_runner(self, deployment_id: UUID) -> bool:
        """Stop a runner."""
        runner = self._runners.get(deployment_id)
        if not runner:
            return False

        await runner.stop()

        # Cancel task
        task = self._tasks.get(deployment_id)
        if task:
            task.cancel()
            try:
                await task
            except asyncio.CancelledError:
                pass

        del self._runners[deployment_id]
        del self._tasks[deployment_id]

        return True

    async def stop_all(self) -> None:
        """Stop all runners."""
        for deployment_id in list(self._runners.keys()):
            await self.stop_runner(deployment_id)


# Singleton manager
_manager: RunnerManager | None = None


def get_runner_manager() -> RunnerManager:
    """Get the runner manager instance."""
    global _manager
    if _manager is None:
        _manager = RunnerManager()
    return _manager
