"""Backtesting engine - runs historical simulations."""

import math
from collections.abc import Callable
from dataclasses import dataclass, field
from datetime import datetime
from typing import TypedDict, cast

import numpy as np

from src.engine import metrics


def _finite(value: float, default: float = 0.0) -> float:
    """Return ``value`` if finite, else ``default``.

    Defensive nan/inf guard (7A): the metric functions already guard their
    divisions, but this ensures a non-finite scalar can never reach the DB
    (``Decimal('NaN')`` would fail the Numeric columns).
    """
    return value if math.isfinite(value) else default


# Type alias for progress callback
# Signature: (current_bar: int, total_bars: int, current_date: datetime) -> None
ProgressCallback = Callable[[int, int, datetime], None]

# Type alias for multi-symbol strategy functions.
# Signature: (engine, bars_dict, warm_up) -> signals, where bars_dict maps
# symbol -> BarData for the current date. When warm_up is True the strategy
# should only accumulate indicator history and return no signals.
StrategyFn = Callable[["BacktestEngine", dict[str, "BarData"], bool], list["SignalData"]]


class BacktestCancelled(Exception):  # domain signal, not an error (N818 ignored in config)
    """Raised when a run is cooperatively cancelled mid-simulation."""


class BarData(TypedDict):
    """Bar data for backtesting."""

    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: int


class SignalData(TypedDict, total=False):
    """Signal generated by strategy."""

    type: str  # "buy" or "sell"
    symbol: str
    quantity: float
    price: float


@dataclass
class Trade:
    """Represents a completed trade."""

    entry_date: datetime
    exit_date: datetime
    symbol: str
    side: str  # always 'long'; the engine does not support short selling
    entry_price: float
    exit_price: float
    quantity: float
    commission: float = 0

    @property
    def pnl(self) -> float:
        """Calculate P&L for this trade."""
        gross_pnl = (self.exit_price - self.entry_price) * self.quantity
        return gross_pnl - self.commission

    @property
    def pnl_percent(self) -> float:
        """Calculate P&L percentage.

        Returns 0.0 if entry_price or quantity is zero to avoid division by zero.
        """
        denominator = self.entry_price * self.quantity
        if denominator == 0:
            return 0.0
        return (self.pnl / denominator) * 100


@dataclass
class Position:
    """Represents an open position."""

    symbol: str
    side: str
    entry_price: float
    quantity: float
    entry_date: datetime
    # Entry commission paid (accumulated across adds) and not yet allocated to a
    # closing trade. Allocated proportionally on (partial) exits so commission is
    # counted exactly once per fill and trade P&L reconciles with equity (6A).
    entry_commission_remaining: float = 0.0


@dataclass
class BacktestConfig:
    """Configuration for a backtest run."""

    initial_capital: float = 100000
    commission_rate: float = 0  # Flat fee per fill (entry and each exit), not a %
    slippage_rate: float = 0  # Percentage
    risk_free_rate: float = 0.02  # For Sharpe ratio


@dataclass
class RejectedSignal:
    """A signal that was rejected by the engine."""

    date: datetime
    symbol: str
    signal_type: str
    quantity: float
    price: float
    reason: str


def _empty_trade_list() -> list[Trade]:
    return []


def _empty_equity_curve() -> list[tuple[datetime, float]]:
    return []


def _empty_rejected_signals() -> list[RejectedSignal]:
    return []


def _empty_float_list() -> list[float]:
    return []


def _empty_monthly_returns() -> dict[str, float]:
    return {}


@dataclass
class BacktestResult:
    """Results from a backtest run."""

    trades: list[Trade] = field(default_factory=_empty_trade_list)
    equity_curve: list[tuple[datetime, float]] = field(default_factory=_empty_equity_curve)
    # Daily-resampled curve; all annualized metrics are computed on this grid
    daily_equity_curve: list[tuple[datetime, float]] = field(default_factory=_empty_equity_curve)
    rejected_signals: list[RejectedSignal] = field(default_factory=_empty_rejected_signals)
    final_equity: float = 0
    total_return: float = 0
    annual_return: float = 0
    sharpe_ratio: float = 0
    sortino_ratio: float = 0
    max_drawdown: float = 0
    max_drawdown_duration: int = 0  # In trading days
    win_rate: float = 0
    # None means undefined (no trades, or no losing trades) — see metrics module
    profit_factor: float | None = None
    daily_returns: list[float] = field(default_factory=_empty_float_list)
    monthly_returns: dict[str, float] = field(default_factory=_empty_monthly_returns)
    exposure_time: float = 0  # Percentage of time with open positions
    # Benchmark comparison fields
    benchmark_return: float = 0
    benchmark_equity_curve: list[tuple[datetime, float]] = field(
        default_factory=_empty_equity_curve
    )
    benchmark_symbol: str = ""
    alpha: float = 0
    beta: float = 0
    information_ratio: float = 0
    excess_return: float = 0


class BacktestEngine:
    """Engine for running historical backtests."""

    def __init__(self, config: BacktestConfig | None = None):
        self.config = config or BacktestConfig()
        self.cash = self.config.initial_capital
        self.positions: dict[str, Position] = {}
        self.trades: list[Trade] = []
        self.equity_curve: list[tuple[datetime, float]] = []
        self.rejected_signals: list[RejectedSignal] = []
        self._current_date: datetime | None = None
        self._days_with_position: int = 0
        self._total_days: int = 0
        self._last_prices: dict[str, float] = {}

    def reset(self) -> None:
        """Reset the engine state."""
        self.cash = self.config.initial_capital
        self.positions = {}
        self.trades = []
        self.equity_curve = []
        self.rejected_signals = []
        self._current_date = None
        self._days_with_position = 0
        self._total_days = 0
        self._last_prices = {}

    def run(
        self,
        bars: dict[str, list[BarData]],
        strategy_fn: StrategyFn,
        start_date: datetime,
        end_date: datetime,
        progress_callback: ProgressCallback | None = None,
        should_abort: Callable[[], bool] | None = None,
    ) -> BacktestResult:
        """Run a backtest with multi-symbol strategy evaluation.

        For each date, all symbols' bars are passed to the strategy at once,
        enabling cross-symbol comparisons for portfolio allocation.

        Bars dated before `start_date` are treated as warm-up: they are fed to
        the strategy so indicators can accumulate history, but no signals are
        executed and no equity is recorded for them.

        Args:
            bars: Historical bar data by symbol (may include warm-up bars)
            strategy_fn: Strategy function (engine, bars_dict, warm_up) -> signals
            start_date: First date on which trading and equity tracking occur
            end_date: Last date of the backtest
            progress_callback: Optional callback for progress updates.
                Signature: (current_bar, total_bars, current_date) -> None
            should_abort: Optional cancellation check, called once per trading
                date. Returning True raises BacktestCancelled.

        Returns:
            BacktestResult with metrics and trades

        Raises:
            BacktestCancelled: If should_abort returns True mid-run.
        """
        self.reset()

        # Index bars by date once for O(1) lookups
        bars_by_date: dict[datetime, dict[str, BarData]] = {}
        for symbol, symbol_bars in bars.items():
            for bar in symbol_bars:
                bar_date = bar["timestamp"]
                if bar_date <= end_date:
                    if bar_date not in bars_by_date:
                        bars_by_date[bar_date] = {}
                    bars_by_date[bar_date][symbol] = bar

        sorted_dates: list[datetime] = sorted(bars_by_date)
        total_bars = sum(1 for d in sorted_dates if d >= start_date)

        trading_bar_idx = 0
        for date in sorted_dates:
            date_bars = bars_by_date[date]

            # Track last known price per symbol (O(1) equity/close lookups)
            for symbol, bar in date_bars.items():
                self._last_prices[symbol] = bar["close"]

            if date < start_date:
                # Warm-up: feed bars to the strategy, execute nothing
                strategy_fn(self, date_bars, True)
                continue

            if should_abort is not None and should_abort():
                raise BacktestCancelled(f"Backtest cancelled at {date.isoformat()}")

            self._current_date = date
            self._total_days += 1

            signals = strategy_fn(self, date_bars, False)
            for signal in signals:
                symbol = signal.get("symbol", "")
                signal_bar = date_bars.get(symbol)
                if signal_bar:
                    self._process_signal(signal, signal_bar)

            # Track days with position
            if self.positions:
                self._days_with_position += 1

            # Record equity
            self.equity_curve.append((date, self._calculate_equity()))

            trading_bar_idx += 1
            if progress_callback is not None:
                progress_callback(trading_bar_idx, total_bars, date)

        # Close all remaining positions at the last known prices
        self._close_all_positions()

        # The last recorded equity point was marked-to-market *before* this
        # end-of-run liquidation, so it excludes the liquidation's commission
        # (and any exit slippage). Replace it with the realized equity so the
        # curve's final value reconciles with the trade ledger (6A).
        if self.equity_curve:
            last_date = self.equity_curve[-1][0]
            self.equity_curve[-1] = (last_date, self._calculate_equity())

        # Calculate metrics
        return self._calculate_results()

    def _process_signal(self, signal: SignalData, bar: BarData) -> None:
        """Process a trading signal.

        Only "buy" and "sell" are supported (long-only engine). Unknown signal
        types are recorded in rejected_signals so strategy bugs surface loudly.
        """
        signal_type = signal.get("type")
        symbol: str | None = signal.get("symbol")
        quantity = signal.get("quantity", 0)
        price = bar["close"]

        if symbol is None:
            return

        # Apply slippage
        if self.config.slippage_rate > 0:
            if signal_type == "buy":
                price *= 1 + self.config.slippage_rate
            elif signal_type == "sell":
                price *= 1 - self.config.slippage_rate

        if signal_type == "buy":
            self._open_position(symbol, price, quantity)
        elif signal_type == "sell":
            if symbol in self.positions:
                self._close_position(symbol, price, quantity if quantity > 0 else None)
            elif self._current_date is not None:
                # Sell with no open position: record it instead of silently
                # dropping it, so a strategy bug surfaces (8A).
                self.rejected_signals.append(
                    RejectedSignal(
                        date=self._current_date,
                        symbol=symbol,
                        signal_type="sell",
                        quantity=quantity,
                        price=price,
                        reason="Sell signal for a symbol with no open position",
                    )
                )
        elif self._current_date is not None:
            self.rejected_signals.append(
                RejectedSignal(
                    date=self._current_date,
                    symbol=symbol,
                    signal_type=str(signal_type),
                    quantity=quantity,
                    price=price,
                    reason=f"Unsupported signal type: {signal_type!r} (engine is long-only)",
                )
            )

    def _open_position(self, symbol: str, price: float, quantity: float) -> None:
        """Open or add to a long position.

        Buying into an existing position averages the entry price by cost.
        If the buy cannot be afforded, the signal is recorded in
        rejected_signals for debugging.
        """
        if self._current_date is None:
            return

        cost = price * quantity
        commission = self.config.commission_rate

        if cost + commission > self.cash:
            # Track rejected signal for debugging
            self.rejected_signals.append(
                RejectedSignal(
                    date=self._current_date,
                    symbol=symbol,
                    signal_type="buy",
                    quantity=quantity,
                    price=price,
                    reason=f"Insufficient cash: need ${cost + commission:.2f}, have ${self.cash:.2f}",
                )
            )
            return

        self.cash -= cost + commission

        existing = self.positions.get(symbol)
        if existing is not None:
            # Add to position: cost-weighted average entry price
            total_quantity = existing.quantity + quantity
            existing.entry_price = (
                existing.entry_price * existing.quantity + price * quantity
            ) / total_quantity
            existing.quantity = total_quantity
            existing.entry_commission_remaining += commission
        else:
            self.positions[symbol] = Position(
                symbol=symbol,
                side="long",
                entry_price=price,
                quantity=quantity,
                entry_date=self._current_date,
                entry_commission_remaining=commission,
            )

    def _close_position(self, symbol: str, price: float, quantity: float | None = None) -> None:
        """Close all or part of an existing position.

        Args:
            symbol: Position to close.
            price: Execution price.
            quantity: Quantity to sell; None (or >= position size) closes fully.
        """
        pos = self.positions.get(symbol)
        if pos is None or self._current_date is None:
            return

        exit_commission = self.config.commission_rate
        sell_quantity = pos.quantity if quantity is None else min(quantity, pos.quantity)
        if sell_quantity <= 0:
            return

        # Allocate the entry commission (paid once for the whole position) to this
        # exit in proportion to the quantity sold, so commission is counted once
        # per fill and trade P&L reconciles with the cash/equity curve even on
        # partial exits (6A). commission_rate is a flat per-fill fee, not a %.
        if sell_quantity >= pos.quantity:
            entry_commission_alloc = pos.entry_commission_remaining
        else:
            entry_commission_alloc = pos.entry_commission_remaining * (sell_quantity / pos.quantity)

        trade = Trade(
            entry_date=pos.entry_date,
            exit_date=self._current_date,
            symbol=symbol,
            side=pos.side,
            entry_price=pos.entry_price,
            exit_price=price,
            quantity=sell_quantity,
            commission=entry_commission_alloc + exit_commission,
        )

        self.trades.append(trade)
        # Only the exit commission hits cash here; the entry commission was
        # already debited when the position was opened.
        self.cash += price * sell_quantity - exit_commission

        if sell_quantity >= pos.quantity:
            del self.positions[symbol]
        else:
            pos.entry_commission_remaining -= entry_commission_alloc
            pos.quantity -= sell_quantity

    def _close_all_positions(self) -> None:
        """Close all open positions at the last known price per symbol."""
        for symbol in list(self.positions.keys()):
            price = self._last_prices.get(symbol)
            if price:
                self._close_position(symbol, price)
            else:
                # No usable last price to liquidate against: record it instead
                # of silently leaving the position out of the trade ledger (8A).
                pos = self.positions[symbol]
                self.rejected_signals.append(
                    RejectedSignal(
                        date=self._current_date or pos.entry_date,
                        symbol=symbol,
                        signal_type="close",
                        quantity=pos.quantity,
                        price=0.0,
                        reason="Could not close position at end of run: no last price available",
                    )
                )

    def _calculate_equity(self) -> float:
        """Calculate current equity from cash and marked-to-market positions."""
        equity = self.cash

        for symbol, pos in self.positions.items():
            price = self._last_prices.get(symbol, pos.entry_price)
            equity += pos.quantity * price

        return equity

    def _calculate_results(self) -> BacktestResult:
        """Calculate backtest metrics via the shared metrics module."""
        if not self.equity_curve:
            # No trading occurred, return initial capital as final equity
            return BacktestResult(final_equity=self.config.initial_capital)

        initial = self.config.initial_capital

        # All annualized metrics use the daily grid so they are correct for
        # any bar timeframe (identity transform for daily bars).
        daily_curve = metrics.resample_daily(self.equity_curve)
        daily_equities = np.array([e[1] for e in daily_curve])

        total_return, annual_return, daily_returns_list = metrics.calculate_returns(
            daily_equities, initial, len(daily_equities)
        )
        daily_returns_arr = np.array(daily_returns_list)

        monthly_returns = metrics.calculate_monthly_returns(daily_curve, initial)
        sharpe_ratio = metrics.calculate_sharpe_ratio(daily_returns_arr, self.config.risk_free_rate)
        sortino_ratio = metrics.calculate_sortino_ratio(
            daily_returns_arr, self.config.risk_free_rate
        )
        max_drawdown, max_dd_duration = metrics.calculate_max_drawdown(daily_equities)

        # Exposure time (percentage of days with positions)
        exposure_time = (
            (self._days_with_position / self._total_days * 100) if self._total_days > 0 else 0
        )

        trades_with_pnl = cast(list[metrics.TradeWithPnl], self.trades)
        win_rate, profit_factor = metrics.calculate_trade_statistics(trades_with_pnl)

        return BacktestResult(
            trades=self.trades,
            equity_curve=self.equity_curve,
            daily_equity_curve=daily_curve,
            rejected_signals=self.rejected_signals,
            final_equity=_finite(float(daily_equities[-1]), initial),
            total_return=_finite(total_return),
            annual_return=_finite(annual_return),
            sharpe_ratio=_finite(sharpe_ratio),
            sortino_ratio=_finite(sortino_ratio),
            max_drawdown=_finite(max_drawdown),
            max_drawdown_duration=max_dd_duration,
            win_rate=_finite(win_rate),
            profit_factor=(
                profit_factor if (profit_factor is None or math.isfinite(profit_factor)) else None
            ),
            daily_returns=daily_returns_list,
            monthly_returns=monthly_returns,
            exposure_time=_finite(exposure_time),
        )

    # Convenience methods for strategies
    def get_position(self, symbol: str) -> Position | None:
        """Get current position for a symbol."""
        return self.positions.get(symbol)

    def has_position(self, symbol: str) -> bool:
        """Check if there's an open position for a symbol."""
        return symbol in self.positions

    def get_cash(self) -> float:
        """Get available cash."""
        return self.cash

    def get_equity(self) -> float:
        """Get current equity (approximate)."""
        if self.equity_curve:
            return self.equity_curve[-1][1]
        return self.cash
