"""Trading domain events.

All events that can occur during trading operations. Events are immutable
facts that are appended to the event store and used to reconstruct state.
"""

from dataclasses import dataclass, field
from decimal import Decimal
from typing import ClassVar, Literal
from uuid import UUID

from src.events.base import TradingEvent, register_event

# =============================================================================
# Signal Events
# =============================================================================


@register_event
@dataclass(kw_only=True)
class SignalGenerated(TradingEvent):
    """A trading signal was generated by the strategy.

    Emitted when the strategy logic produces a buy/sell/short/cover signal.
    """

    EVENT_TYPE: ClassVar[str] = "signal.generated"

    symbol: str
    signal_type: Literal["buy", "sell", "short", "cover"]
    price: Decimal  # Price at time of signal
    qty: Decimal  # Suggested quantity
    confidence: float = 1.0  # Strategy confidence (0-1)
    indicators: dict = field(default_factory=dict)  # Indicator values at signal time


@register_event
@dataclass(kw_only=True)
class SignalRejected(TradingEvent):
    """A trading signal was rejected before order submission.

    Emitted when a signal fails risk checks or other validation.
    """

    EVENT_TYPE: ClassVar[str] = "signal.rejected"

    symbol: str
    signal_type: Literal["buy", "sell", "short", "cover"]
    reason: str  # Why rejected: "risk_check_failed", "circuit_breaker", etc.
    details: dict = field(default_factory=dict)


# =============================================================================
# Order Events
# =============================================================================


@register_event
@dataclass(kw_only=True)
class OrderSubmitted(TradingEvent):
    """An order was submitted to the broker.

    This is the intent event - we're attempting to place an order.
    The order may or may not be accepted by the broker.
    """

    EVENT_TYPE: ClassVar[str] = "order.submitted"

    order_id: UUID  # Our internal order ID
    client_order_id: str  # Idempotency key sent to broker
    symbol: str
    side: Literal["buy", "sell"]
    qty: Decimal
    order_type: Literal["market", "limit", "stop", "stop_limit"]
    time_in_force: str = "day"
    limit_price: Decimal | None = None
    stop_price: Decimal | None = None
    # Bracket order info
    stop_loss_price: Decimal | None = None
    take_profit_price: Decimal | None = None
    parent_order_id: UUID | None = None  # For bracket orders


@register_event
@dataclass(kw_only=True)
class OrderAccepted(TradingEvent):
    """Broker accepted the order.

    The order is now live and may fill.
    """

    EVENT_TYPE: ClassVar[str] = "order.accepted"

    order_id: UUID
    broker_order_id: str  # Alpaca's order ID


@register_event
@dataclass(kw_only=True)
class OrderRejected(TradingEvent):
    """Broker rejected the order.

    The order will not fill.
    """

    EVENT_TYPE: ClassVar[str] = "order.rejected"

    order_id: UUID
    reason: str
    broker_message: str | None = None


@register_event
@dataclass(kw_only=True)
class OrderFilled(TradingEvent):
    """Order was completely filled.

    All requested quantity has been executed.
    """

    EVENT_TYPE: ClassVar[str] = "order.filled"

    order_id: UUID
    symbol: str
    side: Literal["buy", "sell"]
    filled_qty: Decimal
    filled_avg_price: Decimal
    commission: Decimal = Decimal("0")


@register_event
@dataclass(kw_only=True)
class OrderPartiallyFilled(TradingEvent):
    """Order was partially filled.

    Some quantity executed, order still open for remainder.
    """

    EVENT_TYPE: ClassVar[str] = "order.partially_filled"

    order_id: UUID
    symbol: str
    side: Literal["buy", "sell"]
    filled_qty: Decimal  # Cumulative filled
    filled_avg_price: Decimal
    remaining_qty: Decimal


@register_event
@dataclass(kw_only=True)
class OrderCancelled(TradingEvent):
    """Order was cancelled.

    May be user-initiated or broker-initiated (e.g., end of day).
    """

    EVENT_TYPE: ClassVar[str] = "order.cancelled"

    order_id: UUID
    reason: str  # "user_requested", "bracket_oco", "end_of_day", etc.
    filled_qty: Decimal = Decimal("0")  # In case of partial fill before cancel


# =============================================================================
# Position Events
# =============================================================================


@register_event
@dataclass(kw_only=True)
class PositionOpened(TradingEvent):
    """A new position was opened.

    Emitted when first shares of a symbol are acquired.
    """

    EVENT_TYPE: ClassVar[str] = "position.opened"

    symbol: str
    side: Literal["long", "short"]
    qty: Decimal
    entry_price: Decimal
    order_id: UUID  # The fill that opened this position


@register_event
@dataclass(kw_only=True)
class PositionIncreased(TradingEvent):
    """An existing position was increased.

    More shares added to an existing position.
    """

    EVENT_TYPE: ClassVar[str] = "position.increased"

    symbol: str
    qty_added: Decimal
    price: Decimal
    new_total_qty: Decimal
    new_avg_cost: Decimal
    order_id: UUID


@register_event
@dataclass(kw_only=True)
class PositionReduced(TradingEvent):
    """An existing position was reduced.

    Some shares sold/covered but position remains open.
    """

    EVENT_TYPE: ClassVar[str] = "position.reduced"

    symbol: str
    qty_removed: Decimal
    exit_price: Decimal
    remaining_qty: Decimal
    realized_pnl: Decimal
    order_id: UUID


@register_event
@dataclass(kw_only=True)
class PositionClosed(TradingEvent):
    """A position was fully closed.

    All shares sold/covered.
    """

    EVENT_TYPE: ClassVar[str] = "position.closed"

    symbol: str
    exit_price: Decimal
    realized_pnl: Decimal
    order_id: UUID


# =============================================================================
# Session Events
# =============================================================================


@register_event
@dataclass(kw_only=True)
class SessionStarted(TradingEvent):
    """Trading session was started."""

    EVENT_TYPE: ClassVar[str] = "session.started"

    strategy_id: UUID
    strategy_name: str
    mode: Literal["live", "paper"]
    symbols: list[str] = field(default_factory=list)
    starting_equity: Decimal = Decimal("0")


@register_event
@dataclass(kw_only=True)
class SessionStopped(TradingEvent):
    """Trading session was stopped."""

    EVENT_TYPE: ClassVar[str] = "session.stopped"

    reason: str  # "user_requested", "error", "end_of_day", etc.
    final_equity: Decimal | None = None
    total_pnl: Decimal | None = None


@register_event
@dataclass(kw_only=True)
class SessionPaused(TradingEvent):
    """Trading session was paused."""

    EVENT_TYPE: ClassVar[str] = "session.paused"

    reason: str


@register_event
@dataclass(kw_only=True)
class SessionResumed(TradingEvent):
    """Trading session was resumed."""

    EVENT_TYPE: ClassVar[str] = "session.resumed"


# =============================================================================
# Circuit Breaker Events
# =============================================================================


@register_event
@dataclass(kw_only=True)
class CircuitBreakerTriggered(TradingEvent):
    """Circuit breaker was triggered, trading paused."""

    EVENT_TYPE: ClassVar[str] = "circuit_breaker.triggered"

    reason: str  # "consecutive_losses", "daily_loss_limit", etc.
    details: dict = field(default_factory=dict)


@register_event
@dataclass(kw_only=True)
class CircuitBreakerReset(TradingEvent):
    """Circuit breaker was reset, trading can resume."""

    EVENT_TYPE: ClassVar[str] = "circuit_breaker.reset"

    was_forced: bool = False  # True if reset before cooldown elapsed


# =============================================================================
# Reconciliation Events
# =============================================================================


@register_event
@dataclass(kw_only=True)
class ReconciliationPerformed(TradingEvent):
    """Position reconciliation was performed with broker.

    Emitted when we sync our state with the broker's actual state.
    """

    EVENT_TYPE: ClassVar[str] = "reconciliation.performed"

    positions_added: list[str] = field(default_factory=list)
    positions_removed: list[str] = field(default_factory=list)
    positions_adjusted: list[str] = field(default_factory=list)
    orders_synced: int = 0
    discrepancies_found: int = 0


@register_event
@dataclass(kw_only=True)
class ExternalTradeDetected(TradingEvent):
    """A trade was detected that wasn't initiated by our system.

    E.g., manual trade via broker dashboard.
    """

    EVENT_TYPE: ClassVar[str] = "reconciliation.external_trade"

    symbol: str
    side: Literal["buy", "sell"]
    qty: Decimal
    price: Decimal
    broker_order_id: str
